from time import sleep
from Web.TradoAdmin.User.locators import User_Locator
from Web.TradoAdmin.base.base import BaseSetups
from Web.TradoAdmin.Product.locators import Product_Locator
from selenium.webdriver.common.by import By
class Test_All_Users(BaseSetups, User_Locator, Product_Locator):
    def User_Link(self):
        self.setup_trado()
        self.fields(By.XPATH, self.PHONE, "1952222222")
        self.click(By.XPATH, self.PHONE_BUTTON)
        sleep(1)
        self.fields(By.XPATH, self.CODE, "1234")
        sleep(1)
        self.click(By.XPATH, self.SAVE_BUTTON)
        sleep(1)
        self.click(By.XPATH, self.CONNECT)
        sleep(1)
        self.click(By.XPATH, self.USER)
    def search_button_user(self):
        self.setup_trado()
        self.fields(By.XPATH, self.PHONE, "1952222222")
        sleep(1)
        self.click(By.XPATH, self.PHONE_BUTTON)
        sleep(1)
        self.fields(By.XPATH, self.CODE, "1234")
        sleep(1)
        self.click(By.XPATH, self.SAVE_BUTTON)
        sleep(1)
        self.click(By.XPATH, self.CONNECT)
        sleep(1)
        self.click(By.XPATH, self.USER)
        self.click(By.XPATH, self.SEARCH_BUTTO)
    def search_charactor(self):
        self.setup_trado()
        self.fields(By.XPATH, self.PHONE, "1952222222")
        sleep(1)
        self.click(By.XPATH, self.PHONE_BUTTON)
        sleep(1)
        self.fields(By.XPATH, self.CODE, "1234")
        sleep(1)
        self.click(By.XPATH, self.SAVE_BUTTON)
        sleep(1)
        self.click(By.XPATH, self.CONNECT)
        sleep(1)
        self.click(By.XPATH, self.USER)
        self.fields(By.XPATH, self.SEARCH_BUTTO, "fdwuy")
    def next_user(self):
        self.setup_trado()
        self.fields(By.XPATH, self.PHONE, "1952222222")
        sleep(1)
        self.click(By.XPATH, self.PHONE_BUTTON)
        sleep(1)
        self.fields(By.XPATH, self.CODE, "1234")
        sleep(1)
        self.click(By.XPATH, self.SAVE_BUTTON)
        sleep(1)
        self.click(By.XPATH, self.CONNECT)
        sleep(1)
        self.click(By.XPATH, self.USER)
        self.click(By.XPATH, self.NEXT_USER)
    def back_user(self):
        self.setup_trado()
        self.fields(By.XPATH, self.PHONE, "1952222222")
        sleep(1)
        self.click(By.XPATH, self.PHONE_BUTTON)
        sleep(1)
        self.fields(By.XPATH, self.CODE, "1234")
        sleep(1)
        self.click(By.XPATH, self.SAVE_BUTTON)
        sleep(1)
        self.click(By.XPATH, self.CONNECT)
        sleep(1)
        self.click(By.XPATH, self.USER)
        self.click(By.XPATH, self.BACK_USER)
    def forward_user(self):
        self.setup_trado()
        self.fields(By.XPATH, self.PHONE, "1952222222")
        sleep(1)
        self.click(By.XPATH, self.PHONE_BUTTON)
        sleep(1)
        self.fields(By.XPATH, self.CODE, "1234")
        sleep(1)
        self.click(By.XPATH, self.SAVE_BUTTON)
        sleep(1)
        self.click(By.XPATH, self.CONNECT)
        sleep(1)
        self.click(By.XPATH, self.USER)
        self.click(By.XPATH, self.FORWARD_USER)
    def backward_user(self):
        self.setup_trado()
        self.fields(By.XPATH, self.PHONE, "1952222222")
        sleep(1)
        self.click(By.XPATH, self.PHONE_BUTTON)
        sleep(1)
        self.fields(By.XPATH, self.CODE, "1234")
        sleep(1)
        self.click(By.XPATH, self.SAVE_BUTTON)
        sleep(1)
        self.click(By.XPATH, self.CONNECT)
        sleep(1)
        self.click(By.XPATH, self.USER)
        self.click(By.XPATH, self.BACKWARD_USER)
    def photo_user(self):
        self.setup_trado()
        self.fields(By.XPATH, self.PHONE, "1952222222")
        sleep(1)
        self.click(By.XPATH, self.PHONE_BUTTON)
        sleep(1)
        self.fields(By.XPATH, self.CODE, "1234")
        sleep(1)
        self.click(By.XPATH, self.SAVE_BUTTON)
        sleep(1)
        self.click(By.XPATH, self.CONNECT)
        sleep(1)
        self.click(By.XPATH, self.USER)
        self.click(By.XPATH, self.ONE_ELEMENT)
        self.click(By.XPATH, self.PHOTO_USER)
    def first_name_user(self):
        self.setup_trado()
        self.fields(By.XPATH, self.PHONE, "1952222222")
        sleep(1)
        self.click(By.XPATH, self.PHONE_BUTTON)
        sleep(1)
        self.fields(By.XPATH, self.CODE, "1234")
        sleep(1)
        self.click(By.XPATH, self.SAVE_BUTTON)
        sleep(1)
        self.click(By.XPATH, self.CONNECT)
        sleep(1)
        self.click(By.XPATH, self.USER)
        self.click(By.XPATH, self.ONE_ELEMENT)
        self.fields(By.XPATH, self.FIRSTNAME_USER, "gddiuj")
    def last_name_user(self):
        self.setup_trado()
        self.fields(By.XPATH, self.PHONE, "1952222222")
        sleep(1)
        self.click(By.XPATH, self.PHONE_BUTTON)
        sleep(1)
        self.fields(By.XPATH, self.CODE, "1234")
        sleep(1)
        self.click(By.XPATH, self.SAVE_BUTTON)
        sleep(1)
        self.click(By.XPATH, self.CONNECT)
        sleep(1)
        self.click(By.XPATH, self.USER)
        self.click(By.XPATH, self.ONE_ELEMENT)
        self.fields(By.XPATH, self.LASTNAME_USER, "gddiuj")
    def phone_user(self):
        self.setup_trado()
        self.fields(By.XPATH, self.PHONE, "1952222222")
        sleep(1)
        self.click(By.XPATH, self.PHONE_BUTTON)
        sleep(1)
        self.fields(By.XPATH, self.CODE, "1234")
        sleep(1)
        self.click(By.XPATH, self.SAVE_BUTTON)
        sleep(1)
        self.click(By.XPATH, self.CONNECT)
        sleep(1)
        self.click(By.XPATH, self.USER)
        self.click(By.XPATH, self.ONE_ELEMENT)
        self.fields(By.XPATH, self.PHOTO_USER, "452678921")
    def shop_user(self):
        self.setup_trado()
        self.fields(By.XPATH, self.PHONE, "1952222222")
        sleep(1)
        self.click(By.XPATH, self.PHONE_BUTTON)
        sleep(1)
        self.fields(By.XPATH, self.CODE, "1234")
        sleep(1)
        self.click(By.XPATH, self.SAVE_BUTTON)
        sleep(1)
        self.click(By.XPATH, self.CONNECT)
        self.click(By.XPATH, self.USER)
        self.click(By.XPATH, self.ONE_ELEMENT)
        self.fields(By.XPATH, self.SHOP_USER, "tdgh")
    def email_user(self):
        self.setup_trado()
        self.fields(By.XPATH, self.PHONE, "1952222222")
        sleep(1)
        self.click(By.XPATH, self.PHONE_BUTTON)
        sleep(1)
        self.fields(By.XPATH, self.CODE, "1234")
        sleep(1)
        self.click(By.XPATH, self.SAVE_BUTTON)
        sleep(1)
        self.click(By.XPATH, self.CONNECT)
        sleep(1)
        self.click(By.XPATH, self.USER)
        self.click(By.XPATH, self.ONE_ELEMENT)
        self.fields(By.XPATH, self.EMAIL_USER, "dfxbxn@563")
    def additional_phone_user(self):
        self.setup_trado()
        self.fields(By.XPATH, self.PHONE, "1952222222")
        sleep(1)
        self.click(By.XPATH, self.PHONE_BUTTON)
        sleep(1)
        self.fields(By.XPATH, self.CODE, "1234")
        sleep(1)
        self.click(By.XPATH, self.SAVE_BUTTON)
        sleep(1)
        self.click(By.XPATH, self.CONNECT)
        sleep(1)
        self.click(By.XPATH, self.USER)
        self.click(By.XPATH, self.ONE_ELEMENT)
        self.fields(By.XPATH, self.ADDITIONAL_PHONE_USER, "2673497")
    def city_user(self):
        self.setup_trado()
        self.fields(By.XPATH, self.PHONE, "1952222222")
        sleep(1)
        self.click(By.XPATH, self.PHONE_BUTTON)
        sleep(1)
        self.fields(By.XPATH, self.CODE, "1234")
        sleep(1)
        self.click(By.XPATH, self.SAVE_BUTTON)
        sleep(1)
        self.click(By.XPATH, self.CONNECT)
        sleep(1)
        self.click(By.XPATH, self.USER)
        self.click(By.XPATH, self.ONE_ELEMENT)
        self.fields(By.XPATH, self.CITY_USER, "dgdjd")
    def street_user(self):
        self.setup_trado()
        self.fields(By.XPATH, self.PHONE, "1952222222")
        sleep(1)
        self.click(By.XPATH, self.PHONE_BUTTON)
        sleep(1)
        self.fields(By.XPATH, self.CODE, "1234")
        sleep(1)
        self.click(By.XPATH, self.SAVE_BUTTON)
        sleep(1)
        self.click(By.XPATH, self.CONNECT)
        sleep(1)
        self.click(By.XPATH, self.USER)
        self.click(By.XPATH, self.ONE_ELEMENT)
        self.fields(By.XPATH, self.STREET_USER, "dgdjd")
    def class_user(self):
        self.setup_trado()
        self.fields(By.XPATH, self.PHONE, "1952222222")
        sleep(1)
        self.click(By.XPATH, self.PHONE_BUTTON)
        sleep(1)
        self.fields(By.XPATH, self.CODE, "1234")
        sleep(1)
        self.click(By.XPATH, self.SAVE_BUTTON)
        sleep(1)
        self.click(By.XPATH, self.CONNECT)
        sleep(1)
        self.click(By.XPATH, self.USER)
        self.click(By.XPATH, self.ONE_ELEMENT)
        self.fields(By.XPATH, self.CLASS_USER, "dgdjd")
    def city_hall_user(self):
        self.setup_trado()
        self.fields(By.XPATH, self.PHONE, "1952222222")
        sleep(1)
        self.click(By.XPATH, self.PHONE_BUTTON)
        sleep(1)
        self.fields(By.XPATH, self.CODE, "1234")
        sleep(1)
        self.click(By.XPATH, self.SAVE_BUTTON)
        sleep(1)
        self.click(By.XPATH, self.CONNECT)
        sleep(1)
        self.click(By.XPATH, self.USER)
        self.click(By.XPATH, self.ONE_ELEMENT)
        self.fields(By.XPATH, self.CITY_HALL_USER, "dgdjd")
    def building_user(self):
        self.setup_trado()
        self.fields(By.XPATH, self.PHONE, "1952222222")
        sleep(1)
        self.click(By.XPATH, self.PHONE_BUTTON)
        sleep(1)
        self.fields(By.XPATH, self.CODE, "1234")
        sleep(1)
        self.click(By.XPATH, self.SAVE_BUTTON)
        sleep(1)
        self.click(By.XPATH, self.CONNECT)
        sleep(1)
        self.click(By.XPATH, self.USER)
        self.click(By.XPATH, self.ONE_ELEMENT)
        self.fields(By.XPATH, self.BUILDING_USER, "dgdjd")
    def floor_user(self):
        self.setup_trado()
        self.fields(By.XPATH, self.PHONE, "1952222222")
        sleep(1)
        self.click(By.XPATH, self.PHONE_BUTTON)
        sleep(1)
        self.fields(By.XPATH, self.CODE, "1234")
        sleep(1)
        self.click(By.XPATH, self.SAVE_BUTTON)
        sleep(1)
        self.click(By.XPATH, self.CONNECT)
        self.click(By.XPATH, self.USER)
        self.click(By.XPATH, self.ONE_ELEMENT)
        self.fields(By.XPATH, self.FLOOR_USER, "34")
    def account_number_user(self):
        self.setup_trado()
        self.fields(By.XPATH, self.PHONE, "1952222222")
        sleep(1)
        self.click(By.XPATH, self.PHONE_BUTTON)
        sleep(1)
        self.fields(By.XPATH, self.CODE, "1234")
        sleep(1)
        self.click(By.XPATH, self.SAVE_BUTTON)
        sleep(1)
        self.click(By.XPATH, self.CONNECT)
        self.click(By.XPATH, self.USER)
        self.click(By.XPATH, self.ONE_ELEMENT)
        self.fields(By.XPATH, self.ACCOUNT_OWNER_USER, "3442634")
    def number_branch_user(self):
        self.setup_trado()
        self.fields(By.XPATH, self.PHONE, "1952222222")
        sleep(1)
        self.click(By.XPATH, self.PHONE_BUTTON)
        sleep(1)
        self.fields(By.XPATH, self.CODE, "1234")
        sleep(1)
        self.click(By.XPATH, self.SAVE_BUTTON)
        sleep(1)
        self.click(By.XPATH, self.CONNECT)
        self.click(By.XPATH, self.USER)
        self.click(By.XPATH, self.ONE_ELEMENT)
        self.fields(By.XPATH, self.NUMBER_BRANCH, "3442634")
    def number_account_user(self):
        self.setup_trado()
        self.fields(By.XPATH, self.PHONE, "1952222222")
        sleep(1)
        self.click(By.XPATH, self.PHONE_BUTTON)
        sleep(1)
        self.fields(By.XPATH, self.CODE, "1234")
        sleep(1)
        self.click(By.XPATH, self.SAVE_BUTTON)
        sleep(1)
        self.click(By.XPATH, self.CONNECT)
        self.click(By.XPATH, self.USER)
        self.click(By.XPATH, self.ONE_ELEMENT)
        self.fields(By.XPATH, self.NUMBER_ACCOUNT_USER, "3442634")
    def bank_number_user(self):
        self.setup_trado()
        self.fields(By.XPATH, self.PHONE, "1952222222")
        sleep(1)
        self.click(By.XPATH, self.PHONE_BUTTON)
        sleep(1)
        self.fields(By.XPATH, self.CODE, "1234")
        sleep(1)
        self.click(By.XPATH, self.SAVE_BUTTON)
        sleep(1)
        self.click(By.XPATH, self.CONNECT)
        self.click(By.XPATH, self.USER)
        self.click(By.XPATH, self.ONE_ELEMENT)
        self.fields(By.XPATH, self.BANK_NUMBER_USER, "3442634")
    def credit_account_user(self):
        self.setup_trado()
        self.fields(By.XPATH, self.PHONE, "1952222222")
        sleep(1)
        self.click(By.XPATH, self.PHONE_BUTTON)
        sleep(1)
        self.fields(By.XPATH, self.CODE, "1234")
        sleep(1)
        self.click(By.XPATH, self.SAVE_BUTTON)
        sleep(1)
        self.click(By.XPATH, self.CONNECT)
        sleep(1)
        self.click(By.XPATH, self.USER)
        self.click(By.XPATH, self.ONE_ELEMENT)
        self.fields(By.XPATH, self.CREDITACCOUNT_USER, "3442634")
    def balance_user(self):
        self.setup_trado()
        self.fields(By.XPATH, self.PHONE, "1952222222")
        sleep(1)
        self.click(By.XPATH, self.PHONE_BUTTON)
        sleep(1)
        self.fields(By.XPATH, self.CODE, "1234")
        sleep(1)
        self.click(By.XPATH, self.SAVE_BUTTON)
        sleep(1)
        self.click(By.XPATH, self.CONNECT)
        sleep(1)
        self.click(By.XPATH, self.USER)
        self.click(By.XPATH, self.ONE_ELEMENT)
        self.fields(By.XPATH, self.BALANCE_USER, "3442634")
    def income_user(self):
        self.setup_trado()
        self.fields(By.XPATH, self.PHONE, "1952222222")
        sleep(1)
        self.click(By.XPATH, self.PHONE_BUTTON)
        sleep(1)
        self.fields(By.XPATH, self.CODE, "1234")
        sleep(1)
        self.click(By.XPATH, self.SAVE_BUTTON)
        sleep(1)
        self.click(By.XPATH, self.CONNECT)
        self.click(By.XPATH, self.USER)
        self.click(By.XPATH, self.ONE_ELEMENT)
        self.fields(By.XPATH, self.INCOME_USER, "3442634")
    def outcome_user(self):
        self.setup_trado()
        self.fields(By.XPATH, self.PHONE, "1952222222")
        sleep(1)
        self.click(By.XPATH, self.PHONE_BUTTON)
        sleep(1)
        self.fields(By.XPATH, self.CODE, "1234")
        sleep(1)
        self.click(By.XPATH, self.SAVE_BUTTON)
        sleep(1)
        self.click(By.XPATH, self.CONNECT)
        self.click(By.XPATH, self.USER)
        self.click(By.XPATH, self.ONE_ELEMENT)
        self.fields(By.XPATH, self.OUTCOME_USER, "3442634")
    def id_user(self):
        self.setup_trado()
        self.fields(By.XPATH, self.PHONE, "1952222222")
        sleep(1)
        self.click(By.XPATH, self.PHONE_BUTTON)
        sleep(1)
        self.fields(By.XPATH, self.CODE, "1234")
        sleep(1)
        self.click(By.XPATH, self.SAVE_BUTTON)
        sleep(1)
        self.click(By.XPATH, self.CONNECT)
        self.click(By.XPATH, self.USER)
        self.click(By.XPATH, self.ONE_ELEMENT)
        self.fields(By.XPATH, self.ID_USER, "3442634")
    def mailing_list_user(self):
        self.setup_trado()
        self.fields(By.XPATH, self.PHONE, "1952222222")
        sleep(1)
        self.click(By.XPATH, self.PHONE_BUTTON)
        sleep(1)
        self.fields(By.XPATH, self.CODE, "1234")
        sleep(1)
        self.click(By.XPATH, self.SAVE_BUTTON)
        sleep(1)
        self.click(By.XPATH, self.CONNECT)
        self.click(By.XPATH, self.USER)
        self.click(By.XPATH, self.ONE_ELEMENT)
        self.click(By.XPATH, self.MAILINGLIST_USER)
    def extera_user(self):
        self.setup_trado()
        self.fields(By.XPATH, self.PHONE, "1952222222")
        sleep(1)
        self.click(By.XPATH, self.PHONE_BUTTON)
        sleep(1)
        self.fields(By.XPATH, self.CODE, "1234")
        sleep(1)
        self.click(By.XPATH, self.SAVE_BUTTON)
        sleep(1)
        self.click(By.XPATH, self.CONNECT)
        self.click(By.XPATH, self.USER)
        self.click(By.XPATH, self.ONE_ELEMENT)
        self.click(By.XPATH, self.ETTRADOAPR_USER)
    def takanon_user(self):
        self.setup_trado()
        self.fields(By.XPATH, self.PHONE, "1952222222")
        sleep(1)
        self.click(By.XPATH, self.PHONE_BUTTON)
        sleep(1)
        self.fields(By.XPATH, self.CODE, "1234")
        sleep(1)
        self.click(By.XPATH, self.SAVE_BUTTON)
        sleep(1)
        self.click(By.XPATH, self.CONNECT)
        self.click(By.XPATH, self.USER)
        self.click(By.XPATH, self.ONE_ELEMENT)
        self.click(By.XPATH, self.TAKANON_USER)
    def bussiness_type_user(self):
        self.setup_trado()
        self.fields(By.XPATH, self.PHONE, "1952222222")
        sleep(1)
        self.click(By.XPATH, self.PHONE_BUTTON)
        sleep(1)
        self.fields(By.XPATH, self.CODE, "1234")
        sleep(1)
        self.click(By.XPATH, self.SAVE_BUTTON)
        sleep(1)
        self.click(By.XPATH, self.CONNECT)
        self.click(By.XPATH, self.USER)
        self.click(By.XPATH, self.ONE_ELEMENT)
        self.fields(By.XPATH, self.BUSSINES_TYPE_USER, "3442634")
    def button_user(self):
        self.setup_trado()
        self.fields(By.XPATH, self.PHONE, "1952222222")
        sleep(1)
        self.click(By.XPATH, self.PHONE_BUTTON)
        sleep(1)
        self.fields(By.XPATH, self.CODE, "1234")
        sleep(1)
        self.click(By.XPATH, self.SAVE_BUTTON)
        sleep(1)
        self.click(By.XPATH, self.CONNECT)
        self.click(By.XPATH, self.USER)
        self.click(By.XPATH, self.ONE_ELEMENT)
        self.click(By.XPATH, self.MODIFY_BUTTON)
    def end_to_end_user(self):
        self.setup_trado()
        self.fields(By.XPATH, self.PHONE, "1952222222")
        sleep(1)
        self.click(By.XPATH, self.PHONE_BUTTON)
        sleep(1)
        self.fields(By.XPATH, self.CODE, "1234")
        sleep(1)
        self.click(By.XPATH, self.SAVE_BUTTON)
        sleep(1)
        self.click(By.XPATH, self.CONNECT)
        self.click(By.XPATH, self.USER)
        self.click(By.XPATH, self.ONE_ELEMENT)
        self.fields(By.XPATH, self.FIRSTNAME_USER, "rteyt")
        self.fields(By.XPATH, self.LASTNAME_USER, "rteyt")
        self.fields(By.XPATH, self.PHONE_USER, "325678")
        self.fields(By.XPATH, self.SHOP_USER, "rteyt")
        self.fields(By.XPATH, self.EMAIL_USER, "rteyt")
        self.fields(By.XPATH, self.ADDITIONAL_PHONE_USER, "234567")
        self.fields(By.XPATH, self.CITY_USER, "rteyt")
        self.fields(By.XPATH, self.STREET_USER, "rteyt")
        self.fields(By.XPATH, self.CLASS_USER, "rteyt")
        self.fields(By.XPATH, self.BUILDING_USER, "rteyt")
        self.fields(By.XPATH, self.FLOOR_USER, "23")
        self.fields(By.XPATH, self.ACCOUNT_OWNER_USER, "rteyt")
        self.fields(By.XPATH, self.NUMBER_BRANCH, "6")
        self.fields(By.XPATH, self.NUMBER_ACCOUNT_USER, "4")
        self.fields(By.XPATH, self.BANK_NUMBER_USER, "3465789")
        self.click(By.XPATH, self.CREDITACCOUNT_USER)
        self.fields(By.XPATH, self.BALANCE_USER, "5687")
        self.fields(By.XPATH, self.INCOME_USER, "367")
        self.fields(By.XPATH, self.OUTCOME_USER, "3456")
        self.fields(By.XPATH, self.ID_USER, "rteyt")
        self.click(By.XPATH, self.MAILINGLIST_USER)
        self.click(By.XPATH, self.ETTRADOAPR_USER)
        self.click(By.XPATH, self.TAKANON_USER)
        self.fields(By.XPATH, self.BUSSINES_TYPE_USER, "rteyt")
        self.click(By.XPATH, self.MODIFY_BUTTON)
    def first_name_nuber_user(self):
        self.setup_trado()
        self.fields(By.XPATH, self.PHONE, "1952222222")
        sleep(1)
        self.click(By.XPATH, self.PHONE_BUTTON)
        sleep(1)
        self.fields(By.XPATH, self.CODE, "1234")
        sleep(1)
        self.click(By.XPATH, self.SAVE_BUTTON)
        sleep(1)
        self.click(By.XPATH, self.CONNECT)
        self.click(By.XPATH, self.USER)
        self.click(By.XPATH, self.ONE_ELEMENT)
        self.click(By.XPATH, self.FIRSTNAME_USER)





