class department_Locator:
    TRADO_ADMIN = "https://qa-admin.trado.co.il/#/login"
    PHONE = "//body/div[@id='root']/div[1]/div[2]/div[1]/span[1]/form[1]/div[1]/div[1]/span[1]/div[1]/input[1]"
    PHONE_BUTTON = "//body/div[@id='root']/div[1]/div[2]/div[1]/span[1]/form[1]/input[1]"
    CODE_PHONE = "//body/div[@id='root']/div[1]/div[2]/div[1]/span[1]/form[1]/div[1]/div[1]/span[1]/div[1]/input[1]"
    CONNECT = "//body/div[@id='root']/div[1]/div[2]/div[1]/span[1]/form[1]/input[1]"
    DEPARTMENT = "//span[contains(text(),'מחלקות')]"
    SEARCH_DEPARTMENT = "//body/div[@id='root']/div[1]/div[2]/main[1]/div[2]/div[1]/div[1]/span[1]/span[1]/div[1]/input[1]"
    ID = "//thead/tr/th[1]"
    NAME = "//thead/tr/th[2]"
    PHOTO = "//thead/tr/th[3]"
    ACTIVE = "//thead/tr/th[5]"
    DATE_FINISH = "//thead/tr/th[6]"
    PHOTO_BACKGROUND = "//thead/tr/th[3]"
    CLICK_DOT = "//body/div[@id='root']/div[1]/div[2]/main[1]/div[2]/div[1]/div[1]/div[1]/span[1]/i[1]"
    ADD_DOT = "//span[contains(text(),'הוספה')]"
    NAME_DPT = "//body/div[@id='root']/div[1]/div[4]/div[1]/div[1]/form[1]/div[1]/div[1]/span[1]/div[1]/input[1]"
    CLICK_PHOTO = "//body/div[@id='root']/div[1]/div[4]/div[1]/div[1]/form[1]/div[1]/div[2]/div[1]/input[1]"
    ADD_PHOTO = "//body/div[@id='root']/div[1]/div[4]/div[1]/div[1]/form[1]/div[1]/div[2]/div[1]/input[1]"
    DOWNLOAD = "//span[contains(text(),'ייצוא')]"

