class  order_locator_click():
    TRADO_ADMIN = "https://qa-admin.trado.co.il/#/login"
    PHONE = "//body/div[@id='root']/div[1]/div[2]/div[1]/span[1]/form[1]/div[1]/div[1]/span[1]/div[1]/input[1]"
    PHONE_BUTTON = "//body/div[@id='root']/div[1]/div[2]/div[1]/span[1]/form[1]/input[1]"
    CODE_PHONE = "//body/div[@id='root']/div[1]/div[2]/div[1]/span[1]/form[1]/div[1]/div[1]/span[1]/div[1]/input[1]"
    CONNECT = "//body/div[@id='root']/div[1]/div[2]/div[1]/span[1]/form[1]/input[1]"
    ORDER_CLICK = "//span[contains(text(),'הזמנות')]"
    RECIEVED = "//span[contains(text(),'התקבלה')]"
    NUMBER = "//thead/tr/th[1]"
    STATUS = "//thead/tr/th[2]"
    ISMAIN = "//thead/tr/th[3]"
    ORDER = "//thead/tr/th[4]"
    FIRST_NAME ="//thead/tr/th[5]"
    LAST_NAME = "//thead/tr/th[6]"
    ADDRESS = "//thead/tr/th[7]"
    PHONE_NUMBER = "//thead/tr/th[8]"
    SUM = "//thead/tr/th[9]"
    DELIVERY_TIME = "//thead/tr/th[10]"
    PAYMENT_TYPE = "//thead/tr/th[11]"
    READY = "//span[contains(text(),'מוכנה')]"
    SEND = "//span[contains(text(),'מוכנה')]"
    FINISHED = "//span[contains(text(),'מוכנה')]"
    DOT_CLICK = "//body/div[@id='root']/div[1]/div[2]/main[1]/div[2]/div[1]/div[2]/div[1]/div[1]/div[1]/span[1]/i[1]"
    DOWNLOAD = "//span[contains(text(),'ייצוא')]"
    DOWNLOAD_RECEVIED = "//span[contains(text(),'ייצוא')]"
    SEARCH = "//body/div[@id='root']/div[1]/div[2]/main[1]/div[2]/div[1]/div[2]/div[1]/div[1]/span[1]/span[1]/div[1]/input[1]"



