import time
from Web.TradoAdmin.base.base import BaseSetups
from selenium.webdriver.common.by import By
class TestAll_pages(BaseSetups):
   def order(self):
        self.setup_trado()
        self.fields(By.XPATH, self.PHONE, "1952222222")
        time.sleep(2)
        self.click(By.XPATH, self.PHONE_BUTTON)
        time.sleep(2)
        self.fields(By.XPATH, self. CODE_PHONE, "1234")
        time.sleep(2)
        self.click(By.XPATH, self.CONNECT)
        self.click(By.XPATH, self.ORDER_CLICK)
        self.click(By.XPATH, self.RECIEVED)
        self.click(By.XPATH, self.NUMBER)

   def order_1(self):
        self.setup_trado()
        self.fields(By.XPATH, self.PHONE, "1952222222")
        time.sleep(2)
        self.click(By.XPATH, self.PHONE_BUTTON)
        time.sleep(2)
        self.fields(By.XPATH, self.CODE_PHONE, "1234")
        time.sleep(2)
        self.click(By.XPATH, self.CONNECT)
        self.click(By.XPATH, self.ORDER_CLICK)
        self.click(By.XPATH, self.RECIEVED)
        self.click(By.XPATH, self.STATUS)

   def order_2(self):
        self.setup_trado()
        self.fields(By.XPATH, self.PHONE, "1952222222")
        time.sleep(2)
        self.click(By.XPATH, self.PHONE_BUTTON)
        time.sleep(2)
        self.fields(By.XPATH, self.CODE_PHONE, "1234")
        time.sleep(2)
        self.click(By.XPATH, self.CONNECT)
        self.click(By.XPATH, self.ORDER_CLICK)
        self.click(By.XPATH, self.RECIEVED)
        self.click(By.XPATH, self.ISMAIN)

   def order_3(self):
        self.setup_trado()
        self.fields(By.XPATH, self.PHONE, "1952222222")
        time.sleep(2)
        self.click(By.XPATH, self.PHONE_BUTTON)
        time.sleep(2)
        self.fields(By.XPATH, self.CODE_PHONE, "1234")
        time.sleep(2)
        self.click(By.XPATH, self.CONNECT)
        self.click(By.XPATH, self.ORDER_CLICK)
        self.click(By.XPATH, self.RECIEVED)
        self.click(By.XPATH, self.ORDER)

   def order_4(self):
        self.setup_trado()
        self.fields(By.XPATH, self.PHONE, "1952222222")
        time.sleep(2)
        self.click(By.XPATH, self.PHONE_BUTTON)
        time.sleep(2)
        self.fields(By.XPATH, self.CODE_PHONE, "1234")
        time.sleep(2)
        self.click(By.XPATH, self.CONNECT)
        self.click(By.XPATH, self.ORDER_CLICK)
        self.click(By.XPATH, self.RECIEVED)
        self.click(By.XPATH, self.FIRST_NAME)

   def order_5(self):
        self.setup_trado()
        self.fields(By.XPATH, self.PHONE, "1952222222")
        time.sleep(2)
        self.click(By.XPATH, self.PHONE_BUTTON)
        time.sleep(2)
        self.fields(By.XPATH, self.CODE_PHONE, "1234")
        time.sleep(2)
        self.click(By.XPATH, self.CONNECT)
        self.click(By.XPATH, self.ORDER_CLICK)
        self.click(By.XPATH, self.RECIEVED)
        self.click(By.XPATH, self.LAST_NAME)

   def order_6(self):
        self.setup_trado()
        self.fields(By.XPATH, self.PHONE, "1952222222")
        time.sleep(2)
        self.click(By.XPATH, self.PHONE_BUTTON)
        time.sleep(2)
        self.fields(By.XPATH, self.CODE_PHONE, "1234")
        time.sleep(2)
        self.click(By.XPATH, self.CONNECT)
        self.click(By.XPATH, self.ORDER_CLICK)
        self.click(By.XPATH, self.RECIEVED)
        self.click(By.XPATH, self.ADDRESS)

   def order_7(self):
        self.setup_trado()
        self.fields(By.XPATH, self.PHONE, "1952222222")
        time.sleep(2)
        self.click(By.XPATH, self.PHONE_BUTTON)
        time.sleep(2)
        self.fields(By.XPATH, self.CODE_PHONE, "1234")
        time.sleep(2)
        self.click(By.XPATH, self.CONNECT)
        self.click(By.XPATH, self.ORDER_CLICK)
        self.click(By.XPATH, self.RECIEVED)
        self.click(By.XPATH, self.PHONE_NUMBER)

   def order_8(self):
        self.setup_trado()
        self.fields(By.XPATH, self.PHONE, "1952222222")
        time.sleep(2)
        self.click(By.XPATH, self.PHONE_BUTTON)
        time.sleep(2)
        self.fields(By.XPATH, self.CODE_PHONE, "1234")
        time.sleep(2)
        self.click(By.XPATH, self.CONNECT)
        self.click(By.XPATH, self.ORDER_CLICK)
        self.click(By.XPATH, self.RECIEVED)
        self.click(By.XPATH, self.SUM)

   def order_9(self):
        self.setup_trado()
        self.fields(By.XPATH, self.PHONE, "1952222222")
        time.sleep(2)
        self.click(By.XPATH, self.PHONE_BUTTON)
        time.sleep(2)
        self.fields(By.XPATH, self.CODE_PHONE, "1234")
        time.sleep(2)
        self.click(By.XPATH, self.CONNECT)
        self.click(By.XPATH, self.ORDER_CLICK)
        self.click(By.XPATH, self.RECIEVED)
        self.click(By.XPATH, self.DELIVERY_TIME)

   def order_10(self):
        self.setup_trado()
        self.fields(By.XPATH, self.PHONE, "1952222222")
        time.sleep(2)
        self.click(By.XPATH, self.PHONE_BUTTON)
        time.sleep(2)
        self.fields(By.XPATH, self.CODE_PHONE, "1234")
        time.sleep(2)
        self.click(By.XPATH, self.CONNECT)
        self.click(By.XPATH, self.ORDER_CLICK)
        self.click(By.XPATH, self.RECIEVED)
        self.click(By.XPATH, self.PAYMENT_TYPE)

   def order_11(self):
        self.setup_trado()
        self.fields(By.XPATH, self.PHONE, "1952222222")
        time.sleep(2)
        self.click(By.XPATH, self.PHONE_BUTTON)
        time.sleep(2)
        self.fields(By.XPATH, self.CODE_PHONE, "1234")
        time.sleep(2)
        self.click(By.XPATH, self.CONNECT)
        self.click(By.XPATH, self.ORDER_CLICK)
        self.click(By.XPATH, self.READY)
        self.click(By.XPATH, self.NUMBER)

   def order_12(self):
        self.setup_trado()
        self.fields(By.XPATH, self.PHONE, "1952222222")
        time.sleep(2)
        self.click(By.XPATH, self.PHONE_BUTTON)
        time.sleep(2)
        self.fields(By.XPATH, self.CODE_PHONE, "1234")
        time.sleep(2)
        self.click(By.XPATH, self.CONNECT)
        self.click(By.XPATH, self.ORDER_CLICK)
        self.click(By.XPATH, self.READY)
        self.click(By.XPATH, self.STATUS)

   def order_13(self):
        self.setup_trado()
        self.fields(By.XPATH, self.PHONE, "1952222222")
        time.sleep(2)
        self.click(By.XPATH, self.PHONE_BUTTON)
        time.sleep(2)
        self.fields(By.XPATH, self.CODE_PHONE, "1234")
        time.sleep(2)
        self.click(By.XPATH, self.CONNECT)
        self.click(By.XPATH, self.ORDER_CLICK)
        self.click(By.XPATH, self.RECIEVED)
        self.click(By.XPATH, self.ISMAIN)

   def order_14(self):
        self.setup_trado()
        self.fields(By.XPATH, self.PHONE, "1952222222")
        time.sleep(2)
        self.click(By.XPATH, self.PHONE_BUTTON)
        time.sleep(2)
        self.fields(By.XPATH, self.CODE_PHONE, "1234")
        time.sleep(2)
        self.click(By.XPATH, self.CONNECT)
        self.click(By.XPATH, self.ORDER_CLICK)
        self.click(By.XPATH, self.READY)
        self.click(By.XPATH, self.ORDER)

   def order_15(self):
        self.setup_trado()
        self.fields(By.XPATH, self.PHONE, "1952222222")
        time.sleep(2)
        self.click(By.XPATH, self.PHONE_BUTTON)
        time.sleep(2)
        self.fields(By.XPATH, self.CODE_PHONE, "1234")
        time.sleep(2)
        self.click(By.XPATH, self.CONNECT)
        self.click(By.XPATH, self.ORDER_CLICK)
        self.click(By.XPATH, self.READY)
        self.click(By.XPATH, self.FIRST_NAME)

   def order_16(self):
        self.setup_trado()
        self.fields(By.XPATH, self.PHONE, "1952222222")
        time.sleep(2)
        self.click(By.XPATH, self.PHONE_BUTTON)
        time.sleep(2)
        self.fields(By.XPATH, self.CODE_PHONE, "1234")
        time.sleep(2)
        self.click(By.XPATH, self.CONNECT)
        self.click(By.XPATH, self.ORDER_CLICK)
        self.click(By.XPATH, self.READY)
        self.click(By.XPATH, self.LAST_NAME)

   def order_17(self):
        self.setup_trado()
        self.fields(By.XPATH, self.PHONE, "1952222222")
        time.sleep(2)
        self.click(By.XPATH, self.PHONE_BUTTON)
        time.sleep(2)
        self.fields(By.XPATH, self.CODE_PHONE, "1234")
        time.sleep(2)
        self.click(By.XPATH, self.CONNECT)
        self.click(By.XPATH, self.ORDER_CLICK)
        self.click(By.XPATH, self.READY)
        self.click(By.XPATH, self.ADDRESS)

   def order_18(self):
        self.setup_trado()
        self.fields(By.XPATH, self.PHONE, "1952222222")
        time.sleep(2)
        self.click(By.XPATH, self.PHONE_BUTTON)
        time.sleep(2)
        self.fields(By.XPATH, self.CODE_PHONE, "1234")
        time.sleep(2)
        self.click(By.XPATH, self.CONNECT)
        self.click(By.XPATH, self.ORDER_CLICK)
        self.click(By.XPATH, self.READY)
        self.click(By.XPATH, self.PHONE_NUMBER)

   def order_19(self):
        self.setup_trado()
        self.fields(By.XPATH, self.PHONE, "1952222222")
        time.sleep(2)
        self.click(By.XPATH, self.PHONE_BUTTON)
        time.sleep(2)
        self.fields(By.XPATH, self.CODE_PHONE, "1234")
        time.sleep(2)
        self.click(By.XPATH, self.CONNECT)
        self.click(By.XPATH, self.ORDER_CLICK)
        self.click(By.XPATH, self.READY)
        self.click(By.XPATH, self.SUM)

   def order_20(self):
        self.setup_trado()
        self.fields(By.XPATH, self.PHONE, "1952222222")
        time.sleep(2)
        self.click(By.XPATH, self.PHONE_BUTTON)
        time.sleep(2)
        self.fields(By.XPATH, self.CODE_PHONE, "1234")
        time.sleep(2)
        self.click(By.XPATH, self.CONNECT)
        self.click(By.XPATH, self.ORDER_CLICK)
        self.click(By.XPATH, self.READY)
        self.click(By.XPATH, self.DELIVERY_TIME)

   def order_21(self):
        self.setup_trado()
        self.fields(By.XPATH, self.PHONE, "1952222222")
        time.sleep(2)
        self.click(By.XPATH, self.PHONE_BUTTON)
        time.sleep(2)
        self.fields(By.XPATH, self.CODE_PHONE, "1234")
        time.sleep(2)
        self.click(By.XPATH, self.CONNECT)
        self.click(By.XPATH, self.ORDER_CLICK)
        self.click(By.XPATH, self.READY)
        self.click(By.XPATH, self.PAYMENT_TYPE)

   def order_22(self):
        self.setup_trado()
        self.fields(By.XPATH, self.PHONE, "1952222222")
        time.sleep(2)
        self.click(By.XPATH, self.PHONE_BUTTON)
        time.sleep(2)
        self.fields(By.XPATH, self.CODE_PHONE, "1234")
        time.sleep(2)
        self.click(By.XPATH, self.CONNECT)
        self.click(By.XPATH, self.ORDER_CLICK)
        self.click(By.XPATH, self.SEND)
        self.click(By.XPATH, self.NUMBER)

   def order_23(self):
        self.setup_trado()
        self.fields(By.XPATH, self.PHONE, "1952222222")
        time.sleep(2)
        self.click(By.XPATH, self.PHONE_BUTTON)
        time.sleep(2)
        self.fields(By.XPATH, self.CODE_PHONE, "1234")
        time.sleep(2)
        self.click(By.XPATH, self.CONNECT)
        self.click(By.XPATH, self.ORDER_CLICK)
        self.click(By.XPATH, self.SEND)
        self.click(By.XPATH, self.STATUS)

   def order_24(self):
        self.setup_trado()
        self.fields(By.XPATH, self.PHONE, "1952222222")
        time.sleep(2)
        self.click(By.XPATH, self.PHONE_BUTTON)
        time.sleep(2)
        self.fields(By.XPATH, self.CODE_PHONE, "1234")
        time.sleep(2)
        self.click(By.XPATH, self.CONNECT)
        self.click(By.XPATH, self.ORDER_CLICK)
        self.click(By.XPATH, self.SEND)
        self.click(By.XPATH, self.ISMAIN)

   def order_25(self):
        self.setup_trado()
        self.fields(By.XPATH, self.PHONE, "1952222222")
        time.sleep(2)
        self.click(By.XPATH, self.PHONE_BUTTON)
        time.sleep(2)
        self.fields(By.XPATH, self.CODE_PHONE, "1234")
        time.sleep(2)
        self.click(By.XPATH, self.CONNECT)
        self.click(By.XPATH, self.ORDER_CLICK)
        self.click(By.XPATH, self.SEND)
        self.click(By.XPATH, self.ORDER)

   def order_26(self):
        self.setup_trado()
        self.fields(By.XPATH, self.PHONE, "1952222222")
        time.sleep(2)
        self.click(By.XPATH, self.PHONE_BUTTON)
        time.sleep(2)
        self.fields(By.XPATH, self.CODE_PHONE, "1234")
        time.sleep(2)
        self.click(By.XPATH, self.CONNECT)
        self.click(By.XPATH, self.ORDER_CLICK)
        self.click(By.XPATH, self.SEND)
        self.click(By.XPATH, self.FIRST_NAME)

   def order_27(self):
        self.setup_trado()
        self.fields(By.XPATH, self.PHONE, "1952222222")
        time.sleep(2)
        self.click(By.XPATH, self.PHONE_BUTTON)
        time.sleep(2)
        self.fields(By.XPATH, self.CODE_PHONE, "1234")
        time.sleep(2)
        self.click(By.XPATH, self.CONNECT)
        self.click(By.XPATH, self.ORDER_CLICK)
        self.click(By.XPATH, self.SEND)
        self.click(By.XPATH, self.LAST_NAME)

   def order_28(self):
        self.setup_trado()
        self.fields(By.XPATH, self.PHONE, "1952222222")
        time.sleep(2)
        self.click(By.XPATH, self.PHONE_BUTTON)
        time.sleep(2)
        self.fields(By.XPATH, self.CODE_PHONE, "1234")
        time.sleep(2)
        self.click(By.XPATH, self.CONNECT)
        self.click(By.XPATH, self.ORDER_CLICK)
        self.click(By.XPATH, self.SEND)
        self.click(By.XPATH, self.ADDRESS)

   def order_29(self):
        self.setup_trado()
        self.fields(By.XPATH, self.PHONE, "1952222222")
        time.sleep(2)
        self.click(By.XPATH, self.PHONE_BUTTON)
        time.sleep(2)
        self.fields(By.XPATH, self.CODE_PHONE, "1234")
        time.sleep(2)
        self.click(By.XPATH, self.CONNECT)
        self.click(By.XPATH, self.ORDER_CLICK)
        self.click(By.XPATH, self.SEND)
        self.click(By.XPATH, self.PHONE_NUMBER)

   def order_30(self):
        self.setup_trado()
        self.fields(By.XPATH, self.PHONE, "1952222222")
        time.sleep(2)
        self.click(By.XPATH, self.PHONE_BUTTON)
        time.sleep(2)
        self.fields(By.XPATH, self.CODE_PHONE, "1234")
        time.sleep(2)
        self.click(By.XPATH, self.CONNECT)
        self.click(By.XPATH, self.ORDER_CLICK)
        self.click(By.XPATH, self.SEND)
        self.click(By.XPATH, self.SUM)

   def order_31(self):
        self.setup_trado()
        self.fields(By.XPATH, self.PHONE, "1952222222")
        time.sleep(2)
        self.click(By.XPATH, self.PHONE_BUTTON)
        time.sleep(2)
        self.fields(By.XPATH, self.CODE_PHONE, "1234")
        time.sleep(2)
        self.click(By.XPATH, self.CONNECT)
        self.click(By.XPATH, self.ORDER_CLICK)
        self.click(By.XPATH, self.SEND)
        self.click(By.XPATH, self.DELIVERY_TIME)

   def order_32(self):
        self.setup_trado()
        self.fields(By.XPATH, self.PHONE, "1952222222")
        time.sleep(2)
        self.click(By.XPATH, self.PHONE_BUTTON)
        time.sleep(2)
        self.fields(By.XPATH, self.CODE_PHONE, "1234")
        time.sleep(2)
        self.click(By.XPATH, self.CONNECT)
        self.click(By.XPATH, self.ORDER_CLICK)
        self.click(By.XPATH, self.SEND)
        self.click(By.XPATH, self.PAYMENT_TYPE)

   def order_33(self):
        self.setup_trado()
        self.fields(By.XPATH, self.PHONE, "1952222222")
        time.sleep(2)
        self.click(By.XPATH, self.PHONE_BUTTON)
        time.sleep(2)
        self.fields(By.XPATH, self.CODE_PHONE, "1234")
        time.sleep(2)
        self.click(By.XPATH, self.CONNECT)
        self.click(By.XPATH, self.ORDER_CLICK)
        self.click(By.XPATH, self.FINISHED)
        self.click(By.XPATH, self.NUMBER)

   def order_34(self):
        self.setup_trado()
        self.fields(By.XPATH, self.PHONE, "1952222222")
        time.sleep(2)
        self.click(By.XPATH, self.PHONE_BUTTON)
        time.sleep(2)
        self.fields(By.XPATH, self.CODE_PHONE, "1234")
        time.sleep(2)
        self.click(By.XPATH, self.CONNECT)
        self.click(By.XPATH, self.ORDER_CLICK)
        self.click(By.XPATH, self.FINISHED)
        self.click(By.XPATH, self.STATUS)

   def order_35(self):
        self.setup_trado()
        self.fields(By.XPATH, self.PHONE, "1952222222")
        time.sleep(2)
        self.click(By.XPATH, self.PHONE_BUTTON)
        time.sleep(2)
        self.fields(By.XPATH, self.CODE_PHONE, "1234")
        time.sleep(2)
        self.click(By.XPATH, self.CONNECT)
        self.click(By.XPATH, self.ORDER_CLICK)
        self.click(By.XPATH, self.FINISHED)
        self.click(By.XPATH, self.ISMAIN)

   def order_36(self):
        self.setup_trado()
        self.fields(By.XPATH, self.PHONE, "1952222222")
        time.sleep(2)
        self.click(By.XPATH, self.PHONE_BUTTON)
        time.sleep(2)
        self.fields(By.XPATH, self.CODE_PHONE, "1234")
        time.sleep(2)
        self.click(By.XPATH, self.CONNECT)
        self.click(By.XPATH, self.ORDER_CLICK)
        self.click(By.XPATH, self.FINISHED)
        self.click(By.XPATH, self.ORDER)

   def order_37(self):
        self.setup_trado()
        self.fields(By.XPATH, self.PHONE, "1952222222")
        time.sleep(2)
        self.click(By.XPATH, self.PHONE_BUTTON)
        time.sleep(2)
        self.fields(By.XPATH, self.CODE_PHONE, "1234")
        time.sleep(2)
        self.click(By.XPATH, self.CONNECT)
        self.click(By.XPATH, self.ORDER_CLICK)
        self.click(By.XPATH, self.FINISHED)
        self.click(By.XPATH, self.FIRST_NAME)

   def order_38(self):
        self.setup_trado()
        self.fields(By.XPATH, self.PHONE, "1952222222")
        time.sleep(2)
        self.click(By.XPATH, self.PHONE_BUTTON)
        time.sleep(2)
        self.fields(By.XPATH, self.CODE_PHONE, "1234")
        time.sleep(2)
        self.click(By.XPATH, self.CONNECT)
        self.click(By.XPATH, self.ORDER_CLICK)
        self.click(By.XPATH, self.FINISHED)
        self.click(By.XPATH, self.LAST_NAME)

   def order_39(self):
        self.setup_trado()
        self.fields(By.XPATH, self.PHONE, "1952222222")
        time.sleep(2)
        self.click(By.XPATH, self.PHONE_BUTTON)
        time.sleep(2)
        self.fields(By.XPATH, self.CODE_PHONE, "1234")
        time.sleep(2)
        self.click(By.XPATH, self.CONNECT)
        self.click(By.XPATH, self.ORDER_CLICK)
        self.click(By.XPATH, self.FINISHED)
        self.click(By.XPATH, self.ADDRESS)

   def order_40(self):
        self.setup_trado()
        self.fields(By.XPATH, self.PHONE, "1952222222")
        time.sleep(2)
        self.click(By.XPATH, self.PHONE_BUTTON)
        time.sleep(2)
        self.fields(By.XPATH, self.CODE_PHONE, "1234")
        time.sleep(2)
        self.click(By.XPATH, self.CONNECT)
        self.click(By.XPATH, self.ORDER_CLICK)
        self.click(By.XPATH, self.FINISHED)
        self.click(By.XPATH, self.PHONE_NUMBER)

   def order_41(self):
        self.setup_trado()
        self.fields(By.XPATH, self.PHONE, "1952222222")
        time.sleep(2)
        self.click(By.XPATH, self.PHONE_BUTTON)
        time.sleep(2)
        self.fields(By.XPATH, self.CODE_PHONE, "1234")
        time.sleep(2)
        self.click(By.XPATH, self.CONNECT)
        self.click(By.XPATH, self.ORDER_CLICK)
        self.click(By.XPATH, self.FINISHED)
        self.click(By.XPATH, self.SUM)

   def order_42(self):
        self.setup_trado()
        self.fields(By.XPATH, self.PHONE, "1952222222")
        time.sleep(2)
        self.click(By.XPATH, self.PHONE_BUTTON)
        time.sleep(2)
        self.fields(By.XPATH, self.CODE_PHONE, "1234")
        time.sleep(2)
        self.click(By.XPATH, self.CONNECT)
        self.click(By.XPATH, self.ORDER_CLICK)
        self.click(By.XPATH, self.FINISHED)
        self.click(By.XPATH, self.DELIVERY_TIME)

   def order_43(self):
        self.setup_trado()
        self.fields(By.XPATH, self.PHONE, "1952222222")
        time.sleep(2)
        self.click(By.XPATH, self.PHONE_BUTTON)
        time.sleep(2)
        self.fields(By.XPATH, self.CODE_PHONE, "1234")
        time.sleep(2)
        self.click(By.XPATH, self.CONNECT)
        self.click(By.XPATH, self.ORDER_CLICK)
        self.click(By.XPATH, self.FINISHED)
        self.click(By.XPATH, self.PAYMENT_TYPE)

   def order_44(self):
        self.setup_trado()
        self.fields(By.XPATH, self.PHONE, "1952222222")
        time.sleep(2)
        self.click(By.XPATH, self.PHONE_BUTTON)
        time.sleep(2)
        self.fields(By.XPATH, self.CODE_PHONE, "1234")
        time.sleep(2)
        self.click(By.XPATH, self.CONNECT)
        self.click(By.XPATH, self.ORDER_CLICK)
        self.click(By.XPATH, self.RECIEVED)
        self.click(By.XPATH, self.DOT_CLICK)
        self.click(By.XPATH, self.DOWNLOAD)

   def order_45(self):
        self.setup_trado()
        self.fields(By.XPATH, self.PHONE, "1952222222")
        time.sleep(2)
        self.click(By.XPATH, self.PHONE_BUTTON)
        time.sleep(2)
        self.fields(By.XPATH, self.CODE_PHONE, "1234")
        time.sleep(2)
        self.click(By.XPATH, self.CONNECT)
        self.click(By.XPATH, self.ORDER_CLICK)
        self.click(By.XPATH, self.READY)
        self.click(By.XPATH, self.DOT_CLICK)
        self.click(By.XPATH, self.DOWNLOAD)

   def order_46(self):
        self.setup_trado()
        self.fields(By.XPATH, self.PHONE, "1952222222")
        time.sleep(2)
        self.click(By.XPATH, self.PHONE_BUTTON)
        time.sleep(2)
        self.fields(By.XPATH, self.CODE_PHONE, "1234")
        time.sleep(2)
        self.click(By.XPATH, self.CONNECT)
        self.click(By.XPATH, self.ORDER_CLICK)
        self.click(By.XPATH, self.FINISHED)
        self.click(By.XPATH, self.DOT_CLICK)
        self.click(By.XPATH, self.DOWNLOAD)

   def order_47(self):
        self.setup_trado()
        self.fields(By.XPATH, self.PHONE, "1952222222")
        time.sleep(2)
        self.click(By.XPATH, self.PHONE_BUTTON)
        time.sleep(2)
        self.fields(By.XPATH, self.CODE_PHONE, "1234")
        time.sleep(2)
        self.click(By.XPATH, self.CONNECT)
        self.click(By.XPATH, self.ORDER_CLICK)
        self.click(By.XPATH, self.SEND)
        self.click(By.XPATH, self.DOT_CLICK)
        self.click(By.XPATH, self.DOWNLOAD)

   def order_48(self):
        self.setup_trado()
        self.fields(By.XPATH, self.PHONE, "1952222222")
        time.sleep(2)
        self.click(By.XPATH, self.PHONE_BUTTON)
        time.sleep(2)
        self.fields(By.XPATH, self.CODE_PHONE, "1234")
        time.sleep(2)
        self.click(By.XPATH, self.CONNECT)
        self.click(By.XPATH, self.ORDER_CLICK)
        self.click(By.XPATH, self.RECIEVED)
        self.click(By.XPATH, self.FIRST_NAME)
        self.fields(By.XPATH, self.SEARCH, "sdfg")

   def order_49(self):
        self.setup_trado()
        self.fields(By.XPATH, self.PHONE, "1952222222")
        time.sleep(2)
        self.click(By.XPATH, self.PHONE_BUTTON)
        time.sleep(2)
        self.fields(By.XPATH, self.CODE_PHONE, "1234")
        time.sleep(2)
        self.click(By.XPATH, self.CONNECT)
        self.click(By.XPATH, self.ORDER_CLICK)
        self.click(By.XPATH, self.RECIEVED)
        self.click(By.XPATH, self.LAST_NAME)
        self.fields(By.XPATH, self.SEARCH, "asdfgh")


   def order_50(self):
        self.setup_trado()
        self.fields(By.XPATH, self.PHONE, "1952222222")
        time.sleep(2)
        self.click(By.XPATH, self.PHONE_BUTTON)
        time.sleep(2)
        self.fields(By.XPATH, self.CODE_PHONE, "1234")
        time.sleep(2)
        self.click(By.XPATH, self.CONNECT)
        self.click(By.XPATH, self.ORDER_CLICK)
        self.click(By.XPATH, self.RECIEVED)
        self.click(By.XPATH, self.PHONE_NUMBER)
        self.fields(By.XPATH, self.SEARCH, "0502006336")


   def order_51(self):
        self.setup_trado()
        self.fields(By.XPATH, self.PHONE, "1952222222")
        time.sleep(2)
        self.click(By.XPATH, self.PHONE_BUTTON)
        time.sleep(2)
        self.fields(By.XPATH, self.CODE_PHONE, "1234")
        time.sleep(2)
        self.click(By.XPATH, self.CONNECT)
        self.click(By.XPATH, self.ORDER_CLICK)
        self.click(By.XPATH, self.RECIEVED)
        self.click(By.XPATH, self.PAYMENT_TYPE)
        self.fields(By.XPATH, self.SEARCH,  "finTrado")


   def order_52(self):
        self.setup_trado()
        self.fields(By.XPATH, self.PHONE, "1952222222")
        time.sleep(2)
        self.click(By.XPATH, self.PHONE_BUTTON)
        time.sleep(2)
        self.fields(By.XPATH, self.CODE_PHONE, "1234")
        time.sleep(2)
        self.click(By.XPATH, self.CONNECT)
        self.click(By.XPATH, self.ORDER_CLICK)
        self.click(By.XPATH, self.READY)
        self.click(By.XPATH, self.FIRST_NAME)
        self.fields(By.XPATH, self.SEARCH, "dddddsa")

   def order_53(self):
        self.setup_trado()
        self.fields(By.XPATH, self.PHONE, "1952222222")
        time.sleep(2)
        self.click(By.XPATH, self.PHONE_BUTTON)
        time.sleep(2)
        self.fields(By.XPATH, self.CODE_PHONE, "1234")
        time.sleep(2)
        self.click(By.XPATH, self.CONNECT)
        self.click(By.XPATH, self.ORDER_CLICK)
        self.click(By.XPATH, self.READY)
        self.click(By.XPATH, self.LAST_NAME)
        self.fields(By.XPATH, self.SEARCH, "dde")


   def order_54(self):
        self.setup_trado()
        self.fields(By.XPATH, self.PHONE, "1952222222")
        time.sleep(2)
        self.click(By.XPATH, self.PHONE_BUTTON)
        time.sleep(2)
        self.fields(By.XPATH, self.CODE_PHONE, "1234")
        time.sleep(2)
        self.click(By.XPATH, self.CONNECT)
        self.click(By.XPATH, self.ORDER_CLICK)
        self.click(By.XPATH, self.READY)
        self.click(By.XPATH, self.PHONE_NUMBER)
        self.fields(By.XPATH, self.SEARCH, "0535220876")


   def order_55(self):
        self.setup_trado()
        self.fields(By.XPATH, self.PHONE, "1952222222")
        time.sleep(2)
        self.click(By.XPATH, self.PHONE_BUTTON)
        time.sleep(2)
        self.fields(By.XPATH, self.CODE_PHONE, "1234")
        time.sleep(2)
        self.click(By.XPATH, self.CONNECT)
        self.click(By.XPATH, self.ORDER_CLICK)
        self.click(By.XPATH, self.READY)
        self.click(By.XPATH, self.PAYMENT_TYPE)
        self.fields(By.XPATH, self.SEARCH,  "etrado")


   def order_56(self):
        self.setup_trado()
        self.fields(By.XPATH, self.PHONE, "1952222222")
        time.sleep(2)
        self.click(By.XPATH, self.PHONE_BUTTON)
        time.sleep(2)
        self.fields(By.XPATH, self.CODE_PHONE, "1234")
        time.sleep(2)
        self.click(By.XPATH, self.CONNECT)
        self.click(By.XPATH, self.ORDER_CLICK)
        self.click(By.XPATH, self.SEND)
        self.click(By.XPATH, self.FIRST_NAME)
        self.fields(By.XPATH, self.SEARCH, "dddddsa")

   def order_57(self):
        self.setup_trado()
        self.fields(By.XPATH, self.PHONE, "1952222222")
        time.sleep(2)
        self.click(By.XPATH, self.PHONE_BUTTON)
        time.sleep(2)
        self.fields(By.XPATH, self.CODE_PHONE, "1234")
        time.sleep(2)
        self.click(By.XPATH, self.CONNECT)
        self.click(By.XPATH, self.ORDER_CLICK)
        self.click(By.XPATH, self.SEND)
        self.click(By.XPATH, self.LAST_NAME)
        self.fields(By.XPATH, self.SEARCH, "dde")


   def order_58(self):
        self.setup_trado()
        self.fields(By.XPATH, self.PHONE, "1952222222")
        time.sleep(2)
        self.click(By.XPATH, self.PHONE_BUTTON)
        time.sleep(2)
        self.fields(By.XPATH, self.CODE_PHONE, "1234")
        time.sleep(2)
        self.click(By.XPATH, self.CONNECT)
        self.click(By.XPATH, self.ORDER_CLICK)
        self.click(By.XPATH, self.SEND)
        self.click(By.XPATH, self.PHONE_NUMBER)
        self.fields(By.XPATH, self.SEARCH, "0535220876")


   def order_59(self):
        self.setup_trado()
        self.fields(By.XPATH, self.PHONE, "1952222222")
        time.sleep(2)
        self.click(By.XPATH, self.PHONE_BUTTON)
        time.sleep(2)
        self.fields(By.XPATH, self.CODE_PHONE, "1234")
        time.sleep(2)
        self.click(By.XPATH, self.CONNECT)
        self.click(By.XPATH, self.ORDER_CLICK)
        self.click(By.XPATH, self.SEND)
        self.click(By.XPATH, self.PAYMENT_TYPE)
        self.fields(By.XPATH, self.SEARCH,  "etrado")


   def order_60(self):
        self.setup_trado()
        self.fields(By.XPATH, self.PHONE, "1952222222")
        time.sleep(2)
        self.click(By.XPATH, self.PHONE_BUTTON)
        time.sleep(2)
        self.fields(By.XPATH, self.CODE_PHONE, "1234")
        time.sleep(2)
        self.click(By.XPATH, self.CONNECT)
        self.click(By.XPATH, self.ORDER_CLICK)
        self.click(By.XPATH, self.FINISHED)
        self.click(By.XPATH, self.FIRST_NAME)
        self.fields(By.XPATH, self.SEARCH, "dddddsa")

   def order_61(self):
        self.setup_trado()
        self.fields(By.XPATH, self.PHONE, "1952222222")
        time.sleep(2)
        self.click(By.XPATH, self.PHONE_BUTTON)
        time.sleep(2)
        self.fields(By.XPATH, self.CODE_PHONE, "1234")
        time.sleep(2)
        self.click(By.XPATH, self.CONNECT)
        self.click(By.XPATH, self.ORDER_CLICK)
        self.click(By.XPATH, self.FINISHED)
        self.click(By.XPATH, self.LAST_NAME)
        self.fields(By.XPATH, self.SEARCH, "dde")


   def order_62(self):
        self.setup_trado()
        self.fields(By.XPATH, self.PHONE, "1952222222")
        time.sleep(2)
        self.click(By.XPATH, self.PHONE_BUTTON)
        time.sleep(2)
        self.fields(By.XPATH, self.CODE_PHONE, "1234")
        time.sleep(2)
        self.click(By.XPATH, self.CONNECT)
        self.click(By.XPATH, self.ORDER_CLICK)
        self.click(By.XPATH, self.FINISHED)
        self.click(By.XPATH, self.PHONE_NUMBER)
        self.fields(By.XPATH, self.SEARCH, "0535220876")


   def order_63(self):
        self.setup_trado()
        self.fields(By.XPATH, self.PHONE, "1952222222")
        time.sleep(2)
        self.click(By.XPATH, self.PHONE_BUTTON)
        time.sleep(2)
        self.fields(By.XPATH, self.CODE_PHONE, "1234")
        time.sleep(2)
        self.click(By.XPATH, self.CONNECT)
        self.click(By.XPATH, self.ORDER_CLICK)
        self.click(By.XPATH, self.FINISHED)
        self.click(By.XPATH, self.PAYMENT_TYPE)
        self.fields(By.XPATH, self.SEARCH,  "etrado")








