class Product_Locator:
    TRADO_ADMIN = "https://qa-admin.trado.co.il/#/login"
    PHONE = "//body/div[@id='root']/div[1]/div[2]/div[1]/span[1]/form[1]/div[1]/div[1]/span[1]/div[1]/input[1]"
    PHONE_BUTTON = "//body/div[@id='root']/div[1]/div[2]/div[1]/span[1]/form[1]/input[1]"
    CODE = "//body/div[@id='root']/div[1]/div[2]/div[1]/span[1]/form[1]/div[1]/div[1]/span[1]/div[1]/input[1]"
    SAVE_BUTTON = "//body/div[@id='root']/div[1]/div[2]/div[1]/span[1]/form[1]/div[1]/div[2]/span[1]/span[1]"
    CONNECT = "//body/div[@id='root']/div[1]/div[2]/div[1]/span[1]/form[1]/input[1]"
    PRODUCT = "//span[contains(text(),'מוצרים')]"

    INVALID_PHONE = "//div[contains(text(),'no such user')]"
    EMPTY_PHONE = "/html[1]/body[1]/div[1]/div[1]/div[2]/div[1]/span[1]/form[1]/div[1]/div[1]/div[1]"
    CHARACTER_PHONE = "//body/div[@id='root']/div[1]/div[2]/div[1]/span[1]/form[1]/div[1]/div[1]/div[1]"
    LOGIN_FAILED = "//body/div[@id='root']/div[1]/div[2]/div[1]/span[1]/form[1]/div[2]"

    SEARCH_BUTTON = "//body/div[@id='root']/div[1]/div[2]/main[1]/div[2]/div[1]/div[1]/span[1]/span[1]/div[1]/input[1]"
    CODEBARE_DOWN_UP = "//thead/tr[1]/th[1]/span[1]/i[1]"
    PHOTO_UP_DOWN = "//thead/tr[1]/th[2]/span[1]/i[1]"

    ROW1 = "//tbody/tr[1]/td[2]"

    NAME_UP_DOWN = "//thead/tr[1]/th[3]/span[1]/i[1]"
    PRICE_UP_DOWN = "//thead/tr[1]/th[4]/span[1]/i[1]"
    PROMOTION_UP_DOWN = "//thead/tr[1]/th[5]/span[1]/i[1]"
    CATAGORY_UP_DOWN= "//thead/tr[1]/th[6]/span[1]/i[1]"
    DEPARTMENT_UP_DOWN = "//thead/tr[1]/th[7]/span[1]/i[1]"
    TYPES_CO_UP_DOWN = "//thead/tr[1]/th[8]/span[1]/i[1]"
    PRODUCTTAG_UP_DOWN = "//thead/tr[1]/th[9]/span[1]/i[1]"
    SHOP_UP_DOWN = "//thead/tr[1]/th[10]/span[1]/i[1]"
    ORDER_ADDRESS_UO_DOWN = "//thead/tr[1]/th[12]/span[1]/i[1]"
    ADD_INFO_UP_DOWN = "//thead/tr[1]/th[13]/span[1]/i[1]"
    PRODUCTION_DATE_UP_DOWN = "//thead/tr[1]/th[17]/span[1]/i[1]"
    DESCRIPTION = "//thead/tr[1]/th[18]/span[1]/i[1]"

    FORWARD = "//body/div[@id='root']/div[1]/div[2]/main[1]/div[2]/div[1]/div[2]/div[2]/div[2]/span[5]/i[1]"
    BACKWARD = "//body/div[@id='root']/div[1]/div[2]/main[1]/div[2]/div[1]/div[2]/div[2]/div[2]/span[1]/i[1]"
    LEFT = "//body/div[@id='root']/div[1]/div[2]/main[1]/div[2]/div[1]/div[2]/div[2]/div[2]/span[4]/i[1]"
    RIGHT = "//body/div[@id='root']/div[1]/div[2]/main[1]/div[2]/div[1]/div[2]/div[2]/div[2]/span[2]/i[1]"

    LEFT_CORNER = "//body/div[@id='root']/div[1]/div[2]/main[1]/div[2]/div[1]/div[1]/div[1]"

    PLUS = "//span[contains(text(),'הוספה')]"
    PLUS_SYMBOL = "//body/div[@id='root']/div[1]/div[2]/main[1]/div[2]/div[1]/div[1]/div[2]/div[1]/div[1]/span[1]/i[1]"
    SEARCH_PLUS = "//body/div[@id='root']/div[1]/div[4]/div[1]/div[1]/span[1]/form[1]/div[2]/div[1]/div[1]/span[1]/span[1]/div[1]/input[1]"
    BARCODE_PLUS = "//body/div[@id='root']/div[1]/div[4]/div[1]/div[1]/span[1]/form[1]/div[2]/div[2]/span[1]/div[1]/input[1]"
    PHOTO_PLUS = "//body/div[@id='root']/div[1]/div[4]/div[1]/div[1]/span[1]/form[1]/div[2]/div[3]/div[1]/input[1]"
    PRICE_PLUS = "//body/div[@id='root']/div[1]/div[4]/div[1]/div[1]/span[1]/form[1]/div[2]/div[5]/span[1]/div[1]/input[1]"
    NAME_PLUS = "//body/div[@id='root']/div[1]/div[4]/div[1]/div[1]/span[1]/form[1]/div[2]/div[4]/span[1]/div[1]/input[1]"
    PROMOTION_PLUS = "//body/div[@id='root']/div[1]/div[4]/div[1]/div[1]/span[1]/form[1]/div[2]/div[8]/span[1]/div[1]/input[1]"
    NEXT_PLUS = "//body/div[@id='root']/div[1]/div[4]/div[1]/div[1]/span[1]/form[1]/div[4]/input[1]"

    DOWNLOAD = "//span[contains(text(),'ייצוא')]"
    DOWNLOAD_SYMBOL = "//body/div[@id='root']/div[1]/div[2]/main[1]/div[2]/div[1]/div[1]/div[2]/div[1]/div[2]/span[1]/i[1]"

    ADD_TO_BRAND = "//span[contains(text(),'add by brand')]"
    ADD_TO_BRAND_SYMBOL = "//body/div[@id='root']/div[1]/div[2]/main[1]/div[2]/div[1]/div[1]/div[2]/div[1]/div[3]/span[1]/i[1]"
    ADD_TO_BRAND_SEARCH = "//body/div[@id='root']/div[1]/div[4]/div[1]/div[1]/span[1]/form[1]/div[2]/div[1]/div[1]/span[1]/span[1]/div[1]/input[1]"
    ADD_TO_BRAND_SHOP = "//body/div[@id='root']/div[1]/div[4]/div[1]/div[1]/span[1]/form[1]/div[2]/div[2]/div[1]/span[1]/div[1]/input[1]"
    ADD_TO_BRAND_SELECT = "//div[contains(text(),'user :3p7isiaple346o8q')]"

    COME = "//span[contains(text(),'ייבוא')]"
    COME_SYMBOL = "//body/div[@id='root']/div[1]/div[2]/main[1]/div[2]/div[1]/div[1]/div[2]/div[1]/div[4]/span[1]/i[1]"
    COME_IMPORT = "/html[1]/body[1]/div[1]/div[1]/div[4]/div[1]/div[1]/div[1]/form[1]/div[1]/div[1]/div[1]/input[1]"
    COME_SEND = "//body/div[@id='root']/div[1]/div[4]/div[1]/div[1]/div[1]/form[1]/input[1]"

    PATTERN = "//span[contains(text(),'תבנית')]"
    PATTERN_SYMBOL = "//body/div[@id='root']/div[1]/div[2]/main[1]/div[2]/div[1]/div[1]/div[2]/div[1]/div[5]/span[1]/i[1]"

    BARCODE_MOD = "//body/div[@id='root']/div[1]/div[4]/div[1]/div[1]/span[1]/form[1]/div[2]/div[1]/span[1]/div[1]/input[1]"
    NAME_MOD = "//body/div[@id='root']/div[1]/div[4]/div[1]/div[1]/span[1]/form[1]/div[2]/div[3]/span[1]/div[1]/input[1]"
    EXPIRE_DATE_MOD = "//body/div[@id='root']/div[1]/div[4]/div[1]/div[1]/span[1]/form[1]/div[2]/div[6]/span[1]/div[1]/input[1]"
    PHOTO_MOD = "//body/div[@id='root']/div[1]/div[4]/div[1]/div[1]/span[1]/form[1]/div[2]/div[2]/div[1]/input[1]"
    PRICE_MOD = "//body/div[@id='root']/div[1]/div[4]/div[1]/div[1]/span[1]/form[1]/div[2]/div[4]/span[1]/div[1]/input[1]"
    DESCRIPTION_MOD = "//body/div[@id='root']/div[1]/div[4]/div[1]/div[1]/span[1]/form[1]/div[2]/div[7]/span[1]/div[1]/input[1]"
    NEXT_BUTTON = "//body/div[@id='root']/div[1]/div[4]/div[1]/div[1]/span[1]/form[1]/div[4]/input[1]"

    PROMOTION_MOD = "//body/div[@id='root']/div[1]/div[4]/div[1]/div[1]/span[1]/form[1]/div[2]/div[1]/div[1]/span[1]/div[1]/input[1]"
    DEPARTMEN_MOD = "//body/div[@id='root']/div[1]/div[4]/div[1]/div[1]/span[1]/form[1]/div[2]/div[3]/div[1]/span[1]/div[1]/input[1]"
    DAGKADGA_MOD = "//body/div[@id='root']/div[1]/div[4]/div[1]/div[1]/span[1]/form[1]/div[2]/div[5]/div[1]/span[1]/div[1]/input[1]"
    CATAGORY_MOD = "//body/div[@id='root']/div[1]/div[4]/div[1]/div[1]/span[1]/form[1]/div[2]/div[2]/div[1]/span[1]/div[1]/input[1]"
    PRODUCTTAG_MOD = "/html[1]/body[1]/div[1]/div[1]/div[4]/div[1]/div[1]/span[1]/form[1]/div[2]/div[4]/div[1]/span[1]/div[1]/input[1]"
    PARALLEL_IMPO_MOD = "//body/div[@id='root']/div[1]/div[4]/div[1]/div[1]/span[1]/form[1]/div[2]/div[7]/span[1]/span[1]"
    NEXT2_MOD = "div.modal_modalWrapper.modal_open div.modal_modal div.modal_content span.products_productForm form.form_form div:nth-child(4) > input.form_submitBtn:nth-child(2)"

    CARTO_AMOUNT_MOD = "//body/div[@id='root']/div[1]/div[4]/div[1]/div[1]/span[1]/form[1]/div[2]/div[3]/div[1]/div[1]/span[1]/div[1]/input[1]"
    AMOUNT_MOD = "//body/div[@id='root']/div[1]/div[4]/div[1]/div[1]/span[1]/form[1]/div[2]/div[3]/div[1]/div[2]/span[1]/div[1]/input[1]"
    MINIMUM_CATAGORY_MOD = "//body/div[@id='root']/div[1]/div[4]/div[1]/div[1]/span[1]/form[1]/div[2]/div[3]/div[1]/div[2]/span[1]/div[1]/input[1]"
    NEXT3_MOD = "//body/div[@id='root']/div[1]/div[4]/div[1]/div[1]/span[1]/form[1]/div[4]/input[2]"

    CITY_MOD = "//body/div[@id='root']/div[1]/div[4]/div[1]/div[1]/span[1]/form[1]/div[2]/div[2]/div[1]/div[1]/span[1]/div[1]/input[1]"
    NUMBER_MOD = "//body/div[@id='root']/div[1]/div[4]/div[1]/div[1]/span[1]/form[1]/div[2]/div[2]/div[1]/div[3]/span[1]/div[1]/input[1]"
    STREET_MOD = "//body/div[@id='root']/div[1]/div[4]/div[1]/div[1]/span[1]/form[1]/div[2]/div[2]/div[1]/div[2]/span[1]/div[1]/input[1]"
    CONTACTNUMBER_MOD = "//body/div[@id='root']/div[1]/div[4]/div[1]/div[1]/span[1]/form[1]/div[2]/div[3]/div[1]/div[1]/span[1]/div[1]/input[1]"
    NEXT4_MOD = "//body/div[@id='root']/div[1]/div[4]/div[1]/div[1]/span[1]/form[1]/div[4]/input[2]"

    NEXT5_MOD = "//body/div[@id='root']/div[1]/div[4]/div[1]/div[1]/span[1]/form[1]/div[4]/input[2]"
    BACK_MOD = "//body/div[@id='root']/div[1]/div[4]/div[1]/div[1]/span[1]/form[1]/div[4]/input[1]"