from time import sleep
from Web.TradoAdmin.Product.locators import Product_Locator
from Web.TradoAdmin.base.base import BaseSetups
from selenium.webdriver.common.by import By
class TestAll_Product(BaseSetups, Product_Locator):
    def Valid_phone(self):
        self.setup_trado()
        self.fields(By.XPATH, self.PHONE, "1952222222")
        self.click(By.XPATH, self.PHONE_BUTTON)
    def Invalid_phone(self):
        self.setup_trado()
        sleep(1)
        self.fields(By.XPATH, self.PHONE, "1234562345")
        sleep(1)
        self.click(By.XPATH, self.PHONE_BUTTON)
        sleep(1)
        assert self.assertion(By.XPATH, self.INVALID_PHONE) == "no such user"


    def Empty_phone(self):
        self.setup_trado()
        self.fields(By.XPATH, self.PHONE, "")
        self.click(By.XPATH, self.PHONE_BUTTON)
        assert self.assertion(By.XPATH, self.EMPTY_PHONE) == "נא למלא שדה זהxxx"
    def Character_phone(self):
        self.setup_trado()
        self.driver.find_element(By.XPATH, self.PHONE).clear()
        self.fields(By.XPATH, self.PHONE, "belay")
        self.click(By.XPATH, self.PHONE_BUTTON)
        assert self.assertion(By.XPATH, self.INVALID_PHONE) == "no such user"
    def Valid_phone_code(self):
        self.setup_trado()
        self.fields(By.XPATH, self.PHONE, "1952222222")
        sleep(1)
        self.click(By.XPATH, self.PHONE_BUTTON)
        sleep(1)
        self.fields(By.XPATH, self.CODE, "1234")
        sleep(1)
        self.click(By.XPATH, self.CONNECT)
    def Valid_phone_code_save(self):
        self.setup_trado()
        self.fields(By.XPATH, self.PHONE, "1952222222")
        sleep(1)
        self.click(By.XPATH, self.PHONE_BUTTON)
        sleep(1)
        self.fields(By.XPATH, self.CODE, "1234")
        sleep(1)
        self.click(By.XPATH, self.SAVE_BUTTON)
        sleep(1)
        self.click(By.XPATH, self.CONNECT)
    def Valid_phone_invalid_code(self):
        self.setup_trado()
        self.driver.find_element(By.XPATH, self.PHONE).clear()
        self.fields(By.XPATH, self.PHONE, "1952222222")
        sleep(1)
        self.click(By.XPATH, self.PHONE_BUTTON)
        sleep(1)
        self.fields(By.XPATH, self.CODE, "1224")
        sleep(1)
        self.click(By.XPATH, self.SAVE_BUTTON)
        sleep(1)
        self.click(By.XPATH, self.CONNECT)
    def Valid_phone_empty_code(self):
        self.setup_trado()
        self.fields(By.XPATH, self.PHONE, "1952222222")
        sleep(1)
        self.click(By.XPATH, self.PHONE_BUTTON)
        sleep(1)
        self.driver.find_element(By.XPATH, self.PHONE).clear()
        self.fields(By.XPATH, self.CODE, "")
        sleep(1)
        self.click(By.XPATH, self.SAVE_BUTTON)
        sleep(1)
        self.click(By.XPATH, self.CONNECT)
        assert self.assertion(By.XPATH, self.LOGIN_FAILED) == "faild to login"
    def Valid_phone_character_code(self):
        self.setup_trado()
        self.fields(By.XPATH, self.PHONE, "1952222222")
        sleep(1)
        self.click(By.XPATH, self.PHONE_BUTTON)
        sleep(1)
        self.driver.find_element(By.XPATH, self.PHONE).clear()
        self.fields(By.XPATH, self.CODE, "belay ")
        sleep(1)
        self.click(By.XPATH, self.SAVE_BUTTON)
        sleep(1)
        self.click(By.XPATH, self.CONNECT)
        assert self.assertion(By.XPATH, self.LOGIN_FAILED) =="faild to login"

    def Product(self):
        self.setup_trado()
        self.fields(By.XPATH, self.PHONE, "1952222222")
        sleep(1)
        self.click(By.XPATH, self.PHONE_BUTTON)
        sleep(1)
        self.fields(By.XPATH, self.CODE, "1234")
        sleep(1)
        self.click(By.XPATH, self.SAVE_BUTTON)
        sleep(1)
        self.click(By.XPATH, self.CONNECT)
        sleep(1)
        self.click(By.XPATH, self.PRODUCT)
    def Product_Search_Button(self):
        self.setup_trado()
        self.fields(By.XPATH, self.PHONE, "1952222222")
        sleep(1)
        self.click(By.XPATH, self.PHONE_BUTTON)
        sleep(1)
        self.fields(By.XPATH, self.CODE, "1234")
        sleep(1)
        self.click(By.XPATH, self.SAVE_BUTTON)
        sleep(1)
        self.click(By.XPATH, self.CONNECT)
        sleep(1)
        self.click(By.XPATH, self.PRODUCT)
        sleep(1)
        self.click(By.XPATH, self.SEARCH_BUTTON)
    def Number_Input_Search(self):
        self.setup_trado()
        self.fields(By.XPATH, self.PHONE, "1952222222")
        sleep(1)
        self.click(By.XPATH, self.PHONE_BUTTON)
        sleep(1)
        self.fields(By.XPATH, self.CODE, "1234")
        sleep(1)
        self.click(By.XPATH, self.SAVE_BUTTON)
        sleep(1)
        self.click(By.XPATH, self.CONNECT)
        sleep(1)
        self.click(By.XPATH, self.PRODUCT)
        sleep(1)
        self.fields(By.XPATH, self.SEARCH_BUTTON, "222")
    def Charactor_Input_Search(self):
        self.setup_trado()
        self.fields(By.XPATH, self.PHONE, "1952222222")
        sleep(1)
        self.click(By.XPATH, self.PHONE_BUTTON)
        sleep(1)
        self.fields(By.XPATH, self.CODE, "1234")
        sleep(1)
        self.click(By.XPATH, self.SAVE_BUTTON)
        sleep(1)
        self.click(By.XPATH, self.CONNECT)
        sleep(1)
        self.click(By.XPATH, self.PRODUCT)
        sleep(1)
        self.fields(By.XPATH, self.SEARCH_BUTTON, "ברקוד")
    def Number_Chara_Search(self):
        self.setup_trado()
        self.fields(By.XPATH, self.PHONE, "1952222222")
        sleep(1)
        self.click(By.XPATH, self.PHONE_BUTTON)
        sleep(1)
        self.fields(By.XPATH, self.CODE, "1234")
        sleep(1)
        self.click(By.XPATH, self.SAVE_BUTTON)
        sleep(1)
        self.click(By.XPATH, self.CONNECT)
        sleep(1)
        self.click(By.XPATH, self.PRODUCT)
        sleep(1)
        self.fields(By.XPATH, self.SEARCH_BUTTON, "ברק12")
    def Name_Input_Search_button(self):
        self.setup_trado()
        self.fields(By.XPATH, self.PHONE, "1952222222")
        sleep(1)
        self.click(By.XPATH, self.PHONE_BUTTON)
        sleep(1)
        self.fields(By.XPATH, self.CODE, "1234")
        sleep(1)
        self.click(By.XPATH, self.SAVE_BUTTON)
        sleep(1)
        self.click(By.XPATH, self.CONNECT)
        sleep(1)
        self.click(By.XPATH, self.PRODUCT)
        sleep(1)
        self.fields(By.XPATH, self.SEARCH_BUTTON, "ברק12")
    def One_Element(self):
        self.setup_trado()
        self.fields(By.XPATH, self.PHONE, "1952222222")
        sleep(1)
        self.click(By.XPATH, self.PHONE_BUTTON)
        sleep(1)
        self.fields(By.XPATH, self.CODE, "1234")
        sleep(1)
        self.click(By.XPATH, self.SAVE_BUTTON)
        sleep(1)
        self.click(By.XPATH, self.CONNECT)
        sleep(1)
        self.click(By.XPATH, self.PRODUCT)
        sleep(1)
        self.click(By.XPATH, self.ROW1)
    def To_forward(self):
        self.setup_trado()
        self.fields(By.XPATH, self.PHONE, "1952222222")
        sleep(1)
        self.click(By.XPATH, self.PHONE_BUTTON)
        sleep(1)
        self.fields(By.XPATH, self.CODE, "1234")
        sleep(1)
        self.click(By.XPATH, self.SAVE_BUTTON)
        sleep(1)
        self.click(By.XPATH, self.CONNECT)
        sleep(1)
        self.click(By.XPATH, self.PRODUCT)
        self.click(By.XPATH, self.FORWARD)
    def To_Backward(self):
        self.setup_trado()
        self.fields(By.XPATH, self.PHONE, "1952222222")
        sleep(1)
        self.click(By.XPATH, self.PHONE_BUTTON)
        sleep(1)
        self.fields(By.XPATH, self.CODE, "1234")
        sleep(1)
        self.click(By.XPATH, self.SAVE_BUTTON)
        sleep(1)
        self.click(By.XPATH, self.CONNECT)
        self.click(By.XPATH, self.PRODUCT)
        self.click(By.XPATH, self.BACKWARD)
    def T0_Left_Side(self):
        self.setup_trado()
        self.fields(By.XPATH, self.PHONE, "1952222222")
        sleep(1)
        self.click(By.XPATH, self.PHONE_BUTTON)
        sleep(1)
        self.fields(By.XPATH, self.CODE, "1234")
        sleep(1)
        self.click(By.XPATH, self.SAVE_BUTTON)
        sleep(1)
        self.click(By.XPATH, self.CONNECT)
        self.click(By.XPATH, self.PRODUCT)
        self.click(By.XPATH, self.LEFT)
    def To_Right_Side(self):
        self.setup_trado()
        self.fields(By.XPATH, self.PHONE, "1952222222")
        sleep(1)
        self.click(By.XPATH, self.PHONE_BUTTON)
        sleep(1)
        self.fields(By.XPATH, self.CODE, "1234")
        sleep(1)
        self.click(By.XPATH, self.SAVE_BUTTON)
        sleep(1)
        self.click(By.XPATH, self.CONNECT)
        self.click(By.XPATH, self.PRODUCT)
        self.click(By.XPATH, self.RIGHT)
    def Left_corner(self):
        self.setup_trado()
        self.fields(By.XPATH, self.PHONE, "1952222222")
        sleep(1)
        self.click(By.XPATH, self.PHONE_BUTTON)
        sleep(1)
        self.fields(By.XPATH, self.CODE, "1234")
        sleep(1)
        self.click(By.XPATH, self.SAVE_BUTTON)
        sleep(1)
        self.click(By.XPATH, self.CONNECT)
        sleep(1)
        self.click(By.XPATH, self.PRODUCT)
        self.click(By.XPATH, self.LEFT_CORNER)
    def Plus(self):
        self.setup_trado()
        self.fields(By.XPATH, self.PHONE, "1952222222")
        sleep(1)
        self.click(By.XPATH, self.PHONE_BUTTON)
        sleep(1)
        self.fields(By.XPATH, self.CODE, "1234")
        sleep(1)
        self.click(By.XPATH, self.SAVE_BUTTON)
        sleep(1)
        self.click(By.XPATH, self.CONNECT)
        sleep(1)
        self.click(By.XPATH, self.PRODUCT)
        self.click(By.XPATH, self.LEFT_CORNER)
        self.click(By.XPATH, self.PLUS)
    def Plus_symbol(self):
        self.setup_trado()
        self.fields(By.XPATH, self.PHONE, "1952222222")
        sleep(1)
        self.click(By.XPATH, self.PHONE_BUTTON)
        sleep(1)
        self.fields(By.XPATH, self.CODE, "1234")
        sleep(1)
        self.click(By.XPATH, self.SAVE_BUTTON)
        sleep(1)
        self.click(By.XPATH, self.CONNECT)
        sleep(1)
        self.click(By.XPATH, self.PRODUCT)
        self.click(By.XPATH, self.LEFT_CORNER)
        self.click(By.XPATH, self.PLUS_SYMBOL)
    def Download(self):
        self.setup_trado()
        self.fields(By.XPATH, self.PHONE, "1952222222")
        sleep(1)
        self.click(By.XPATH, self.PHONE_BUTTON)
        sleep(1)
        self.fields(By.XPATH, self.CODE, "1234")
        sleep(1)
        self.click(By.XPATH, self.SAVE_BUTTON)
        sleep(1)
        self.click(By.XPATH, self.CONNECT)
        sleep(1)
        self.click(By.XPATH, self.PRODUCT)
        self.click(By.XPATH, self.LEFT_CORNER)
        self.click(By.XPATH, self.DOWNLOAD)
    def Download_Smbol(self):
        self.setup_trado()
        self.fields(By.XPATH, self.PHONE, "1952222222")
        sleep(1)
        self.click(By.XPATH, self.PHONE_BUTTON)
        sleep(1)
        self.fields(By.XPATH, self.CODE, "1234")
        sleep(1)
        self.click(By.XPATH, self.SAVE_BUTTON)
        sleep(1)
        self.click(By.XPATH, self.CONNECT)
        sleep(1)
        self.click(By.XPATH, self.PRODUCT)
        self.click(By.XPATH, self.LEFT_CORNER)
        self.click(By.XPATH, self.DOWNLOAD_SYMBOL)
    def Add_To_Brand(self):
        self.setup_trado()
        self.fields(By.XPATH, self.PHONE, "1952222222")
        sleep(1)
        self.click(By.XPATH, self.PHONE_BUTTON)
        sleep(1)
        self.fields(By.XPATH, self.CODE, "1234")
        sleep(1)
        self.click(By.XPATH, self.SAVE_BUTTON)
        sleep(1)
        self.click(By.XPATH, self.CONNECT)
        sleep(1)
        self.click(By.XPATH, self.PRODUCT)
        self.click(By.XPATH, self.LEFT_CORNER)
        self.click(By.XPATH, self.ADD_TO_BRAND)
    def Add_To_Brand_symbol(self):
        self.setup_trado()
        self.fields(By.XPATH, self.PHONE, "1952222222")
        sleep(1)
        self.click(By.XPATH, self.PHONE_BUTTON)
        sleep(1)
        self.fields(By.XPATH, self.CODE, "1234")
        sleep(1)
        self.click(By.XPATH, self.SAVE_BUTTON)
        sleep(1)
        self.click(By.XPATH, self.CONNECT)
        sleep(1)
        self.click(By.XPATH, self.PRODUCT)
        self.click(By.XPATH, self.LEFT_CORNER)
        self.click(By.XPATH, self.ADD_TO_BRAND_SYMBOL)
    def Come(self):
        self.setup_trado()
        self.fields(By.XPATH, self.PHONE, "1952222222")
        sleep(1)
        self.click(By.XPATH, self.PHONE_BUTTON)
        sleep(1)
        self.fields(By.XPATH, self.CODE, "1234")
        sleep(1)
        self.click(By.XPATH, self.SAVE_BUTTON)
        sleep(1)
        self.click(By.XPATH, self.CONNECT)
        sleep(1)
        self.click(By.XPATH, self.PRODUCT)
        self.click(By.XPATH, self.LEFT_CORNER)
        self.click(By.XPATH, self.COME)
    def Come_symbol(self):
        self.setup_trado()
        self.fields(By.XPATH, self.PHONE, "1952222222")
        sleep(1)
        self.click(By.XPATH, self.PHONE_BUTTON)
        sleep(1)
        self.fields(By.XPATH, self.CODE, "1234")
        sleep(1)
        self.click(By.XPATH, self.SAVE_BUTTON)
        sleep(1)
        self.click(By.XPATH, self.CONNECT)
        sleep(1)
        self.click(By.XPATH, self.PRODUCT)
        self.click(By.XPATH, self.LEFT_CORNER)
        self.click(By.XPATH, self.COME_SYMBOL)
    def Pattern(self):
        self.setup_trado()
        self.fields(By.XPATH, self.PHONE, "1952222222")
        sleep(1)
        self.click(By.XPATH, self.PHONE_BUTTON)
        sleep(1)
        self.fields(By.XPATH, self.CODE, "1234")
        sleep(1)
        self.click(By.XPATH, self.SAVE_BUTTON)
        sleep(1)
        self.click(By.XPATH, self.CONNECT)
        sleep(1)
        self.click(By.XPATH, self.PRODUCT)
        self.click(By.XPATH, self.LEFT_CORNER)
        self.click(By.XPATH, self.PATTERN)
    def Pattern_Symbol(self):
        self.setup_trado()
        self.fields(By.XPATH, self.PHONE, "1952222222")
        sleep(1)
        self.click(By.XPATH, self.PHONE_BUTTON)
        sleep(1)
        self.fields(By.XPATH, self.CODE, "1234")
        sleep(1)
        self.click(By.XPATH, self.SAVE_BUTTON)
        sleep(1)
        self.click(By.XPATH, self.CONNECT)
        sleep(1)
        self.click(By.XPATH, self.PRODUCT)
        self.click(By.XPATH, self.LEFT_CORNER)
        self.click(By.XPATH, self.PATTERN_SYMBOL)
    def Plus_Full(self):
        self.setup_trado()
        self.fields(By.XPATH, self.PHONE, "1952222222")
        sleep(1)
        self.click(By.XPATH, self.PHONE_BUTTON)
        sleep(1)
        self.fields(By.XPATH, self.CODE, "1234")
        sleep(1)
        self.click(By.XPATH, self.SAVE_BUTTON)
        sleep(1)
        self.click(By.XPATH, self.CONNECT)
        sleep(1)
        self.click(By.XPATH, self.PRODUCT)
        sleep(1)
        self.click(By.XPATH, self.LEFT_CORNER)
        self.click(By.XPATH, self.PLUS)
        self.fields(By.XPATH, self.SEARCH_PLUS, "ewbw3")
        self.fields(By.XPATH, self.BARCODE_PLUS, "feghe")
        # self.fields(By.XPATH, self.PHOTO_PLUS, "t3783u")
        # sleep(2)
        self.fields(By.XPATH, self.PRICE_PLUS, "rtwtbhh")
        self.fields(By.XPATH, self.NAME_PLUS, "3576873hj")
        self.fields(By.XPATH, self.PROMOTION_PLUS, "vdshk3")
        self.fields(By.XPATH, self.NEXT_PLUS, "y3898u3lk")
    def Add_To_Brand_Full(self):
        self.setup_trado()
        self.fields(By.XPATH, self.PHONE, "1952222222")
        sleep(1)
        self.click(By.XPATH, self.PHONE_BUTTON)
        sleep(1)
        self.fields(By.XPATH, self.CODE, "1234")
        sleep(1)
        self.click(By.XPATH, self.SAVE_BUTTON)
        sleep(1)
        self.click(By.XPATH, self.CONNECT)
        sleep(1)
        self.click(By.XPATH, self.PRODUCT)
        self.click(By.XPATH, self.LEFT_CORNER)
        self.click(By.XPATH, self.ADD_TO_BRAND)
        self.fields(By.XPATH, self.ADD_TO_BRAND_SEARCH, "rtw873eu")
        self.fields(By.XPATH, self.ADD_TO_BRAND_SHOP, "FDGEM")
        self.click(By.XPATH, self.ADD_TO_BRAND_SELECT)
    def Come_Import(self):
        self.setup_trado()
        self.fields(By.XPATH, self.PHONE, "1952222222")
        sleep(1)
        self.click(By.XPATH, self.PHONE_BUTTON)
        sleep(1)
        self.fields(By.XPATH, self.CODE, "1234")
        sleep(1)
        self.click(By.XPATH, self.SAVE_BUTTON)
        sleep(1)
        self.click(By.XPATH, self.CONNECT)
        sleep(1)
        self.click(By.XPATH, self.PRODUCT)
        self.click(By.XPATH, self.LEFT_CORNER)
        self.click(By.XPATH, self.COME)
        self.click(By.XPATH, self.COME_IMPORT)
    def SwitchAlert2(self):
        return self.driver.switch_to.alert.cancel()
    def Come_Send(self):
        self.setup_trado()
        self.fields(By.XPATH, self.PHONE, "1952222222")
        sleep(1)
        self.click(By.XPATH, self.PHONE_BUTTON)
        sleep(1)
        self.fields(By.XPATH, self.CODE, "1234")
        sleep(1)
        self.click(By.XPATH, self.SAVE_BUTTON)
        sleep(1)
        self.click(By.XPATH, self.CONNECT)
        sleep(1)
        self.click(By.XPATH, self.PRODUCT)
        self.click(By.XPATH, self.LEFT_CORNER)
        self.click(By.XPATH, self.COME)
        self.click(By.XPATH, self.COME_SEND)
    def Come_Full(self):
        self.setup_trado()
        self.fields(By.XPATH, self.PHONE, "1952222222")
        sleep(1)
        self.click(By.XPATH, self.PHONE_BUTTON)
        sleep(1)
        self.fields(By.XPATH, self.CODE, "1234")
        sleep(1)
        self.click(By.XPATH, self.SAVE_BUTTON)
        sleep(1)
        self.click(By.XPATH, self.CONNECT)
        sleep(1)
        self.click(By.XPATH, self.PRODUCT)
        self.click(By.XPATH, self.LEFT_CORNER)
        self.click(By.XPATH, self.COME)
        self.click(By.XPATH, self.COME_IMPORT)
        self.click(By.XPATH, self.COME_SEND)
    def Modify(self):
        self.setup_trado()
        self.fields(By.XPATH, self.PHONE, "1952222222")
        sleep(1)
        self.click(By.XPATH, self.PHONE_BUTTON)
        sleep(1)
        self.fields(By.XPATH, self.CODE, "1234")
        sleep(1)
        self.click(By.XPATH, self.SAVE_BUTTON)
        sleep(1)
        self.click(By.XPATH, self.CONNECT)
        sleep(1)
        self.click(By.XPATH, self.PRODUCT)
        self.click(By.XPATH, self.ROW1)
    def modify_barcode(self):
        self.setup_trado()
        self.fields(By.XPATH, self.PHONE, "1952222222")
        sleep(1)
        self.click(By.XPATH, self.PHONE_BUTTON)
        sleep(1)
        self.fields(By.XPATH, self.CODE, "1234")
        sleep(1)
        self.click(By.XPATH, self.SAVE_BUTTON)
        sleep(1)
        self.click(By.XPATH, self.CONNECT)
        self.click(By.XPATH, self.PRODUCT)
        self.click(By.XPATH, self.ROW1)
        self.fields(By.XPATH, self.BARCODE_MOD, "deeyu")
    def modify_name(self):
        self.setup_trado()
        self.fields(By.XPATH, self.PHONE, "1952222222")
        sleep(1)
        self.click(By.XPATH, self.PHONE_BUTTON)
        sleep(1)
        self.fields(By.XPATH, self.CODE, "1234")
        sleep(1)
        self.click(By.XPATH, self.SAVE_BUTTON)
        sleep(1)
        self.click(By.XPATH, self.CONNECT)
        self.click(By.XPATH, self.PRODUCT)
        self.click(By.XPATH, self.ROW1)
        self.fields(By.XPATH, self.NAME_MOD, "take")
    def modify_expiredate(self):
        self.setup_trado()
        self.fields(By.XPATH, self.PHONE, "1952222222")
        sleep(1)
        self.click(By.XPATH, self.PHONE_BUTTON)
        sleep(1)
        self.fields(By.XPATH, self.CODE, "1234")
        sleep(1)
        self.click(By.XPATH, self.SAVE_BUTTON)
        sleep(1)
        self.click(By.XPATH, self.CONNECT)
        self.click(By.XPATH, self.PRODUCT)
        self.click(By.XPATH, self.ROW1)
        self.fields(By.XPATH, self.EXPIRE_DATE_MOD, "123")
    def modify_photo(self):
        self.setup_trado()
        self.fields(By.XPATH, self.PHONE, "1952222222")
        sleep(1)
        self.click(By.XPATH, self.PHONE_BUTTON)
        sleep(1)
        self.fields(By.XPATH, self.CODE, "1234")
        sleep(1)
        self.click(By.XPATH, self.SAVE_BUTTON)
        sleep()
        self.click(By.XPATH, self.CONNECT)
        sleep(1)
        self.click(By.XPATH, self.PRODUCT)
        self.click(By.XPATH, self.ROW1)
        self.click(By.XPATH, self.PHOTO_MOD)
    def modify_price(self):
        self.setup_trado()
        self.fields(By.XPATH, self.PHONE, "1952222222")
        sleep(1)
        self.click(By.XPATH, self.PHONE_BUTTON)
        sleep(1)
        self.fields(By.XPATH, self.CODE, "1234")
        sleep(1)
        self.click(By.XPATH, self.SAVE_BUTTON)
        sleep(1)
        self.click(By.XPATH, self.CONNECT)
        sleep(1)
        self.click(By.XPATH, self.PRODUCT)
        self.click(By.XPATH, self.ROW1)
        self.fields(By.XPATH, self.PRICE_MOD, "234")
    def modify_description(self):
        self.setup_trado()
        self.fields(By.XPATH, self.PHONE, "1952222222")
        sleep(1)
        self.click(By.XPATH, self.PHONE_BUTTON)
        sleep(1)
        self.fields(By.XPATH, self.CODE, "1234")
        sleep(1)
        self.click(By.XPATH, self.SAVE_BUTTON)
        sleep(1)
        self.click(By.XPATH, self.CONNECT)
        sleep(1)
        self.click(By.XPATH, self.PRODUCT)
        self.click(By.XPATH, self.ROW1)
        self.fields(By.XPATH, self.DESCRIPTION_MOD, "duhdk")
    def part_one(self):
        self.setup_trado()
        self.fields(By.XPATH, self.PHONE, "1952222222")
        sleep(2)
        self.click(By.XPATH, self.PHONE_BUTTON)
        sleep(2)
        self.fields(By.XPATH, self.CODE, "1234")
        sleep(2)
        self.click(By.XPATH, self.SAVE_BUTTON)
        sleep(2)
        self.click(By.XPATH, self.CONNECT)
        sleep(2)
        self.click(By.XPATH, self.PRODUCT)
        sleep(2)
        self.click(By.XPATH, self.ROW1)
        self.fields(By.XPATH, self.BARCODE_MOD, "deeyu")
        self.fields(By.XPATH, self.NAME_MOD, "take")
        self.fields(By.XPATH, self.EXPIRE_DATE_MOD, "123")
        self.fields(By.XPATH, self.PRICE_MOD, "234")
        self.fields(By.XPATH, self.DESCRIPTION_MOD, "duhdk")
    def next_button(self):
        self.setup_trado()
        self.fields(By.XPATH, self.PHONE, "1952222222")
        sleep(1)
        self.click(By.XPATH, self.PHONE_BUTTON)
        sleep(1)
        self.fields(By.XPATH, self.CODE, "1234")
        sleep(1)
        self.click(By.XPATH, self.SAVE_BUTTON)
        sleep(1)
        self.click(By.XPATH, self.CONNECT)
        sleep(1)
        self.click(By.XPATH, self.PRODUCT)
        self.click(By.XPATH, self.ROW1)
        self.fields(By.XPATH, self.BARCODE_MOD, "deeyu")
        self.fields(By.XPATH, self.NAME_MOD, "take")
        self.fields(By.XPATH, self.EXPIRE_DATE_MOD, "123")
        self.fields(By.XPATH, self.PRICE_MOD, "234")
        self.fields(By.XPATH, self.DESCRIPTION_MOD, "duhdk")
        self.click(By.XPATH, self.NEXT_BUTTON)
    def modify_promoption(self):
        self.setup_trado()
        self.fields(By.XPATH, self.PHONE, "1952222222")
        sleep(1)
        self.click(By.XPATH, self.PHONE_BUTTON)
        sleep(1)
        self.fields(By.XPATH, self.CODE, "1234")
        sleep(1)
        self.click(By.XPATH, self.SAVE_BUTTON)
        sleep(2)
        self.click(By.XPATH, self.CONNECT)
        sleep(1)
        self.click(By.XPATH, self.PRODUCT)
        self.click(By.XPATH, self.ROW1)
        self.fields(By.XPATH, self.BARCODE_MOD, "deeyu")
        self.fields(By.XPATH, self.NAME_MOD, "take")
        self.fields(By.XPATH, self.EXPIRE_DATE_MOD, "123")
        self.fields(By.XPATH, self.PRICE_MOD, "234")
        self.fields(By.XPATH, self.DESCRIPTION_MOD, "duhdk")
        self.click(By.XPATH, self.NEXT_BUTTON)
        self.fields(By.XPATH, self.PROMOTION_MOD, "uhuouj23")
    def modify_department(self):
        self.setup_trado()
        self.fields(By.XPATH, self.PHONE, "1952222222")
        sleep(1)
        self.click(By.XPATH, self.PHONE_BUTTON)
        sleep(1)
        self.fields(By.XPATH, self.CODE, "1234")
        sleep(1)
        self.click(By.XPATH, self.SAVE_BUTTON)
        sleep(1)
        self.click(By.XPATH, self.CONNECT)
        sleep(1)
        self.click(By.XPATH, self.PRODUCT)
        self.click(By.XPATH, self.ROW1)
        self.fields(By.XPATH, self.BARCODE_MOD, "deeyu")
        self.fields(By.XPATH, self.NAME_MOD, "take")
        self.fields(By.XPATH, self.EXPIRE_DATE_MOD, "123")
        self.fields(By.XPATH, self.PRICE_MOD, "234")
        self.fields(By.XPATH, self.DESCRIPTION_MOD, "duhdk")
        self.click(By.XPATH, self.NEXT_BUTTON)
        self.fields(By.XPATH, self.PROMOTION_MOD, "uhuouj23")
        self.fields(By.XPATH, self.DEPARTMEN_MOD, "rtwtuw")
    def modify_dakgard(self):
        self.setup_trado()
        self.fields(By.XPATH, self.PHONE, "1952222222")
        sleep(1)
        self.click(By.XPATH, self.PHONE_BUTTON)
        sleep(1)
        self.fields(By.XPATH, self.CODE, "1234")
        sleep(1)
        self.click(By.XPATH, self.SAVE_BUTTON)
        sleep(1)
        self.click(By.XPATH, self.CONNECT)
        self.click(By.XPATH, self.PRODUCT)
        self.click(By.XPATH, self.ROW1)
        self.fields(By.XPATH, self.BARCODE_MOD, "deeyu")
        self.fields(By.XPATH, self.NAME_MOD, "take")
        self.fields(By.XPATH, self.EXPIRE_DATE_MOD, "123")
        self.fields(By.XPATH, self.PRICE_MOD, "234")
        self.fields(By.XPATH, self.DESCRIPTION_MOD, "duhdk")
        self.click(By.XPATH, self.NEXT_BUTTON)
        self.fields(By.XPATH, self.PROMOTION_MOD, "uhuouj23")
        self.fields(By.XPATH, self.DEPARTMEN_MOD, "rtwtuw")
        self.fields(By.XPATH, self.DAGKADGA_MOD, "wshns")

    def modify_catagory(self):
        self.setup_trado()
        self.fields(By.XPATH, self.PHONE, "1952222222")
        sleep(1)
        self.click(By.XPATH, self.PHONE_BUTTON)
        sleep(1)
        self.fields(By.XPATH, self.CODE, "1234")
        sleep(1)
        self.click(By.XPATH, self.SAVE_BUTTON)
        sleep(1)
        self.click(By.XPATH, self.CONNECT)
        self.click(By.XPATH, self.PRODUCT)
        self.click(By.XPATH, self.ROW1)
        self.fields(By.XPATH, self.BARCODE_MOD, "deeyu")
        self.fields(By.XPATH, self.NAME_MOD, "take")
        self.fields(By.XPATH, self.EXPIRE_DATE_MOD, "123")
        self.fields(By.XPATH, self.PRICE_MOD, "234")
        self.fields(By.XPATH, self.DESCRIPTION_MOD, "duhdk")
        self.click(By.XPATH, self.NEXT_BUTTON)
        self.fields(By.XPATH, self.PROMOTION_MOD, "uhuouj23")
        self.fields(By.XPATH, self.DEPARTMEN_MOD, "rtwtuw")
        self.fields(By.XPATH, self.DAGKADGA_MOD, "wshns")
        self.fields(By.XPATH, self.CATAGORY_MOD, "ye3djnnd")
    def modify_productTag(self):
        self.setup_trado()
        self.fields(By.XPATH, self.PHONE, "1952222222")
        sleep(1)
        self.click(By.XPATH, self.PHONE_BUTTON)
        sleep(1)
        self.fields(By.XPATH, self.CODE, "1234")
        sleep(1)
        self.click(By.XPATH, self.SAVE_BUTTON)
        sleep(1)
        self.click(By.XPATH, self.CONNECT)
        sleep(1)
        self.click(By.XPATH, self.PRODUCT)
        sleep(1)
        self.click(By.XPATH, self.ROW1)
        self.fields(By.XPATH, self.BARCODE_MOD, "deeyu")
        self.fields(By.XPATH, self.NAME_MOD, "take")
        self.fields(By.XPATH, self.EXPIRE_DATE_MOD, "123")
        self.fields(By.XPATH, self.PRICE_MOD, "234")
        self.fields(By.XPATH, self.DESCRIPTION_MOD, "duhdk")
        self.click(By.XPATH, self.NEXT_BUTTON)
        self.fields(By.XPATH, self.PROMOTION_MOD, "uhuouj23")
        self.fields(By.XPATH, self.DEPARTMEN_MOD, "rtwtuw")
        self.fields(By.XPATH, self.DAGKADGA_MOD, "wshns")
        self.fields(By.XPATH, self.CATAGORY_MOD, "ye3djnnd")
        self.fields(By.XPATH, self.PRODUCTTAG_MOD, "ytuhede")
        assert self.assertion(By.XPATH, self.NAME_ASSERTION) == "נא eeלא שדה זהxxx"
    def modify_parallel(self):
        self.setup_trado()
        self.fields(By.XPATH, self.PHONE, "1952222222")
        sleep(1)
        self.click(By.XPATH, self.PHONE_BUTTON)
        sleep(1)
        self.fields(By.XPATH, self.CODE, "1234")
        sleep(1)
        self.click(By.XPATH, self.SAVE_BUTTON)
        sleep(1)
        self.click(By.XPATH, self.CONNECT)
        sleep(1)
        self.click(By.XPATH, self.PRODUCT)
        self.click(By.XPATH, self.ROW1)
        self.fields(By.XPATH, self.BARCODE_MOD, "deeyu")
        self.fields(By.XPATH, self.NAME_MOD, "take")
        self.fields(By.XPATH, self.EXPIRE_DATE_MOD, "123")
        self.fields(By.XPATH, self.PRICE_MOD, "234")
        self.fields(By.XPATH, self.DESCRIPTION_MOD, "duhdk")
        self.click(By.XPATH, self.NEXT_BUTTON)
        self.fields(By.XPATH, self.PROMOTION_MOD, "uhuouj23")
        self.fields(By.XPATH, self.DEPARTMEN_MOD, "rtwtuw")
        self.fields(By.XPATH, self.DAGKADGA_MOD, "wshns")
        self.fields(By.XPATH, self.CATAGORY_MOD, "ye3djnnd")
        self.fields(By.XPATH, self.PRODUCTTAG_MOD, "ytuhede")
        assert self.assertion(By.XPATH, self.NAME_ASSERTION) == "נא eeלא שדה זהxxx"
    def next2_button(self):
        self.setup_trado()
        self.fields(By.XPATH, self.PHONE, "1952222222")
        sleep(1)
        self.click(By.XPATH, self.PHONE_BUTTON)
        sleep(1)
        self.fields(By.XPATH, self.CODE, "1234")
        sleep(1)
        self.click(By.XPATH, self.SAVE_BUTTON)
        sleep(1)
        self.click(By.XPATH, self.CONNECT)
        sleep(1)
        self.click(By.XPATH, self.PRODUCT)
        self.click(By.XPATH, self.ROW1)
        self.fields(By.XPATH, self.BARCODE_MOD, "deeyu")
        self.fields(By.XPATH, self.NAME_MOD, "take")
        self.fields(By.XPATH, self.EXPIRE_DATE_MOD, "123")
        self.fields(By.XPATH, self.PRICE_MOD, "234")
        self.fields(By.XPATH, self.DESCRIPTION_MOD, "duhdk")
        self.click(By.XPATH, self.NEXT_BUTTON)
        self.fields(By.XPATH, self.PROMOTION_MOD, "uhuouj23")
        self.fields(By.XPATH, self.DEPARTMEN_MOD, "rtwtuw")
        self.fields(By.XPATH, self.DAGKADGA_MOD, "wshns")
        self.fields(By.XPATH, self.CATAGORY_MOD, "ye3djnnd")
        self.fields(By.XPATH, self.PRODUCTTAG_MOD, "ytuhede")
        self.click(By.XPATH, self.NEXT2_MOD)
    def modify_carton_amount(self):
        self.setup_trado()
        self.fields(By.XPATH, self.PHONE, "1952222222")
        sleep(1)
        self.click(By.XPATH, self.PHONE_BUTTON)
        sleep(1)
        self.fields(By.XPATH, self.CODE, "1234")
        sleep(1)
        self.click(By.XPATH, self.SAVE_BUTTON)
        sleep(1)
        self.click(By.XPATH, self.CONNECT)
        self.click(By.XPATH, self.PRODUCT)
        self.click(By.XPATH, self.ROW1)
        self.fields(By.XPATH, self.BARCODE_MOD, "deeyu")
        self.fields(By.XPATH, self.NAME_MOD, "take")
        self.fields(By.XPATH, self.EXPIRE_DATE_MOD, "123")
        self.fields(By.XPATH, self.PRICE_MOD, "234")
        self.fields(By.XPATH, self.DESCRIPTION_MOD, "duhdk")
        self.click(By.XPATH, self.NEXT_BUTTON)
        self.fields(By.XPATH, self.PROMOTION_MOD, "uhuouj23")
        self.fields(By.XPATH, self.DEPARTMEN_MOD, "rtwtuw")
        self.fields(By.XPATH, self.DAGKADGA_MOD, "wshns")
        self.fields(By.XPATH, self.CATAGORY_MOD, "ye3djnnd")
        self.fields(By.XPATH, self.PRODUCTTAG_MOD, "ytuhede")
        # self.click(By.XPATH, self.NEXT2_MOD)
        # self.fields(By.XPATH, self.CARTO_AMOUNT_MOD, "12")
    def modify_amoun(self):
        self.setup_trado()
        self.fields(By.XPATH, self.PHONE, "1952222222")
        sleep(1)
        self.click(By.XPATH, self.PHONE_BUTTON)
        sleep(1)
        self.fields(By.XPATH, self.CODE, "1234")
        sleep(1)
        self.click(By.XPATH, self.SAVE_BUTTON)
        sleep(1)
        self.click(By.XPATH, self.CONNECT)
        sleep(1)
        self.click(By.XPATH, self.PRODUCT)
        self.click(By.XPATH, self.ROW1)
        self.fields(By.XPATH, self.BARCODE_MOD, "deeyu")
        self.fields(By.XPATH, self.NAME_MOD, "take")
        self.fields(By.XPATH, self.EXPIRE_DATE_MOD, "123")
        self.fields(By.XPATH, self.PRICE_MOD, "234")
        self.fields(By.XPATH, self.DESCRIPTION_MOD, "duhdk")
        self.click(By.XPATH, self.NEXT_BUTTON)
        self.fields(By.XPATH, self.PROMOTION_MOD, "uhuouj23")
        self.fields(By.XPATH, self.DEPARTMEN_MOD, "rtwtuw")
        self.fields(By.XPATH, self.DAGKADGA_MOD, "wshns")
        self.fields(By.XPATH, self.CATAGORY_MOD, "ye3djnnd")
        self.fields(By.XPATH, self.PRODUCTTAG_MOD, "ytuhede")
        self.click(By.XPATH, self.NEXT2_MOD)
        self.fields(By.XPATH, self.CARTO_AMOUNT_MOD, "12")
        self.fields(By.XPATH, self.AMOUNT_MOD, "gysynj")
    def modify_minimium_carton(self):
        self.setup_trado()
        self.fields(By.XPATH, self.PHONE, "1952222222")
        sleep(1)
        self.click(By.XPATH, self.PHONE_BUTTON)
        sleep(1)
        self.fields(By.XPATH, self.CODE, "1234")
        sleep(1)
        self.click(By.XPATH, self.SAVE_BUTTON)
        sleep(1)
        self.click(By.XPATH, self.CONNECT)
        self.click(By.XPATH, self.PRODUCT)
        self.click(By.XPATH, self.ROW1)
        self.fields(By.XPATH, self.BARCODE_MOD, "deeyu")
        self.fields(By.XPATH, self.NAME_MOD, "take")
        self.fields(By.XPATH, self.EXPIRE_DATE_MOD, "123")
        self.fields(By.XPATH, self.PRICE_MOD, "234")
        self.fields(By.XPATH, self.DESCRIPTION_MOD, "duhdk")
        self.click(By.XPATH, self.NEXT_BUTTON)
        self.fields(By.XPATH, self.PROMOTION_MOD, "uhuouj23")
        self.fields(By.XPATH, self.DEPARTMEN_MOD, "rtwtuw")
        self.fields(By.XPATH, self.DAGKADGA_MOD, "wshns")
        self.fields(By.XPATH, self.CATAGORY_MOD, "ye3djnnd")
        self.fields(By.XPATH, self.PRODUCTTAG_MOD, "ytuhede")
        self.click(By.XPATH, self.NEXT2_MOD)
        self.fields(By.XPATH, self.CARTO_AMOUNT_MOD, "12")
        self.fields(By.XPATH, self.AMOUNT_MOD, "gysynj")
        self.fields(By.XPATH, self.MINIMUM_CATAGORY_MOD, "23")
    def next3_button(self):
        self.setup_trado()
        self.fields(By.XPATH, self.PHONE, "1952222222")
        sleep(1)
        self.click(By.XPATH, self.PHONE_BUTTON)
        sleep(1)
        self.fields(By.XPATH, self.CODE, "1234")
        sleep(1)
        self.click(By.XPATH, self.SAVE_BUTTON)
        sleep(1)
        self.click(By.XPATH, self.CONNECT)
        self.click(By.XPATH, self.PRODUCT)
        self.click(By.XPATH, self.ROW1)
        self.fields(By.XPATH, self.BARCODE_MOD, "deeyu")
        self.fields(By.XPATH, self.NAME_MOD, "take")
        self.fields(By.XPATH, self.EXPIRE_DATE_MOD, "123")
        self.fields(By.XPATH, self.PRICE_MOD, "234")
        self.fields(By.XPATH, self.DESCRIPTION_MOD, "duhdk")
        self.click(By.XPATH, self.NEXT_BUTTON)
        self.fields(By.XPATH, self.PROMOTION_MOD, "uhuouj23")
        self.fields(By.XPATH, self.DEPARTMEN_MOD, "rtwtuw")
        self.fields(By.XPATH, self.DAGKADGA_MOD, "wshns")
        self.fields(By.XPATH, self.CATAGORY_MOD, "ye3djnnd")
        self.fields(By.XPATH, self.PRODUCTTAG_MOD, "ytuhede")
        self.click(By.XPATH, self.NEXT2_MOD)
        self.fields(By.XPATH, self.CARTO_AMOUNT_MOD, "12")
        self.fields(By.XPATH, self.AMOUNT_MOD, "gysynj")
        self.fields(By.XPATH, self.MINIMUM_CATAGORY_MOD, "23")
        self.click(By.XPATH, self.NEXT3_MOD)
    def modify_city(self):
        self.setup_trado()
        self.fields(By.XPATH, self.PHONE, "1952222222")
        sleep(1)
        self.click(By.XPATH, self.PHONE_BUTTON)
        sleep(1)
        self.fields(By.XPATH, self.CODE, "1234")
        sleep(1)
        self.click(By.XPATH, self.SAVE_BUTTON)
        sleep(1)
        self.click(By.XPATH, self.CONNECT)
        self.click(By.XPATH, self.PRODUCT)
        self.click(By.XPATH, self.ROW1)
        self.fields(By.XPATH, self.BARCODE_MOD, "deeyu")
        self.fields(By.XPATH, self.NAME_MOD, "take")
        self.fields(By.XPATH, self.EXPIRE_DATE_MOD, "123")
        self.fields(By.XPATH, self.PRICE_MOD, "234")
        self.fields(By.XPATH, self.DESCRIPTION_MOD, "duhdk")
        self.click(By.XPATH, self.NEXT_BUTTON)
        self.fields(By.XPATH, self.PROMOTION_MOD, "uhuouj23")
        self.fields(By.XPATH, self.DEPARTMEN_MOD, "rtwtuw")
        self.fields(By.XPATH, self.DAGKADGA_MOD, "wshns")
        self.fields(By.XPATH, self.CATAGORY_MOD, "ye3djnnd")
        self.fields(By.XPATH, self.PRODUCTTAG_MOD, "ytuhede")
        self.click(By.XPATH, self.NEXT2_MOD)
        self.fields(By.XPATH, self.CARTO_AMOUNT_MOD, "12")
        self.fields(By.XPATH, self.AMOUNT_MOD, "gysynj")
        self.fields(By.XPATH, self.MINIMUM_CATAGORY_MOD, "23")
        self.click(By.XPATH, self.NEXT3_MOD)
        self.fields(By.XPATH, self.CITY_MOD, "rteh")
    def modify_number(self):
        self.setup_trado()
        self.fields(By.XPATH, self.PHONE, "1952222222")
        sleep(1)
        self.click(By.XPATH, self.PHONE_BUTTON)
        sleep(1)
        self.fields(By.XPATH, self.CODE, "1234")
        sleep(1)
        self.click(By.XPATH, self.SAVE_BUTTON)
        sleep(1)
        self.click(By.XPATH, self.CONNECT)
        sleep(1)
        self.click(By.XPATH, self.PRODUCT)
        self.click(By.XPATH, self.ROW1)
        self.fields(By.XPATH, self.BARCODE_MOD, "deeyu")
        self.fields(By.XPATH, self.NAME_MOD, "take")
        self.fields(By.XPATH, self.EXPIRE_DATE_MOD, "123")
        self.fields(By.XPATH, self.PRICE_MOD, "234")
        self.fields(By.XPATH, self.DESCRIPTION_MOD, "duhdk")
        self.click(By.XPATH, self.NEXT_BUTTON)
        self.fields(By.XPATH, self.PROMOTION_MOD, "uhuouj23")
        self.fields(By.XPATH, self.DEPARTMEN_MOD, "rtwtuw")
        self.fields(By.XPATH, self.DAGKADGA_MOD, "wshns")
        self.fields(By.XPATH, self.CATAGORY_MOD, "ye3djnnd")
        self.fields(By.XPATH, self.PRODUCTTAG_MOD, "ytuhede")
        self.click(By.XPATH, self.NEXT2_MOD)
        self.fields(By.XPATH, self.CARTO_AMOUNT_MOD, "12")
        self.fields(By.XPATH, self.AMOUNT_MOD, "gysynj")
        self.fields(By.XPATH, self.MINIMUM_CATAGORY_MOD, "23")
        self.click(By.XPATH, self.NEXT3_MOD)
        self.fields(By.XPATH, self.CITY_MOD, "rteh")
        self.fields(By.XPATH, self.NUMBER_MOD, "23")
    def modify_street(self):
        self.setup_trado()
        self.fields(By.XPATH, self.PHONE, "1952222222")
        sleep(1)
        self.click(By.XPATH, self.PHONE_BUTTON)
        sleep(1)
        self.fields(By.XPATH, self.CODE, "1234")
        sleep(1)
        self.click(By.XPATH, self.SAVE_BUTTON)
        sleep(1)
        self.click(By.XPATH, self.CONNECT)
        sleep(1)
        self.click(By.XPATH, self.PRODUCT)
        self.click(By.XPATH, self.ROW1)
        self.fields(By.XPATH, self.BARCODE_MOD, "deeyu")
        self.fields(By.XPATH, self.NAME_MOD, "take")
        self.fields(By.XPATH, self.EXPIRE_DATE_MOD, "123")
        self.fields(By.XPATH, self.PRICE_MOD, "234")
        self.fields(By.XPATH, self.DESCRIPTION_MOD, "duhdk")
        self.click(By.XPATH, self.NEXT_BUTTON)
        self.fields(By.XPATH, self.PROMOTION_MOD, "uhuouj23")
        self.fields(By.XPATH, self.DEPARTMEN_MOD, "rtwtuw")
        self.fields(By.XPATH, self.DAGKADGA_MOD, "wshns")
        self.fields(By.XPATH, self.CATAGORY_MOD, "ye3djnnd")
        self.fields(By.XPATH, self.PRODUCTTAG_MOD, "ytuhede")
        self.click(By.XPATH, self.NEXT2_MOD)
        self.fields(By.XPATH, self.CARTO_AMOUNT_MOD, "12")
        self.fields(By.XPATH, self.AMOUNT_MOD, "gysynj")
        self.fields(By.XPATH, self.MINIMUM_CATAGORY_MOD, "23")
        self.click(By.XPATH, self.NEXT3_MOD)
        self.fields(By.XPATH, self.CITY_MOD, "rteh")
        self.fields(By.XPATH, self.NUMBER_MOD, "23")
        self.fields(By.XPATH, self.STREET_MOD, "rtwj")
    def modify_contact_number(self):
        self.setup_trado()
        self.fields(By.XPATH, self.PHONE, "1952222222")
        sleep(1)
        self.click(By.XPATH, self.PHONE_BUTTON)
        sleep(1)
        self.fields(By.XPATH, self.CODE, "1234")
        sleep(1)
        self.click(By.XPATH, self.SAVE_BUTTON)
        sleep(1)
        self.click(By.XPATH, self.CONNECT)
        self.click(By.XPATH, self.PRODUCT)
        self.click(By.XPATH, self.ROW1)
        self.fields(By.XPATH, self.BARCODE_MOD, "deeyu")
        self.fields(By.XPATH, self.NAME_MOD, "take")
        self.fields(By.XPATH, self.EXPIRE_DATE_MOD, "123")
        self.fields(By.XPATH, self.PRICE_MOD, "234")
        self.fields(By.XPATH, self.DESCRIPTION_MOD, "duhdk")
        self.click(By.XPATH, self.NEXT_BUTTON)
        self.fields(By.XPATH, self.PROMOTION_MOD, "uhuouj23")
        self.fields(By.XPATH, self.DEPARTMEN_MOD, "rtwtuw")
        self.fields(By.XPATH, self.DAGKADGA_MOD, "wshns")
        self.fields(By.XPATH, self.CATAGORY_MOD, "ye3djnnd")
        self.fields(By.XPATH, self.PRODUCTTAG_MOD, "ytuhede")
        self.click(By.XPATH, self.NEXT2_MOD)
        self.fields(By.XPATH, self.CARTO_AMOUNT_MOD, "12")
        self.fields(By.XPATH, self.AMOUNT_MOD, "gysynj")
        self.fields(By.XPATH, self.MINIMUM_CATAGORY_MOD, "23")
        self.click(By.XPATH, self.NEXT3_MOD)
        self.fields(By.XPATH, self.CITY_MOD, "rteh")
        self.fields(By.XPATH, self.NUMBER_MOD, "23")
        self.fields(By.XPATH, self.STREET_MOD, "rtwj")
        self.fields(By.XPATH, self.CONTACTNUMBER_MOD, "2563768")
    def next4_button(self):
        self.setup_trado()
        self.fields(By.XPATH, self.PHONE, "1952222222")
        sleep(1)
        self.click(By.XPATH, self.PHONE_BUTTON)
        sleep(1)
        self.fields(By.XPATH, self.CODE, "1234")
        sleep(1)
        self.click(By.XPATH, self.SAVE_BUTTON)
        sleep(1)
        self.click(By.XPATH, self.CONNECT)
        sleep(1)
        self.click(By.XPATH, self.PRODUCT)
        self.click(By.XPATH, self.ROW1)
        self.fields(By.XPATH, self.BARCODE_MOD, "deeyu")
        self.fields(By.XPATH, self.NAME_MOD, "take")
        self.fields(By.XPATH, self.EXPIRE_DATE_MOD, "123")
        self.fields(By.XPATH, self.PRICE_MOD, "234")
        self.fields(By.XPATH, self.DESCRIPTION_MOD, "duhdk")
        self.click(By.XPATH, self.NEXT_BUTTON)
        self.fields(By.XPATH, self.PROMOTION_MOD, "uhuouj23")
        self.fields(By.XPATH, self.DEPARTMEN_MOD, "rtwtuw")
        self.fields(By.XPATH, self.DAGKADGA_MOD, "wshns")
        self.fields(By.XPATH, self.CATAGORY_MOD, "ye3djnnd")
        self.fields(By.XPATH, self.PRODUCTTAG_MOD, "ytuhede")
        self.click(By.XPATH, self.NEXT2_MOD)
        self.fields(By.XPATH, self.CARTO_AMOUNT_MOD, "12")
        self.fields(By.XPATH, self.AMOUNT_MOD, "gysynj")
        self.fields(By.XPATH, self.MINIMUM_CATAGORY_MOD, "23")
        self.click(By.XPATH, self.NEXT3_MOD)
        self.fields(By.XPATH, self.CITY_MOD, "rteh")
        self.fields(By.XPATH, self.NUMBER_MOD, "23")
        self.fields(By.XPATH, self.STREET_MOD, "rtwj")
        self.fields(By.XPATH, self.CONTACTNUMBER_MOD, "2563768")
        self.click(By.XPATH, self.NEXT4_MOD)
    def next5_button(self):
        self.setup_trado()
        self.fields(By.XPATH, self.PHONE, "1952222222")
        sleep(1)
        self.click(By.XPATH, self.PHONE_BUTTON)
        sleep(1)
        self.fields(By.XPATH, self.CODE, "1234")
        sleep(1)
        self.click(By.XPATH, self.SAVE_BUTTON)
        sleep(1)
        self.click(By.XPATH, self.CONNECT)
        sleep(1)
        self.click(By.XPATH, self.PRODUCT)
        self.click(By.XPATH, self.ROW1)
        self.fields(By.XPATH, self.BARCODE_MOD, "deeyu")
        self.fields(By.XPATH, self.NAME_MOD, "take")
        self.fields(By.XPATH, self.EXPIRE_DATE_MOD, "123")
        self.fields(By.XPATH, self.PRICE_MOD, "234")
        self.fields(By.XPATH, self.DESCRIPTION_MOD, "duhdk")
        self.click(By.XPATH, self.NEXT_BUTTON)
        self.fields(By.XPATH, self.PROMOTION_MOD, "uhuouj23")
        self.fields(By.XPATH, self.DEPARTMEN_MOD, "rtwtuw")
        self.fields(By.XPATH, self.DAGKADGA_MOD, "wshns")
        self.fields(By.XPATH, self.CATAGORY_MOD, "ye3djnnd")
        self.fields(By.XPATH, self.PRODUCTTAG_MOD, "ytuhede")
        self.click(By.XPATH, self.NEXT2_MOD)
        self.fields(By.XPATH, self.CARTO_AMOUNT_MOD, "12")
        self.fields(By.XPATH, self.AMOUNT_MOD, "gysynj")
        self.fields(By.XPATH, self.MINIMUM_CATAGORY_MOD, "23")
        self.click(By.XPATH, self.NEXT3_MOD)
        self.fields(By.XPATH, self.CITY_MOD, "rteh")
        self.fields(By.XPATH, self.NUMBER_MOD, "23")
        self.fields(By.XPATH, self.STREET_MOD, "rtwj")
        self.fields(By.XPATH, self.CONTACTNUMBER_MOD, "2563768")
        self.click(By.XPATH, self.NEXT4_MOD)
        self.click(By.XPATH, self.NEXT5_MOD)
    def back_button(self):
        self.setup_trado()
        self.fields(By.XPATH, self.PHONE, "1952222222")
        sleep(1)
        self.click(By.XPATH, self.PHONE_BUTTON)
        sleep(1)
        self.fields(By.XPATH, self.CODE, "1234")
        sleep(1)
        self.click(By.XPATH, self.SAVE_BUTTON)
        sleep(1)
        self.click(By.XPATH, self.CONNECT)
        sleep(1)
        self.click(By.XPATH, self.PRODUCT)
        self.click(By.XPATH, self.ROW1)
        self.fields(By.XPATH, self.BARCODE_MOD, "deeyu")
        self.fields(By.XPATH, self.NAME_MOD, "take")
        self.fields(By.XPATH, self.EXPIRE_DATE_MOD, "123")
        self.fields(By.XPATH, self.PRICE_MOD, "234")
        self.fields(By.XPATH, self.DESCRIPTION_MOD, "duhdk")
        self.click(By.XPATH, self.NEXT_BUTTON)
        self.fields(By.XPATH, self.PROMOTION_MOD, "uhuouj23")
        self.fields(By.XPATH, self.DEPARTMEN_MOD, "rtwtuw")
        self.fields(By.XPATH, self.DAGKADGA_MOD, "wshns")
        self.fields(By.XPATH, self.CATAGORY_MOD, "ye3djnnd")
        self.fields(By.XPATH, self.PRODUCTTAG_MOD, "ytuhede")
        # self.click(By.XPATH, self.NEXT2_MOD)
        # self.fields(By.XPATH, self.CARTO_AMOUNT_MOD, "12")
        # self.fields(By.XPATH, self.AMOUNT_MOD, "gysynj")
        # self.fields(By.XPATH, self.MINIMUM_CATAGORY_MOD, "23")
        # self.click(By.XPATH, self.NEXT3_MOD)
        # self.fields(By.XPATH, self.CITY_MOD, "rteh")
        # self.fields(By.XPATH, self.NUMBER_MOD, "23")
        # self.fields(By.XPATH, self.STREET_MOD, "rtwj")
        # self.fields(By.XPATH, self.CONTACTNUMBER_MOD, "2563768")
        # self.click(By.XPATH, self.NEXT4_MOD)
        # self.click(By.XPATH, self.BACK_MOD)
    def buttu2(self):
        self.setup_trado()
        self.fields(By.XPATH, self.PHONE, "1952222222")
        sleep(1)
        self.click(By.XPATH, self.PHONE_BUTTON)
        sleep(1)
        self.fields(By.XPATH, self.CODE, "1234")
        sleep(1)
        self.click(By.XPATH, self.SAVE_BUTTON)
        self.click(By.XPATH, self.CONNECT)
        self.click(By.XPATH, self.PRODUCT)
        self.click(By.XPATH, self.ROW1)
        self.click(By.XPATH, self.NEXT_BUTTON)
        #self.fields(By.XPATH, self.CATAGORY_MOD, "ye3djnnd")
        #self.click(By.XPATH, self.NEXT2_MOD)

    def next42_button(self):
        self.setup_trado()
        self.fields(By.XPATH, self.PHONE, "1234562345")
        sleep(1)
        self.click(By.XPATH, self.PHONE_BUTTON)
        sleep(1)
        self.fields(By.XPATH, self.CODE, "1234")
        sleep(1)
        self.click(By.XPATH, self.SAVE_BUTTON)
        sleep(1)
        self.click(By.XPATH, self.CONNECT)
        self.click(By.XPATH, self.PRODUCT)
        self.click(By.XPATH, self.ROW1)
        self.fields(By.XPATH, self.BARCODE_MOD, "אטקו")
        self.fields(By.XPATH, self.NAME_MOD, "כעגיחיגח")
        self.click(By.XPATH, self.NEXT_BUTTON)