import time

import pytest
from selenium.webdriver.common.by import By

from Web.TradoUser.Base.base_test import BaseSetups


class TestPayments(BaseSetups):
    def valid_payment_credit_card(self):
        self.setup_trado()
        self.click(By.XPATH, self.COCTAIL)
        self.click(By.XPATH, self.SAVE)
        self.click(By.XPATH, self.CANABIS_CATEGORY)
        self.click(By.XPATH, self.LEMON_OIL_PRO)
        self.click(By.XPATH, self.LEMON_ADD)
        self.click(By.XPATH, self.SALES_CATEGORY)
        self.click(By.XPATH, self.ULTRA_PRO)
        self.click(By.XPATH, self.ULTRA_SOUR_ADD)
        self.click(By.XPATH, self.CHECKOUT)
        self.fields(By.XPATH, self.PHONE_FIELD, "0502006336")
        self.checkbox(By.XPATH, self.CHECK_BOX)
        self.click(By.XPATH, self.CONNECT)
        self.fields(By.XPATH, self.FILL_ONE, self.code_generator())
        self.click(By.XPATH, self.AUTHENTICATION)
        self.click(By.XPATH, self.CHECKOUT)
        self.fields(By.XPATH, self.BUSINESS_NAME_FIELD, "Teamthree")
        self.fields(By.XPATH, self.BN_NUMBER_FIELD, "515074946")
        self.fields(By.XPATH, self.EMAIL_FIELD, "abcd@gmail.com")
        self.fields(By.XPATH, self.CITY_FIELD, "באר שבע, Israel")
        self.fields(By.XPATH, self.STREET_FIELD, "5")
        self.fields(By.XPATH, self.NUMBER_FIELD, "3")
        self.fields(By.XPATH, self.ENTRANCE_FIELD, "5")
        self.fields(By.XPATH, self.FLOOR_FIELD, "8")
        self.fields(By.XPATH, self.DELIVERY_CITY_FIELD, "תל אביב, Israel")
        self.fields(By.XPATH, self.DELIVERY_STREET_FIELD, "5")
        self.fields(By.XPATH, self.DELIVERY_NUMBER_FIELD, "7")
        self.fields(By.XPATH, self.DELIVERY_ENTRANCE_FIELD, "9")
        self.fields(By.XPATH, self.DELIVERY_FLOOR_FIELD, "3")
        self.fields(By.XPATH, self.CONTACT_RECIVER_NAME, "team")
        self.fields(By.XPATH, self.FIRST_NAME_FIELD, "peace")
        self.fields(By.XPATH, self.LAST_NAME_FIELD, "love")
        self.fields(By.XPATH, self.TELEPHONE_FIELD, "0526802789")
        self.click(By.XPATH, self.COMPLETE_PURCHASE)
        self.click(By.XPATH, self.CARTIS_HADASH)
        self.click(By.XPATH, self.CREDIT_CARD_NUMBER_FIELD)
        # self.fields(By.XPATH, self.CREDIT_CARD_NUMBER_FIELD, "4580000000000000")
        # self.click(By.XPATH, self.ID_FIELD)
        # self.fields(By.ID, self.ID_FIELD, "341343390")
        # self.selector(By.XPATH, self.MONTH_SELECTOR, "05")
        # self.selector(By.XPATH, self.YEAR_SELECTOR, "2024")
        # self.fields(By.XPATH, self.CVV_FIELD, "123")
        # self.click(By.XPATH, self.FOR_PAYMENT__BTN)

    def invalid_credit_card(self):
        self.setup_trado()
        self.click(By.XPATH, self.COCTAIL)
        self.click(By.XPATH, self.SAVE)
        self.click(By.XPATH, self.CANABIS_CATEGORY)
        self.click(By.XPATH, self.LEMON_OIL_PRO)
        self.click(By.XPATH, self.LEMON_ADD)
        self.click(By.XPATH, self.SALES_CATEGORY)
        self.click(By.XPATH, self.ULTRA_PRO)
        self.click(By.XPATH, self.ULTRA_SOUR_ADD)
        self.click(By.XPATH, self.CHECKOUT)
        self.fields(By.XPATH, self.PHONE_FIELD, "0535220878")
        self.checkbox(By.XPATH, self.CHECK_BOX)
        self.click(By.XPATH, self.CONNECT)
        self.fields(By.XPATH, self.FILL_ONE, self.code_generator())
        self.click(By.XPATH, self.AUTHENTICATION)
        self.click(By.XPATH, self.CHECKOUT)
        self.fields(By.XPATH, self.BUSINESS_NAME_FIELD, "Teamthree")
        self.fields(By.XPATH, self.BN_NUMBER_FIELD, "515074946")
        self.fields(By.XPATH, self.EMAIL_FIELD, "abcd@gmail.com")
        self.fields(By.XPATH, self.CITY_FIELD, "באר שבע, Israel")
        self.fields(By.XPATH, self.STREET_FIELD, "5")
        self.fields(By.XPATH, self.NUMBER_FIELD, "3")
        self.fields(By.XPATH, self.ENTRANCE_FIELD, "5")
        self.fields(By.XPATH, self.FLOOR_FIELD, "8")
        self.fields(By.XPATH, self.DELIVERY_CITY_FIELD, "תל אביב, Israel")
        self.fields(By.XPATH, self.DELIVERY_STREET_FIELD, "5")
        self.fields(By.XPATH, self.DELIVERY_NUMBER_FIELD, "7")
        self.fields(By.XPATH, self.DELIVERY_ENTRANCE_FIELD, "9")
        self.fields(By.XPATH, self.DELIVERY_FLOOR_FIELD, "3")
        self.fields(By.XPATH, self.CONTACT_RECIVER_NAME, "team")
        self.fields(By.XPATH, self.FIRST_NAME_FIELD, "peace")
        self.fields(By.XPATH, self.LAST_NAME_FIELD, "love")
        self.fields(By.XPATH, self.TELEPHONE_FIELD, "0526802789")
        self.click(By.XPATH, self.COMPLETE_PURCHASE)

        self.click(By.XPATH, self.CARTIS_HADASH)
        self.fields(By.XPATH, self.CREDIT_CARD_NUMBER_FIELD, "")
        self.fields(By.ID, self.ID_FIELD, "100303351")
        self.selector(By.XPATH, self.MONTH_SELECTOR, "05")
        self.selector(By.XPATH, self.YEAR_SELECTOR, "2028")
        self.fields(By.XPATH, self.CVV_FIELD, "100")
        self.click(By.XPATH, self.FOR_PAYMENT__BTN)
        self.tear_down()

    def test_b2b_payment(self):
        self.setup_trado()
        self.click(By.XPATH, self.COCTAIL)
        self.click(By.XPATH, self.SAVE)
        self.click(By.XPATH, self.CANABIS_CATEGORY)
        self.click(By.XPATH, self.LEMON_OIL_PRO)
        self.click(By.XPATH, self.LEMON_ADD)
        self.click(By.XPATH, self.SALES_CATEGORY)
        self.click(By.XPATH, self.ULTRA_PRO)
        self.click(By.XPATH, self.ULTRA_SOUR_ADD)
        self.click(By.XPATH, self.CHECKOUT)
        self.fields(By.XPATH, self.PHONE_FIELD, "0502006336")
        self.checkbox(By.XPATH, self.CHECK_BOX)
        self.click(By.XPATH, self.CONNECT)
        self.fields(By.XPATH, self.FILL_ONE, self.code_generator())
        self.click(By.XPATH, self.AUTHENTICATION)
        self.click(By.XPATH, self.CHECKOUT)
        self.fields(By.XPATH, self.BUSINESS_NAME_FIELD, "Teamthree")
        self.fields(By.XPATH, self.BN_NUMBER_FIELD, "515074946")
        self.fields(By.XPATH, self.EMAIL_FIELD, "abcd@gmail.com")
        self.fields(By.XPATH, self.CITY_FIELD, "באר שבע, Israel")
        self.fields(By.XPATH, self.STREET_FIELD, "5")
        self.fields(By.XPATH, self.NUMBER_FIELD, "3")
        self.fields(By.XPATH, self.ENTRANCE_FIELD, "5")
        self.fields(By.XPATH, self.FLOOR_FIELD, "8")
        self.fields(By.XPATH, self.DELIVERY_CITY_FIELD, "תל אביב, Israel")
        self.fields(By.XPATH, self.DELIVERY_STREET_FIELD, "5")
        self.fields(By.XPATH, self.DELIVERY_NUMBER_FIELD, "7")
        self.fields(By.XPATH, self.DELIVERY_ENTRANCE_FIELD, "9")
        self.fields(By.XPATH, self.DELIVERY_FLOOR_FIELD, "3")
        self.fields(By.XPATH, self.CONTACT_RECIVER_NAME, "team")
        self.fields(By.XPATH, self.FIRST_NAME_FIELD, "team-3")
        self.fields(By.XPATH, self.LAST_NAME_FIELD, "team-3")
        self.fields(By.XPATH, self.TELEPHONE_FIELD, "0526802789")
        self.click(By.XPATH, self.COMPLETE_PURCHASE)
        self.click(By.XPATH, self.B2B_METHOD)
        self.fields(By.XPATH, self.BN_NUMBER_PAYMENT, "5251784945")
        self.fields(By.XPATH, self.BN_CUSTOMER_ID, "557")
        self.click(By.XPATH, self.CONFIRM_TRANSFER)
        self.click(By.XPATH, self.PURCHASE)
        assert self.assertion(By.XPATH, self.SUCCESS_TITLE) == 'תודה שהזמנת דרכנו!'
        self.click(By.XPATH, self.BACK_TO_HOME)
        self.tear_down()

    def valid_payment_digital_check(self):
        self.setup_trado()
        self.click(By.XPATH, self.COCTAIL)
        self.click(By.XPATH, self.SAVE)
        self.click(By.XPATH, self.CANABIS_CATEGORY)
        self.click(By.XPATH, self.LEMON_OIL_PRO)
        self.click(By.XPATH, self.LEMON_ADD)
        self.click(By.XPATH, self.SALES_CATEGORY)
        self.click(By.XPATH, self.ULTRA_PRO)
        self.click(By.XPATH, self.ULTRA_SOUR_ADD)
        self.click(By.XPATH, self.CHECKOUT)
        self.fields(By.XPATH, self.PHONE_FIELD, "0502006336")
        self.checkbox(By.XPATH, self.CHECK_BOX)
        self.click(By.XPATH, self.CONNECT)
        self.fields(By.XPATH, self.FILL_ONE, self.code_generator())
        self.click(By.XPATH, self.AUTHENTICATION)
        self.click(By.XPATH, self.CHECKOUT)
        self.fields(By.XPATH, self.BUSINESS_NAME_FIELD, "Teamthree")
        self.fields(By.XPATH, self.BN_NUMBER_FIELD, "515074946")
        self.fields(By.XPATH, self.EMAIL_FIELD, "abcd@gmail.com")
        self.fields(By.XPATH, self.CITY_FIELD, "באר שבע, Israel")
        self.fields(By.XPATH, self.STREET_FIELD, "5")
        self.fields(By.XPATH, self.NUMBER_FIELD, "3")
        self.fields(By.XPATH, self.ENTRANCE_FIELD, "5")
        self.fields(By.XPATH, self.FLOOR_FIELD, "8")
        self.fields(By.XPATH, self.DELIVERY_CITY_FIELD, "תל אביב, Israel")
        self.fields(By.XPATH, self.DELIVERY_STREET_FIELD, "5")
        self.fields(By.XPATH, self.DELIVERY_NUMBER_FIELD, "7")
        self.fields(By.XPATH, self.DELIVERY_ENTRANCE_FIELD, "9")
        self.fields(By.XPATH, self.DELIVERY_FLOOR_FIELD, "3")
        self.fields(By.XPATH, self.CONTACT_RECIVER_NAME, "team")
        self.fields(By.XPATH, self.FIRST_NAME_FIELD, "Gashaw")
        self.fields(By.XPATH, self.LAST_NAME_FIELD, "team-3")
        self.fields(By.XPATH, self.TELEPHONE_FIELD, "0526802789")
        self.click(By.XPATH, self.COMPLETE_PURCHASE)
        self.click(By.XPATH, self.DIGTAL_CHECK)
        self.selector(By.XPATH, self.BANK_NAME, "11 - בנק דיסקונט")
        self.fields(By.XPATH, self.BRANCH, "beersheva")
        self.fields(By.XPATH, self.BANK_ACCOUNT, "456123")
        self.fields(By.XPATH, self.ACCOUNT_HOLDER_NAME, "Team three")
        self.click(By.XPATH, self.IMMEDIATE_PAYMENT)
        self.click(By.XPATH, self.INSERT_BUTTON)
        self.click(By.XPATH, self.PURCHASE)
        assert self.assertion(By.XPATH, self.SUCCESS_TITLE) == 'תודה שהזמנת דרכנו!'
        self.click(By.XPATH, self.BACK_TO_HOME)
        self.tear_down()

    def valid_payment_digital_check_with_flowing30(self):
        self.setup_trado()
        self.click(By.XPATH, self.COCTAIL)
        self.click(By.XPATH, self.SAVE)
        self.click(By.XPATH, self.CANABIS_CATEGORY)
        self.click(By.XPATH, self.LEMON_OIL_PRO)
        self.click(By.XPATH, self.LEMON_ADD)
        self.click(By.XPATH, self.SALES_CATEGORY)
        self.click(By.XPATH, self.ULTRA_PRO)
        self.click(By.XPATH, self.ULTRA_SOUR_ADD)
        self.click(By.XPATH, self.CHECKOUT)
        self.fields(By.XPATH, self.PHONE_FIELD, "0502006336")
        self.checkbox(By.XPATH, self.CHECK_BOX)
        self.click(By.XPATH, self.CONNECT)
        self.fields(By.XPATH, self.FILL_ONE, self.code_generator())
        self.click(By.XPATH, self.AUTHENTICATION)
        self.click(By.XPATH, self.CHECKOUT)
        self.fields(By.XPATH, self.BUSINESS_NAME_FIELD, "The Defiant")
        self.fields(By.XPATH, self.BN_NUMBER_FIELD, "515074946")
        self.fields(By.XPATH, self.EMAIL_FIELD, "abcd@gmail.com")
        self.fields(By.XPATH, self.CITY_FIELD, "באר שבע, Israel")
        self.fields(By.XPATH, self.STREET_FIELD, "5")
        self.fields(By.XPATH, self.NUMBER_FIELD, "3")
        self.fields(By.XPATH, self.ENTRANCE_FIELD, "5")
        self.fields(By.XPATH, self.FLOOR_FIELD, "8")
        self.fields(By.XPATH, self.DELIVERY_CITY_FIELD, "תל אביב, Israel")
        self.fields(By.XPATH, self.DELIVERY_STREET_FIELD, "5")
        self.fields(By.XPATH, self.DELIVERY_NUMBER_FIELD, "7")
        self.fields(By.XPATH, self.DELIVERY_ENTRANCE_FIELD, "9")
        self.fields(By.XPATH, self.DELIVERY_FLOOR_FIELD, "3")
        self.fields(By.XPATH, self.CONTACT_RECIVER_NAME, "team")
        self.fields(By.XPATH, self.FIRST_NAME_FIELD, "defiant")
        self.fields(By.XPATH, self.LAST_NAME_FIELD, "ttt")
        self.fields(By.XPATH, self.TELEPHONE_FIELD, "0526802789")
        self.click(By.XPATH, self.COMPLETE_PURCHASE)
        self.click(By.XPATH, self.DIGTAL_CHECK)
        self.selector(By.XPATH, self.BANK_NAME, "11 - בנק דיסקונט")
        self.fields(By.XPATH, self.BRANCH, "8")
        self.fields(By.XPATH, self.BANK_ACCOUNT, "78963")
        self.fields(By.XPATH, self.ACCOUNT_HOLDER_NAME, "rtfg")
        self.click(By.XPATH, self.FLOWING_30)
        self.click(By.XPATH, self.INSERT_BUTTON)
        self.click(By.XPATH, self.PURCHASE)
        assert self.assertion(By.XPATH, self.SUCCESS_TITLE) == 'תודה שהזמנת דרכנו!'
        self.click(By.XPATH, self.BACK_TO_HOME)

    def valid_payment_FinTrado(self):
        self.setup_trado()
        self.click(By.XPATH, self.COCTAIL)
        self.click(By.XPATH, self.SAVE)
        self.click(By.XPATH, self.CANABIS_CATEGORY)
        self.click(By.XPATH, self.LEMON_OIL_PRO)
        self.click(By.XPATH, self.LEMON_ADD)
        self.click(By.XPATH, self.CHECKOUT)
        self.fields(By.XPATH, self.PHONE_FIELD, "0502006336")
        self.checkbox(By.XPATH, self.CHECK_BOX)
        self.click(By.XPATH, self.CONNECT)
        self.fields(By.XPATH, self.FILL_ONE, self.code_generator())
        self.click(By.XPATH, self.AUTHENTICATION)
        self.click(By.XPATH, self.CHECKOUT)
        self.fields(By.XPATH, self.BUSINESS_NAME_FIELD, "The Defiant")
        self.fields(By.XPATH, self.BN_NUMBER_FIELD, "515074946")
        self.fields(By.XPATH, self.EMAIL_FIELD, "abcdg@gmail.com")
        self.fields(By.XPATH, self.CITY_FIELD, "באר שבע, Israel")
        self.fields(By.XPATH, self.STREET_FIELD, "5")
        self.fields(By.XPATH, self.NUMBER_FIELD, "3")
        self.fields(By.XPATH, self.ENTRANCE_FIELD, "5")
        self.fields(By.XPATH, self.FLOOR_FIELD, "8")
        self.fields(By.XPATH, self.DELIVERY_CITY_FIELD, "תל אביב, Israel")
        self.fields(By.XPATH, self.DELIVERY_STREET_FIELD, "5")
        self.fields(By.XPATH, self.DELIVERY_NUMBER_FIELD, "7")
        self.fields(By.XPATH, self.DELIVERY_ENTRANCE_FIELD, "9")
        self.fields(By.XPATH, self.DELIVERY_FLOOR_FIELD, "3")
        self.fields(By.XPATH, self.CONTACT_RECIVER_NAME, "team")
        self.fields(By.XPATH, self.FIRST_NAME_FIELD, "team3")
        self.fields(By.XPATH, self.LAST_NAME_FIELD, "team3")
        self.fields(By.XPATH, self.TELEPHONE_FIELD, "0501234567")
        self.click(By.XPATH, self.COMPLETE_PURCHASE)
        self.click(By.XPATH, self.FINTRADO)
        self.selector(By.XPATH, self.LOAN_PERIOD_TIME, "12")
        self.click(By.XPATH, self.NEXT1)
        self.click(By.XPATH, self.NEXT2)
        # assert self.assertion(By.XPATH, self.REQ_APPROVED) == 'מזל טוב! בקשתך אושרה באופן עקרוני'
        self.click(By.XPATH, self.FINISH_ORDER)
        self.click(By.XPATH, self.PURCHASE)
        assert self.assertion(By.XPATH, self.SUCCESS_TITLE) == 'תודה שהזמנת דרכנו!'
        self.click(By.XPATH, self.BACK_TO_HOME)

    def valid_payment_FinTrado_without_accepting_1policy(self):
        self.setup_trado()
        self.click(By.XPATH, self.COCTAIL)
        self.click(By.XPATH, self.SAVE)
        self.click(By.XPATH, self.CANABIS_CATEGORY)
        self.click(By.XPATH, self.LEMON_OIL_PRO)
        self.click(By.XPATH, self.LEMON_ADD)
        self.click(By.XPATH, self.CHECKOUT)
        self.fields(By.XPATH, self.PHONE_FIELD, "0502006336")
        self.checkbox(By.XPATH, self.CHECK_BOX)
        self.click(By.XPATH, self.CONNECT)
        self.fields(By.XPATH, self.FILL_ONE, self.code_generator())
        self.click(By.XPATH, self.AUTHENTICATION)
        self.click(By.XPATH, self.CHECKOUT)
        self.fields(By.XPATH, self.BUSINESS_NAME_FIELD, "The Defiant")
        self.fields(By.XPATH, self.BN_NUMBER_FIELD, "515074946")
        self.fields(By.XPATH, self.EMAIL_FIELD, "abcdg@gmail.com")
        self.fields(By.XPATH, self.CITY_FIELD, "באר שבע, Israel")
        self.fields(By.XPATH, self.STREET_FIELD, "5")
        self.fields(By.XPATH, self.NUMBER_FIELD, "3")
        self.fields(By.XPATH, self.ENTRANCE_FIELD, "5")
        self.fields(By.XPATH, self.FLOOR_FIELD, "8")
        self.fields(By.XPATH, self.DELIVERY_CITY_FIELD, "תל אביב, Israel")
        self.fields(By.XPATH, self.DELIVERY_STREET_FIELD, "5")
        self.fields(By.XPATH, self.DELIVERY_NUMBER_FIELD, "7")
        self.fields(By.XPATH, self.DELIVERY_ENTRANCE_FIELD, "9")
        self.fields(By.XPATH, self.DELIVERY_FLOOR_FIELD, "3")
        self.fields(By.XPATH, self.CONTACT_RECIVER_NAME, "team")
        self.fields(By.XPATH, self.FIRST_NAME_FIELD, "peace")
        self.fields(By.XPATH, self.LAST_NAME_FIELD, "love")
        self.fields(By.XPATH, self.TELEPHONE_FIELD, "0526802789")
        self.click(By.XPATH, self.COMPLETE_PURCHASE)
        self.click(By.XPATH, self.FINTRADO)
        self.selector(By.XPATH, self.LOAN_PERIOD_TIME, "12")
        self.click(By.XPATH, self.NEXT1)
        self.checkbox(By.XPATH, self.VERIF1)
        assert self.assertion(By.XPATH, self.CONFIRM_2POLICY) == 'Must Confirm 2 Terms For Complete'
        self.click(By.XPATH, self.NEXT2)

    def valid_payment_FinTrado_without_accepting_2policy(self):
        self.setup_trado()
        self.click(By.XPATH, self.COCTAIL)
        self.click(By.XPATH, self.SAVE)
        self.click(By.XPATH, self.CANABIS_CATEGORY)
        self.click(By.XPATH, self.LEMON_OIL_PRO)
        self.click(By.XPATH, self.LEMON_ADD)
        self.click(By.XPATH, self.CHECKOUT)
        self.fields(By.XPATH, self.PHONE_FIELD, "0502006336")
        self.checkbox(By.XPATH, self.CHECK_BOX)
        self.click(By.XPATH, self.CONNECT)
        self.fields(By.XPATH, self.FILL_ONE, self.code_generator())
        self.click(By.XPATH, self.AUTHENTICATION)
        self.click(By.XPATH, self.CHECKOUT)
        self.fields(By.XPATH, self.BUSINESS_NAME_FIELD, "The Defiant")
        self.fields(By.XPATH, self.BN_NUMBER_FIELD, "515074946")
        self.fields(By.XPATH, self.EMAIL_FIELD, "abcdg@gmail.com")
        self.fields(By.XPATH, self.CITY_FIELD, "באר שבע, Israel")
        self.fields(By.XPATH, self.STREET_FIELD, "5")
        self.fields(By.XPATH, self.NUMBER_FIELD, "3")
        self.fields(By.XPATH, self.ENTRANCE_FIELD, "5")
        self.fields(By.XPATH, self.FLOOR_FIELD, "8")
        self.fields(By.XPATH, self.DELIVERY_CITY_FIELD, "תל אביב, Israel")
        self.fields(By.XPATH, self.DELIVERY_STREET_FIELD, "5")
        self.fields(By.XPATH, self.DELIVERY_NUMBER_FIELD, "7")
        self.fields(By.XPATH, self.DELIVERY_ENTRANCE_FIELD, "9")
        self.fields(By.XPATH, self.DELIVERY_FLOOR_FIELD, "3")
        self.fields(By.XPATH, self.CONTACT_RECIVER_NAME, "team")
        self.fields(By.XPATH, self.FIRST_NAME_FIELD, "peace")
        self.fields(By.XPATH, self.LAST_NAME_FIELD, "love")
        self.fields(By.XPATH, self.TELEPHONE_FIELD, "0526802789")
        self.click(By.XPATH, self.COMPLETE_PURCHASE)
        self.click(By.XPATH, self.FINTRADO)
        self.selector(By.XPATH, self.LOAN_PERIOD_TIME, "12")
        self.click(By.XPATH, self.NEXT1)
        self.checkbox(By.XPATH, self.VERIF1)
        assert self.assertion(By.XPATH, self.CONFIRM_2POLICY) == 'Must Confirm 2 Terms For Complete'
        self.click(By.XPATH, self.NEXT2)
        self.tear_down()

    # invalid tests

    def invalid_customer_id_b2b_payment(self):
        self.setup_trado()
        self.click(By.XPATH, self.COCTAIL)
        self.click(By.XPATH, self.SAVE)
        self.click(By.XPATH, self.CANABIS_CATEGORY)
        self.click(By.XPATH, self.LEMON_OIL_PRO)
        self.click(By.XPATH, self.LEMON_ADD)
        self.click(By.XPATH, self.SALES_CATEGORY)
        self.click(By.XPATH, self.ULTRA_PRO)
        self.click(By.XPATH, self.ULTRA_SOUR_ADD)
        self.click(By.XPATH, self.CHECKOUT)
        self.fields(By.XPATH, self.PHONE_FIELD, "0502006336")
        self.checkbox(By.XPATH, self.CHECK_BOX)
        self.click(By.XPATH, self.CONNECT)
        self.fields(By.XPATH, self.FILL_ONE, self.code_generator())
        self.click(By.XPATH, self.AUTHENTICATION)
        self.click(By.XPATH, self.CHECKOUT)
        self.fields(By.XPATH, self.BUSINESS_NAME_FIELD, "Teamthree")
        self.fields(By.XPATH, self.BN_NUMBER_FIELD, "515074946")
        self.fields(By.XPATH, self.EMAIL_FIELD, "abcd@gmail.com")
        self.fields(By.XPATH, self.CITY_FIELD, "באר שבע, Israel")
        self.fields(By.XPATH, self.STREET_FIELD, "5")
        self.fields(By.XPATH, self.NUMBER_FIELD, "3")
        self.fields(By.XPATH, self.ENTRANCE_FIELD, "5")
        self.fields(By.XPATH, self.FLOOR_FIELD, "8")
        self.fields(By.XPATH, self.DELIVERY_CITY_FIELD, "תל אביב, Israel")
        self.fields(By.XPATH, self.DELIVERY_STREET_FIELD, "5")
        self.fields(By.XPATH, self.DELIVERY_NUMBER_FIELD, "7")
        self.fields(By.XPATH, self.DELIVERY_ENTRANCE_FIELD, "9")
        self.fields(By.XPATH, self.DELIVERY_FLOOR_FIELD, "3")
        self.fields(By.XPATH, self.CONTACT_RECIVER_NAME, "team")
        self.fields(By.XPATH, self.FIRST_NAME_FIELD, "peace")
        self.fields(By.XPATH, self.LAST_NAME_FIELD, "love")
        self.fields(By.XPATH, self.TELEPHONE_FIELD, "0526802789")
        self.click(By.XPATH, self.COMPLETE_PURCHASE)
        self.click(By.XPATH, self.B2B_METHOD)
        self.fields(By.XPATH, self.BN_NUMBER_PAYMENT, "5251784945")
        self.fields(By.XPATH, self.BN_CUSTOMER_ID, "")
        self.click(By.XPATH, self.CONFIRM_TRANSFER)
        self.click(By.XPATH, self.PURCHASE)
        assert self.assertion(By.XPATH, self.SUCCESS_TITLE) == ''
        self.click(By.XPATH, self.BACK_TO_HOME)
        self.tear_down()

    def invalid_payment_digital_check(self):
        self.setup_trado()
        self.click(By.XPATH, self.COCTAIL)
        self.click(By.XPATH, self.SAVE)
        self.click(By.XPATH, self.CANABIS_CATEGORY)
        self.click(By.XPATH, self.LEMON_OIL_PRO)
        self.click(By.XPATH, self.LEMON_ADD)
        self.click(By.XPATH, self.SALES_CATEGORY)
        self.click(By.XPATH, self.ULTRA_PRO)
        self.click(By.XPATH, self.ULTRA_SOUR_ADD)
        self.click(By.XPATH, self.CHECKOUT)
        self.fields(By.XPATH, self.PHONE_FIELD, "0502006336")
        self.checkbox(By.XPATH, self.CHECK_BOX)
        self.click(By.XPATH, self.CONNECT)
        self.fields(By.XPATH, self.FILL_ONE, self.code_generator())
        self.click(By.XPATH, self.AUTHENTICATION)
        self.click(By.XPATH, self.CHECKOUT)
        self.fields(By.XPATH, self.BUSINESS_NAME_FIELD, "The Defiant")
        self.fields(By.XPATH, self.BN_NUMBER_FIELD, "515074946")
        self.fields(By.XPATH, self.EMAIL_FIELD, "abcd@gmail.com")
        self.fields(By.XPATH, self.CITY_FIELD, "באר שבע, Israel")
        self.fields(By.XPATH, self.STREET_FIELD, "5")
        self.fields(By.XPATH, self.NUMBER_FIELD, "3")
        self.fields(By.XPATH, self.ENTRANCE_FIELD, "5")
        self.fields(By.XPATH, self.FLOOR_FIELD, "8")
        self.fields(By.XPATH, self.DELIVERY_CITY_FIELD, "תל אביב, Israel")
        self.fields(By.XPATH, self.DELIVERY_STREET_FIELD, "5")
        self.fields(By.XPATH, self.DELIVERY_NUMBER_FIELD, "7")
        self.fields(By.XPATH, self.DELIVERY_ENTRANCE_FIELD, "9")
        self.fields(By.XPATH, self.DELIVERY_FLOOR_FIELD, "3")
        self.fields(By.XPATH, self.CONTACT_RECIVER_NAME, "team")
        self.fields(By.XPATH, self.FIRST_NAME_FIELD, "defiant")
        self.fields(By.XPATH, self.LAST_NAME_FIELD, "ttt")
        self.fields(By.XPATH, self.TELEPHONE_FIELD, "0526802789")
        self.click(By.XPATH, self.COMPLETE_PURCHASE)
        self.click(By.XPATH, self.DIGTAL_CHECK)
        self.selector(By.XPATH, self.BANK_NAME, "11 - בנק דיסקונט")
        self.fields(By.XPATH, self.BRANCH, "")
        self.fields(By.XPATH, self.BANK_ACCOUNT, "")
        self.fields(By.XPATH, self.ACCOUNT_HOLDER_NAME, "")
        self.click(By.XPATH, self.IMMEDIATE_PAYMENT)
        self.click(By.XPATH, self.INSERT_BUTTON)
        self.click(By.XPATH, self.PURCHASE)
        assert self.assertion(By.XPATH, self.SUCCESS_TITLE) == ''
        self.click(By.XPATH, self.BACK_TO_HOME)

    def valid_payment_digital_check_with_flowing60(self):
        self.setup_trado()
        self.click(By.XPATH, self.COCTAIL)
        self.click(By.XPATH, self.SAVE)
        self.click(By.XPATH, self.CANABIS_CATEGORY)
        self.click(By.XPATH, self.LEMON_OIL_PRO)
        self.click(By.XPATH, self.LEMON_ADD)
        self.click(By.XPATH, self.SALES_CATEGORY)
        self.click(By.XPATH, self.ULTRA_PRO)
        self.click(By.XPATH, self.ULTRA_SOUR_ADD)
        self.click(By.XPATH, self.CHECKOUT)
        self.fields(By.XPATH, self.PHONE_FIELD, "0502006336")
        self.checkbox(By.XPATH, self.CHECK_BOX)
        self.click(By.XPATH, self.CONNECT)
        self.fields(By.XPATH, self.FILL_ONE, self.code_generator())
        self.click(By.XPATH, self.AUTHENTICATION)
        self.click(By.XPATH, self.CHECKOUT)
        self.fields(By.XPATH, self.BUSINESS_NAME_FIELD, "The Defiant")
        self.fields(By.XPATH, self.BN_NUMBER_FIELD, "515074946")
        self.fields(By.XPATH, self.EMAIL_FIELD, "abcd@gmail.com")
        self.fields(By.XPATH, self.CITY_FIELD, "באר שבע, Israel")
        self.fields(By.XPATH, self.STREET_FIELD, "5")
        self.fields(By.XPATH, self.NUMBER_FIELD, "3")
        self.fields(By.XPATH, self.ENTRANCE_FIELD, "5")
        self.fields(By.XPATH, self.FLOOR_FIELD, "8")
        self.fields(By.XPATH, self.DELIVERY_CITY_FIELD, "תל אביב, Israel")
        self.fields(By.XPATH, self.DELIVERY_STREET_FIELD, "5")
        self.fields(By.XPATH, self.DELIVERY_NUMBER_FIELD, "7")
        self.fields(By.XPATH, self.DELIVERY_ENTRANCE_FIELD, "9")
        self.fields(By.XPATH, self.DELIVERY_FLOOR_FIELD, "3")
        self.fields(By.XPATH, self.CONTACT_RECIVER_NAME, "team")
        self.fields(By.XPATH, self.FIRST_NAME_FIELD, "defiant")
        self.fields(By.XPATH, self.LAST_NAME_FIELD, "ttt")
        self.fields(By.XPATH, self.TELEPHONE_FIELD, "0526802789")
        self.click(By.XPATH, self.COMPLETE_PURCHASE)
        self.click(By.XPATH, self.DIGTAL_CHECK)
        self.selector(By.XPATH, self.BANK_NAME, "11 - בנק דיסקונט")
        self.fields(By.XPATH, self.BRANCH, "8")
        self.fields(By.XPATH, self.BANK_ACCOUNT, "78963")
        self.fields(By.XPATH, self.ACCOUNT_HOLDER_NAME, "rtfg")
        self.click(By.XPATH, self.FLOWING_60)
        self.click(By.XPATH, self.INSERT_BUTTON)
        self.click(By.XPATH, self.PURCHASE)
        assert self.assertion(By.XPATH, self.SUCCESS_TITLE) == '!='
        self.click(By.XPATH, self.BACK_TO_HOME)

    def valid_payment_digital_check_with_flowing90(self):
        self.setup_trado()
        self.click(By.XPATH, self.COCTAIL)
        self.click(By.XPATH, self.SAVE)
        self.click(By.XPATH, self.CANABIS_CATEGORY)
        self.click(By.XPATH, self.LEMON_OIL_PRO)
        self.click(By.XPATH, self.LEMON_ADD)
        self.click(By.XPATH, self.SALES_CATEGORY)
        self.click(By.XPATH, self.ULTRA_PRO)
        self.click(By.XPATH, self.ULTRA_SOUR_ADD)
        self.click(By.XPATH, self.CHECKOUT)
        self.fields(By.XPATH, self.PHONE_FIELD, "0502006336")
        self.checkbox(By.XPATH, self.CHECK_BOX)
        self.click(By.XPATH, self.CONNECT)
        self.fields(By.XPATH, self.FILL_ONE, self.code_generator())
        self.click(By.XPATH, self.AUTHENTICATION)
        self.click(By.XPATH, self.CHECKOUT)
        self.fields(By.XPATH, self.BUSINESS_NAME_FIELD, "The Defiant")
        self.fields(By.XPATH, self.BN_NUMBER_FIELD, "515074946")
        self.fields(By.XPATH, self.EMAIL_FIELD, "abcd@gmail.com")
        self.fields(By.XPATH, self.CITY_FIELD, "באר שבע, Israel")
        self.fields(By.XPATH, self.STREET_FIELD, "5")
        self.fields(By.XPATH, self.NUMBER_FIELD, "3")
        self.fields(By.XPATH, self.ENTRANCE_FIELD, "5")
        self.fields(By.XPATH, self.FLOOR_FIELD, "8")
        self.fields(By.XPATH, self.DELIVERY_CITY_FIELD, "תל אביב, Israel")
        self.fields(By.XPATH, self.DELIVERY_STREET_FIELD, "5")
        self.fields(By.XPATH, self.DELIVERY_NUMBER_FIELD, "7")
        self.fields(By.XPATH, self.DELIVERY_ENTRANCE_FIELD, "9")
        self.fields(By.XPATH, self.DELIVERY_FLOOR_FIELD, "3")
        self.fields(By.XPATH, self.CONTACT_RECIVER_NAME, "team")
        self.fields(By.XPATH, self.FIRST_NAME_FIELD, "defiant")
        self.fields(By.XPATH, self.LAST_NAME_FIELD, "ttt")
        self.fields(By.XPATH, self.TELEPHONE_FIELD, "0526802789")
        self.click(By.XPATH, self.COMPLETE_PURCHASE)
        self.click(By.XPATH, self.DIGTAL_CHECK)
        self.selector(By.XPATH, self.BANK_NAME, "11 - בנק דיסקונט")
        self.fields(By.XPATH, self.BRANCH, "8")
        self.fields(By.XPATH, self.BANK_ACCOUNT, "78963")
        self.fields(By.XPATH, self.ACCOUNT_HOLDER_NAME, "rtfg")
        self.click(By.XPATH, self.FLOWING_90)
        self.click(By.XPATH, self.INSERT_BUTTON)
        self.click(By.XPATH, self.PURCHASE)
        assert self.assertion(By.XPATH, self.SUCCESS_TITLE) == ''
        self.click(By.XPATH, self.BACK_TO_HOME)

    def valid_payment_bank_transfer(self):
        self.setup_trado()
        self.click(By.XPATH, self.COCTAIL)
        self.click(By.XPATH, self.SAVE)
        self.click(By.XPATH, self.CANABIS_CATEGORY)
        self.click(By.XPATH, self.LEMON_OIL_PRO)
        self.click(By.XPATH, self.LEMON_ADD)
        self.click(By.XPATH, self.SALES_CATEGORY)
        self.click(By.XPATH, self.ULTRA_PRO)
        self.click(By.XPATH, self.ULTRA_SOUR_ADD)
        self.click(By.XPATH, self.CHECKOUT)
        self.fields(By.XPATH, self.PHONE_FIELD, "0502006336")
        self.checkbox(By.XPATH, self.CHECK_BOX)
        self.click(By.XPATH, self.CONNECT)
        self.fields(By.XPATH, self.FILL_ONE, self.code_generator())
        self.click(By.XPATH, self.AUTHENTICATION)
        self.click(By.XPATH, self.CHECKOUT)
        self.fields(By.XPATH, self.BUSINESS_NAME_FIELD, "Team-three")
        self.fields(By.XPATH, self.BN_NUMBER_FIELD, "515074946")
        self.fields(By.XPATH, self.EMAIL_FIELD, "abcd@gmail.com")
        self.fields(By.XPATH, self.CITY_FIELD, "באר שבע, Israel")
        self.fields(By.XPATH, self.STREET_FIELD, "5")
        self.fields(By.XPATH, self.NUMBER_FIELD, "3")
        self.fields(By.XPATH, self.ENTRANCE_FIELD, "5")
        self.fields(By.XPATH, self.FLOOR_FIELD, "8")
        self.fields(By.XPATH, self.DELIVERY_CITY_FIELD, "תל אביב, Israel")
        self.fields(By.XPATH, self.DELIVERY_STREET_FIELD, "5")
        self.fields(By.XPATH, self.DELIVERY_NUMBER_FIELD, "7")
        self.fields(By.XPATH, self.DELIVERY_ENTRANCE_FIELD, "9")
        self.fields(By.XPATH, self.DELIVERY_FLOOR_FIELD, "3")
        self.fields(By.XPATH, self.CONTACT_RECIVER_NAME, "team")
        self.fields(By.XPATH, self.FIRST_NAME_FIELD, "peace")
        self.fields(By.XPATH, self.LAST_NAME_FIELD, "love")
        self.fields(By.XPATH, self.TELEPHONE_FIELD, "0526802789")
        self.click(By.XPATH, self.COMPLETE_PURCHASE)
        self.click(By.XPATH, self.BANK_TRANSFER)
        self.selector(By.XPATH, self.BANK_NAME_TRANSFER, "9 - בנק הדואר")
        self.fields(By.XPATH, self.BRANCH_TRANSFER, "באר שבע")
        self.fields(By.XPATH, self.TRANSFER_ACCOUNT_NO, "614523")
        self.fields(By.XPATH, self.ACCOUNT_HOLDER_NAME_TRANSFER, "Team3")
        self.fields(By.XPATH, self.TRANSFER_BNNUMBER, "507514946")
        self.click(By.CSS_SELECTOR, self.CONFIRM_TRANSFER_BANK)
        self.click(By.XPATH, self.PURCHASE)
        assert self.assertion(By.XPATH, self.SUCCESS_TITLE) == 'תודה שהזמנת דרכנו!'
        self.click(By.XPATH, self.BACK_TO_HOME)

    def invalid_account_no_payment_bank_transfer(self):
        self.setup_trado()
        self.click(By.XPATH, self.COCTAIL)
        self.click(By.XPATH, self.SAVE)
        self.click(By.XPATH, self.CANABIS_CATEGORY)
        self.click(By.XPATH, self.LEMON_OIL_PRO)
        self.click(By.XPATH, self.LEMON_ADD)
        self.click(By.XPATH, self.SALES_CATEGORY)
        self.click(By.XPATH, self.ULTRA_PRO)
        self.click(By.XPATH, self.ULTRA_SOUR_ADD)
        self.click(By.XPATH, self.CHECKOUT)
        self.fields(By.XPATH, self.PHONE_FIELD, "0502006336")
        self.checkbox(By.XPATH, self.CHECK_BOX)
        self.click(By.XPATH, self.CONNECT)
        self.fields(By.XPATH, self.FILL_ONE, self.code_generator())
        self.click(By.XPATH, self.AUTHENTICATION)
        self.click(By.XPATH, self.CHECKOUT)
        self.fields(By.XPATH, self.BUSINESS_NAME_FIELD, "Teamthree")
        self.fields(By.XPATH, self.BN_NUMBER_FIELD, "515074946")
        self.fields(By.XPATH, self.EMAIL_FIELD, "abcd@gmail.com")
        self.fields(By.XPATH, self.CITY_FIELD, "באר שבע, Israel")
        self.fields(By.XPATH, self.STREET_FIELD, "5")
        self.fields(By.XPATH, self.NUMBER_FIELD, "3")
        self.fields(By.XPATH, self.ENTRANCE_FIELD, "5")
        self.fields(By.XPATH, self.FLOOR_FIELD, "8")
        self.fields(By.XPATH, self.DELIVERY_CITY_FIELD, "תל אביב, Israel")
        self.fields(By.XPATH, self.DELIVERY_STREET_FIELD, "5")
        self.fields(By.XPATH, self.DELIVERY_NUMBER_FIELD, "7")
        self.fields(By.XPATH, self.DELIVERY_ENTRANCE_FIELD, "9")
        self.fields(By.XPATH, self.DELIVERY_FLOOR_FIELD, "3")
        self.fields(By.XPATH, self.CONTACT_RECIVER_NAME, "team")
        self.fields(By.XPATH, self.FIRST_NAME_FIELD, "peace")
        self.fields(By.XPATH, self.LAST_NAME_FIELD, "love")
        self.fields(By.XPATH, self.TELEPHONE_FIELD, "0526802789")
        self.click(By.XPATH, self.COMPLETE_PURCHASE)
        self.click(By.XPATH, self.BANK_TRANSFER)
        self.selector(By.XPATH, self.BANK_NAME_TRANSFER, "9 - בנק הדואר")
        self.fields(By.XPATH, self.BRANCH_TRANSFER, "באר שבע")
        self.fields(By.XPATH, self.TRANSFER_ACCOUNT_NO, "")
        self.fields(By.XPATH, self.ACCOUNT_HOLDER_NAME_TRANSFER, "Team3")
        self.fields(By.XPATH, self.TRANSFER_BNNUMBER, "507514946")
        self.click(By.CSS_SELECTOR, self.CONFIRM_TRANSFER_BANK)
        self.click(By.XPATH, self.PURCHASE)
        assert self.assertion(By.XPATH, self.SUCCESS_TITLE) == ''
        self.click(By.XPATH, self.BACK_TO_HOME)

    def invalid_branch_no_payment_bank_transfer(self):
        self.setup_trado()
        self.click(By.XPATH, self.COCTAIL)
        self.click(By.XPATH, self.SAVE)
        self.click(By.XPATH, self.CANABIS_CATEGORY)
        self.click(By.XPATH, self.LEMON_OIL_PRO)
        self.click(By.XPATH, self.LEMON_ADD)
        self.click(By.XPATH, self.SALES_CATEGORY)
        self.click(By.XPATH, self.ULTRA_PRO)
        self.click(By.XPATH, self.ULTRA_SOUR_ADD)
        self.click(By.XPATH, self.CHECKOUT)
        self.fields(By.XPATH, self.PHONE_FIELD, "0502006336")
        self.checkbox(By.XPATH, self.CHECK_BOX)
        self.click(By.XPATH, self.CONNECT)
        self.fields(By.XPATH, self.FILL_ONE, self.code_generator())
        self.click(By.XPATH, self.AUTHENTICATION)
        self.click(By.XPATH, self.CHECKOUT)
        self.fields(By.XPATH, self.BUSINESS_NAME_FIELD, "Teamthree")
        self.fields(By.XPATH, self.BN_NUMBER_FIELD, "515074946")
        self.fields(By.XPATH, self.EMAIL_FIELD, "abcd@gmail.com")
        self.fields(By.XPATH, self.CITY_FIELD, "באר שבע, Israel")
        self.fields(By.XPATH, self.STREET_FIELD, "5")
        self.fields(By.XPATH, self.NUMBER_FIELD, "3")
        self.fields(By.XPATH, self.ENTRANCE_FIELD, "5")
        self.fields(By.XPATH, self.FLOOR_FIELD, "8")
        self.fields(By.XPATH, self.DELIVERY_CITY_FIELD, "תל אביב, Israel")
        self.fields(By.XPATH, self.DELIVERY_STREET_FIELD, "5")
        self.fields(By.XPATH, self.DELIVERY_NUMBER_FIELD, "7")
        self.fields(By.XPATH, self.DELIVERY_ENTRANCE_FIELD, "9")
        self.fields(By.XPATH, self.DELIVERY_FLOOR_FIELD, "3")
        self.fields(By.XPATH, self.CONTACT_RECIVER_NAME, "team")
        self.fields(By.XPATH, self.FIRST_NAME_FIELD, "peace")
        self.fields(By.XPATH, self.LAST_NAME_FIELD, "love")
        self.fields(By.XPATH, self.TELEPHONE_FIELD, "0526802789")
        self.click(By.XPATH, self.COMPLETE_PURCHASE)
        self.click(By.XPATH, self.BANK_TRANSFER)
        self.selector(By.XPATH, self.BANK_NAME_TRANSFER, "9 - בנק הדואר")
        self.fields(By.XPATH, self.BRANCH_TRANSFER, "")
        self.fields(By.XPATH, self.TRANSFER_ACCOUNT_NO, "")
        self.fields(By.XPATH, self.ACCOUNT_HOLDER_NAME_TRANSFER, "")
        self.fields(By.XPATH, self.TRANSFER_BNNUMBER, "507514946")
        self.click(By.CSS_SELECTOR, self.CONFIRM_TRANSFER_BANK)
        self.click(By.XPATH, self.PURCHASE)
        assert self.assertion(By.XPATH, self.SUCCESS_TITLE) == 'fill the blank'
        self.click(By.XPATH, self.BACK_TO_HOME)


    def invalid_invoice_Business_name(self):
        self.setup_trado()
        self.click(By.XPATH, self.COCTAIL)
        self.click(By.XPATH, self.SAVE)
        self.click(By.XPATH, self.CANABIS_CATEGORY)
        self.click(By.XPATH, self.LEMON_OIL_PRO)
        self.click(By.XPATH, self.LEMON_ADD)
        self.click(By.XPATH, self.SALES_CATEGORY)
        self.click(By.XPATH, self.ULTRA_PRO)
        self.click(By.XPATH, self.ULTRA_SOUR_ADD)
        self.click(By.XPATH, self.CHECKOUT)
        self.fields(By.XPATH, self.PHONE_FIELD, "0502006336")
        self.checkbox(By.XPATH, self.CHECK_BOX)
        self.click(By.XPATH, self.CONNECT)
        self.fields(By.XPATH, self.FILL_ONE, self.code_generator())
        self.click(By.XPATH, self.AUTHENTICATION)
        self.click(By.XPATH, self.CHECKOUT)
        self.fields(By.XPATH, self.BUSINESS_NAME_FIELD, "")
        self.fields(By.XPATH, self.BN_NUMBER_FIELD, "515074948")
        self.fields(By.XPATH, self.EMAIL_FIELD, "abcd@gmail.com")
        self.fields(By.XPATH, self.CITY_FIELD, "beersheva")
        self.fields(By.XPATH, self.STREET_FIELD, "7")
        self.fields(By.XPATH, self.NUMBER_FIELD, "3")
        self.fields(By.XPATH, self.ENTRANCE_FIELD, "5")
        self.fields(By.XPATH, self.FLOOR_FIELD, "4")
        self.fields(By.XPATH, self.DELIVERY_CITY_FIELD, "beersheva")
        self.fields(By.XPATH, self.DELIVERY_STREET_FIELD, "5")
        self.fields(By.XPATH, self.DELIVERY_NUMBER_FIELD, "8")
        self.fields(By.XPATH, self.DELIVERY_ENTRANCE_FIELD, "7")
        self.fields(By.XPATH, self.DELIVERY_FLOOR_FIELD, "4")
        self.fields(By.XPATH, self.CONTACT_RECIVER_NAME, "gashu")
        self.fields(By.XPATH, self.FIRST_NAME_FIELD, "true")
        self.fields(By.XPATH, self.LAST_NAME_FIELD, "one")
        self.fields(By.XPATH, self.TELEPHONE_FIELD, "0529874563")
        self.click(By.XPATH, self.COMPLETE_PURCHASE)
        if self.assertion(By.XPATH, self.ERROR_INVOICE) == 'נא למלא שדה זה':
            print("success")
        else:
            print("Failed")

    def invalid_invoice_BNnumber(self):
        self.setup_trado()
        self.click(By.XPATH, self.COCTAIL)
        self.click(By.XPATH, self.SAVE)
        self.click(By.XPATH, self.CANABIS_CATEGORY)
        self.click(By.XPATH, self.LEMON_OIL_PRO)
        self.click(By.XPATH, self.LEMON_ADD)
        self.click(By.XPATH, self.SALES_CATEGORY)
        self.click(By.XPATH, self.ULTRA_PRO)
        self.click(By.XPATH, self.ULTRA_SOUR_ADD)
        self.click(By.XPATH, self.CHECKOUT)
        self.fields(By.XPATH, self.PHONE_FIELD, "0502006336")
        self.checkbox(By.XPATH, self.CHECK_BOX)
        self.click(By.XPATH, self.CONNECT)
        self.fields(By.XPATH, self.FILL_ONE, self.code_generator())
        self.click(By.XPATH, self.AUTHENTICATION)
        self.click(By.XPATH, self.CHECKOUT)
        self.fields(By.XPATH, self.BUSINESS_NAME_FIELD, "Gashu")
        self.fields(By.XPATH, self.BN_NUMBER_FIELD, "")
        self.fields(By.XPATH, self.EMAIL_FIELD, "abcd@gmail.com")
        self.fields(By.XPATH, self.CITY_FIELD, "באר שבע, Israel")
        self.fields(By.XPATH, self.STREET_FIELD, "5")
        self.fields(By.XPATH, self.NUMBER_FIELD, "3")
        self.fields(By.XPATH, self.ENTRANCE_FIELD, "5")
        self.fields(By.XPATH, self.FLOOR_FIELD, "8")
        self.fields(By.XPATH, self.DELIVERY_CITY_FIELD, "תל אביב, Israel")
        self.fields(By.XPATH, self.DELIVERY_STREET_FIELD, "5")
        self.fields(By.XPATH, self.DELIVERY_NUMBER_FIELD, "7")
        self.fields(By.XPATH, self.DELIVERY_ENTRANCE_FIELD, "9")
        self.fields(By.XPATH, self.DELIVERY_FLOOR_FIELD, "3")
        self.fields(By.XPATH, self.CONTACT_RECIVER_NAME, "team")
        self.fields(By.XPATH, self.FIRST_NAME_FIELD, "peace")
        self.fields(By.XPATH, self.LAST_NAME_FIELD, "love")
        self.fields(By.XPATH, self.TELEPHONE_FIELD, "0526802789")
        self.click(By.XPATH, self.COMPLETE_PURCHASE)
        if self.assertion(By.XPATH, self.ASERT_BN) == 'נא למלא שדה זה':
            print("Passed")
        else:
            print("Test Failed")

    def invalid_invoice_email(self):
        self.setup_trado()
        self.click(By.XPATH, self.COCTAIL)
        self.click(By.XPATH, self.SAVE)
        self.click(By.XPATH, self.CANABIS_CATEGORY)
        self.click(By.XPATH, self.LEMON_OIL_PRO)
        self.click(By.XPATH, self.LEMON_ADD)
        self.click(By.XPATH, self.SALES_CATEGORY)
        self.click(By.XPATH, self.ULTRA_PRO)
        self.click(By.XPATH, self.ULTRA_SOUR_ADD)
        self.click(By.XPATH, self.CHECKOUT)
        self.fields(By.XPATH, self.PHONE_FIELD, "0502006336")
        self.checkbox(By.XPATH, self.CHECK_BOX)
        self.click(By.XPATH, self.CONNECT)
        self.fields(By.XPATH, self.FILL_ONE, self.code_generator())
        self.click(By.XPATH, self.AUTHENTICATION)
        self.click(By.XPATH, self.CHECKOUT)
        self.fields(By.XPATH, self.BUSINESS_NAME_FIELD, "Gashu")
        self.fields(By.XPATH, self.BN_NUMBER_FIELD, "515074946")
        self.fields(By.XPATH, self.EMAIL_FIELD, "")
        self.fields(By.XPATH, self.CITY_FIELD, "באר שבע, Israel")
        self.fields(By.XPATH, self.STREET_FIELD, "5")
        self.fields(By.XPATH, self.NUMBER_FIELD, "3")
        self.fields(By.XPATH, self.ENTRANCE_FIELD, "5")
        self.fields(By.XPATH, self.FLOOR_FIELD, "8")
        self.fields(By.XPATH, self.DELIVERY_CITY_FIELD, "תל אביב, Israel")
        self.fields(By.XPATH, self.DELIVERY_STREET_FIELD, "5")
        self.fields(By.XPATH, self.DELIVERY_NUMBER_FIELD, "7")
        self.fields(By.XPATH, self.DELIVERY_ENTRANCE_FIELD, "9")
        self.fields(By.XPATH, self.DELIVERY_FLOOR_FIELD, "3")
        self.fields(By.XPATH, self.CONTACT_RECIVER_NAME, "team")
        self.fields(By.XPATH, self.FIRST_NAME_FIELD, "peace")
        self.fields(By.XPATH, self.LAST_NAME_FIELD, "love")
        self.fields(By.XPATH, self.TELEPHONE_FIELD, "0526802789")
        self.click(By.XPATH, self.COMPLETE_PURCHASE)
        if self.assertion(By.XPATH, self.ASERT_EMAIL) == 'נא למלא שדה זה':
            print("Passed")
        else:
            print("Test Failed")

    def invalid_invoice_CITY(self):
        self.setup_trado()
        self.click(By.XPATH, self.COCTAIL)
        self.click(By.XPATH, self.SAVE)
        self.click(By.XPATH, self.CANABIS_CATEGORY)
        self.click(By.XPATH, self.LEMON_OIL_PRO)
        self.click(By.XPATH, self.LEMON_ADD)
        self.click(By.XPATH, self.SALES_CATEGORY)
        self.click(By.XPATH, self.ULTRA_PRO)
        self.click(By.XPATH, self.ULTRA_SOUR_ADD)
        self.click(By.XPATH, self.CHECKOUT)
        self.fields(By.XPATH, self.PHONE_FIELD, "0502006336")
        self.checkbox(By.XPATH, self.CHECK_BOX)
        self.click(By.XPATH, self.CONNECT)
        self.fields(By.XPATH, self.FILL_ONE, self.code_generator())
        self.click(By.XPATH, self.AUTHENTICATION)
        self.click(By.XPATH, self.CHECKOUT)
        self.fields(By.XPATH, self.BUSINESS_NAME_FIELD, "Gashu")
        self.fields(By.XPATH, self.BN_NUMBER_FIELD, "515074946")
        self.fields(By.XPATH, self.EMAIL_FIELD, "abcd@gmail.com")
        self.fields(By.XPATH, self.CITY_FIELD, "")
        self.fields(By.XPATH, self.STREET_FIELD, "באר שבע")
        self.fields(By.XPATH, self.NUMBER_FIELD, "3")
        self.fields(By.XPATH, self.ENTRANCE_FIELD, "5")
        self.fields(By.XPATH, self.FLOOR_FIELD, "8")
        self.fields(By.XPATH, self.DELIVERY_CITY_FIELD, "תל אביב, Israel")
        self.fields(By.XPATH, self.DELIVERY_STREET_FIELD, "5")
        self.fields(By.XPATH, self.DELIVERY_NUMBER_FIELD, "7")
        self.fields(By.XPATH, self.DELIVERY_ENTRANCE_FIELD, "9")
        self.fields(By.XPATH, self.DELIVERY_FLOOR_FIELD, "3")
        self.fields(By.XPATH, self.CONTACT_RECIVER_NAME, "team")
        self.fields(By.XPATH, self.FIRST_NAME_FIELD, "peace")
        self.fields(By.XPATH, self.LAST_NAME_FIELD, "love")
        self.fields(By.XPATH, self.TELEPHONE_FIELD, "0526802789")
        self.click(By.XPATH, self.COMPLETE_PURCHASE)
        if self.assertion(By.XPATH, self.ASERT_CITY) == 'נא למלא שדה זה':
            print("Passed")
        else:
            print("Test Failed")

    def invalid_invoice_STREEETNO(self):
        self.setup_trado()
        self.click(By.XPATH, self.COCTAIL)
        self.click(By.XPATH, self.SAVE)
        self.click(By.XPATH, self.CANABIS_CATEGORY)
        self.click(By.XPATH, self.LEMON_OIL_PRO)
        self.click(By.XPATH, self.LEMON_ADD)
        self.click(By.XPATH, self.SALES_CATEGORY)
        self.click(By.XPATH, self.ULTRA_PRO)
        self.click(By.XPATH, self.ULTRA_SOUR_ADD)
        self.click(By.XPATH, self.CHECKOUT)
        self.fields(By.XPATH, self.PHONE_FIELD, "0502006336")
        self.checkbox(By.XPATH, self.CHECK_BOX)
        self.click(By.XPATH, self.CONNECT)
        self.fields(By.XPATH, self.FILL_ONE, self.code_generator())
        self.click(By.XPATH, self.AUTHENTICATION)
        self.click(By.XPATH, self.CHECKOUT)
        self.fields(By.XPATH, self.BUSINESS_NAME_FIELD, "Gashu")
        self.fields(By.XPATH, self.BN_NUMBER_FIELD, "515074946")
        self.fields(By.XPATH, self.EMAIL_FIELD, "abcd@gmail.com")
        self.fields(By.XPATH, self.CITY_FIELD, "באר שבע, Israel")
        self.fields(By.XPATH, self.STREET_FIELD, "")
        self.fields(By.XPATH, self.NUMBER_FIELD, "3")
        self.fields(By.XPATH, self.ENTRANCE_FIELD, "5")
        self.fields(By.XPATH, self.FLOOR_FIELD, "8")
        self.fields(By.XPATH, self.DELIVERY_CITY_FIELD, "תל אביב, Israel")
        self.fields(By.XPATH, self.DELIVERY_STREET_FIELD, "5")
        self.fields(By.XPATH, self.DELIVERY_NUMBER_FIELD, "7")
        self.fields(By.XPATH, self.DELIVERY_ENTRANCE_FIELD, "9")
        self.fields(By.XPATH, self.DELIVERY_FLOOR_FIELD, "3")
        self.fields(By.XPATH, self.CONTACT_RECIVER_NAME, "team")
        self.fields(By.XPATH, self.FIRST_NAME_FIELD, "peace")
        self.fields(By.XPATH, self.LAST_NAME_FIELD, "love")
        self.fields(By.XPATH, self.TELEPHONE_FIELD, "0526802789")
        self.click(By.XPATH, self.COMPLETE_PURCHASE)
        if self.assertion(By.XPATH, self.ASERT_STREET) == 'נא למלא שדה זה':
            print("Passed")
        else:
            print("Test Failed")

    def invalid_invoice_HOUSENO(self):
        self.setup_trado()
        self.click(By.XPATH, self.COCTAIL)
        self.click(By.XPATH, self.SAVE)
        self.click(By.XPATH, self.CANABIS_CATEGORY)
        self.click(By.XPATH, self.LEMON_OIL_PRO)
        self.click(By.XPATH, self.LEMON_ADD)
        self.click(By.XPATH, self.SALES_CATEGORY)
        self.click(By.XPATH, self.ULTRA_PRO)
        self.click(By.XPATH, self.ULTRA_SOUR_ADD)
        self.click(By.XPATH, self.CHECKOUT)
        self.fields(By.XPATH, self.PHONE_FIELD, "0502006336")
        self.checkbox(By.XPATH, self.CHECK_BOX)
        self.click(By.XPATH, self.CONNECT)
        self.fields(By.XPATH, self.FILL_ONE, self.code_generator())
        self.click(By.XPATH, self.AUTHENTICATION)
        self.click(By.XPATH, self.CHECKOUT)
        self.fields(By.XPATH, self.BUSINESS_NAME_FIELD, "Gashu")
        self.fields(By.XPATH, self.BN_NUMBER_FIELD, "515074946")
        self.fields(By.XPATH, self.EMAIL_FIELD, "abcd@gmail.com")
        self.fields(By.XPATH, self.CITY_FIELD, "באר שבע, Israel")
        self.fields(By.XPATH, self.STREET_FIELD, "באר שבע")
        self.fields(By.XPATH, self.NUMBER_FIELD, "")
        self.fields(By.XPATH, self.ENTRANCE_FIELD, "5")
        self.fields(By.XPATH, self.FLOOR_FIELD, "8")
        self.fields(By.XPATH, self.DELIVERY_CITY_FIELD, "תל אביב, Israel")
        self.fields(By.XPATH, self.DELIVERY_STREET_FIELD, "5")
        self.fields(By.XPATH, self.DELIVERY_NUMBER_FIELD, "7")
        self.fields(By.XPATH, self.DELIVERY_ENTRANCE_FIELD, "9")
        self.fields(By.XPATH, self.DELIVERY_FLOOR_FIELD, "3")
        self.fields(By.XPATH, self.CONTACT_RECIVER_NAME, "team")
        self.fields(By.XPATH, self.FIRST_NAME_FIELD, "peace")
        self.fields(By.XPATH, self.LAST_NAME_FIELD, "love")
        self.fields(By.XPATH, self.TELEPHONE_FIELD, "0526802789")
        self.click(By.XPATH, self.COMPLETE_PURCHASE)
        if self.assertion(By.XPATH, self.ASERT_HOUSENO) == 'נא למלא שדה זה':
            print("Passed")
        else:
            print("Test Failed")

    def invalid_invoice_ENTRANCE(self):
        self.setup_trado()
        self.click(By.XPATH, self.COCTAIL)
        self.click(By.XPATH, self.SAVE)
        self.click(By.XPATH, self.CANABIS_CATEGORY)
        self.click(By.XPATH, self.LEMON_OIL_PRO)
        self.click(By.XPATH, self.LEMON_ADD)
        self.click(By.XPATH, self.SALES_CATEGORY)
        self.click(By.XPATH, self.ULTRA_PRO)
        self.click(By.XPATH, self.ULTRA_SOUR_ADD)
        self.click(By.XPATH, self.CHECKOUT)
        self.fields(By.XPATH, self.PHONE_FIELD, "0502006336")
        self.checkbox(By.XPATH, self.CHECK_BOX)
        self.click(By.XPATH, self.CONNECT)
        self.fields(By.XPATH, self.FILL_ONE, self.code_generator())
        self.click(By.XPATH, self.AUTHENTICATION)
        self.click(By.XPATH, self.CHECKOUT)
        self.fields(By.XPATH, self.BUSINESS_NAME_FIELD, "Gashu")
        self.fields(By.XPATH, self.BN_NUMBER_FIELD, "515074946")
        self.fields(By.XPATH, self.EMAIL_FIELD, "abcd@gmail.com")
        self.fields(By.XPATH, self.CITY_FIELD, "באר שבע, Israel")
        self.fields(By.XPATH, self.STREET_FIELD, "באר שבע")
        self.fields(By.XPATH, self.NUMBER_FIELD, "4")
        self.fields(By.XPATH, self.ENTRANCE_FIELD, "")
        self.fields(By.XPATH, self.FLOOR_FIELD, "8")
        self.fields(By.XPATH, self.DELIVERY_CITY_FIELD, "תל אביב, Israel")
        self.fields(By.XPATH, self.DELIVERY_STREET_FIELD, "5")
        self.fields(By.XPATH, self.DELIVERY_NUMBER_FIELD, "7")
        self.fields(By.XPATH, self.DELIVERY_ENTRANCE_FIELD, "5")
        self.fields(By.XPATH, self.DELIVERY_FLOOR_FIELD, "3")
        self.fields(By.XPATH, self.CONTACT_RECIVER_NAME, "team")
        self.fields(By.XPATH, self.FIRST_NAME_FIELD, "peace")
        self.fields(By.XPATH, self.LAST_NAME_FIELD, "love")
        self.fields(By.XPATH, self.TELEPHONE_FIELD, "0526802789")
        self.click(By.XPATH, self.COMPLETE_PURCHASE)
        assert self.assertion(By.XPATH, self.ASERT_ENTRANCE) == 'נא למלא שדה זה'

    def invalid_invoice_FLOORNO(self):
        self.setup_trado()
        self.click(By.XPATH, self.COCTAIL)
        self.click(By.XPATH, self.SAVE)
        self.click(By.XPATH, self.CANABIS_CATEGORY)
        self.click(By.XPATH, self.LEMON_OIL_PRO)
        self.click(By.XPATH, self.LEMON_ADD)
        self.click(By.XPATH, self.SALES_CATEGORY)
        self.click(By.XPATH, self.ULTRA_PRO)
        self.click(By.XPATH, self.ULTRA_SOUR_ADD)
        self.click(By.XPATH, self.CHECKOUT)
        self.fields(By.XPATH, self.PHONE_FIELD, "0502006336")
        self.checkbox(By.XPATH, self.CHECK_BOX)
        self.click(By.XPATH, self.CONNECT)
        self.fields(By.XPATH, self.FILL_ONE, self.code_generator())
        self.click(By.XPATH, self.AUTHENTICATION)
        self.click(By.XPATH, self.CHECKOUT)
        self.fields(By.XPATH, self.BUSINESS_NAME_FIELD, "Gashu")
        self.fields(By.XPATH, self.BN_NUMBER_FIELD, "515074946")
        self.fields(By.XPATH, self.EMAIL_FIELD, "abcd@gmail.com")
        self.fields(By.XPATH, self.CITY_FIELD, "באר שבע, Israel")
        self.fields(By.XPATH, self.STREET_FIELD, "באר שבע")
        self.fields(By.XPATH, self.NUMBER_FIELD, "5")
        self.fields(By.XPATH, self.ENTRANCE_FIELD, "")
        self.fields(By.XPATH, self.FLOOR_FIELD, "")

        self.fields(By.XPATH, self.DELIVERY_CITY_FIELD, "תל אביב, Israel")
        self.fields(By.XPATH, self.DELIVERY_STREET_FIELD, "5")
        self.fields(By.XPATH, self.DELIVERY_NUMBER_FIELD, "7")
        self.fields(By.XPATH, self.DELIVERY_ENTRANCE_FIELD, "4")
        self.fields(By.XPATH, self.DELIVERY_FLOOR_FIELD, "7")
        self.fields(By.XPATH, self.CONTACT_RECIVER_NAME, "team")
        self.fields(By.XPATH, self.FIRST_NAME_FIELD, "peace")
        self.fields(By.XPATH, self.LAST_NAME_FIELD, "love")
        self.fields(By.XPATH, self.TELEPHONE_FIELD, "0526802789")
        self.click(By.XPATH, self.COMPLETE_PURCHASE)
        if self.assertion(By.XPATH, self.ASERT_ENTRANCE) == 'נא למלא שדה זה':
            print("Passed")
        else:
            print("Test Failed")

    def invalid_invoice_TOWN(self):
        self.setup_trado()
        self.click(By.XPATH, self.COCTAIL)
        self.click(By.XPATH, self.SAVE)
        self.click(By.XPATH, self.CANABIS_CATEGORY)
        self.click(By.XPATH, self.LEMON_OIL_PRO)
        self.click(By.XPATH, self.LEMON_ADD)
        self.click(By.XPATH, self.SALES_CATEGORY)
        self.click(By.XPATH, self.ULTRA_PRO)
        self.click(By.XPATH, self.ULTRA_SOUR_ADD)
        self.click(By.XPATH, self.CHECKOUT)
        self.fields(By.XPATH, self.PHONE_FIELD, "0502006336")
        self.checkbox(By.XPATH, self.CHECK_BOX)
        self.click(By.XPATH, self.CONNECT)
        self.fields(By.XPATH, self.FILL_ONE, self.code_generator())
        self.click(By.XPATH, self.AUTHENTICATION)
        self.click(By.XPATH, self.CHECKOUT)
        self.fields(By.XPATH, self.BUSINESS_NAME_FIELD, "Gashu")
        self.fields(By.XPATH, self.BN_NUMBER_FIELD, "515074946")
        self.fields(By.XPATH, self.EMAIL_FIELD, "abcd@gmail.com")
        self.fields(By.XPATH, self.CITY_FIELD, "באר שבע, Israel")
        self.fields(By.XPATH, self.STREET_FIELD, "באר שבע ")
        self.fields(By.XPATH, self.NUMBER_FIELD, "3")
        self.fields(By.XPATH, self.ENTRANCE_FIELD, "5")
        self.fields(By.XPATH, self.FLOOR_FIELD, "8")
        self.fields(By.XPATH, self.DELIVERY_CITY_FIELD, "")
        self.fields(By.XPATH, self.DELIVERY_STREET_FIELD, "5")
        self.fields(By.XPATH, self.DELIVERY_NUMBER_FIELD, "7")
        self.fields(By.XPATH, self.DELIVERY_ENTRANCE_FIELD, "9")
        self.fields(By.XPATH, self.DELIVERY_FLOOR_FIELD, "3")
        self.fields(By.XPATH, self.CONTACT_RECIVER_NAME, "team")
        self.fields(By.XPATH, self.FIRST_NAME_FIELD, "peace")
        self.fields(By.XPATH, self.LAST_NAME_FIELD, "love")
        self.fields(By.XPATH, self.TELEPHONE_FIELD, "0526802789")
        self.click(By.XPATH, self.COMPLETE_PURCHASE)
        if self.assertion(By.XPATH, self.TOWN_ASERT) == 'נא למלא שדה זה':
            print("Passed")
        else:
            print("Test Failed")

    def invalid_invoice_STREET_DELIVERY(self):
        self.setup_trado()
        self.click(By.XPATH, self.COCTAIL)
        self.click(By.XPATH, self.SAVE)
        self.click(By.XPATH, self.CANABIS_CATEGORY)
        self.click(By.XPATH, self.LEMON_OIL_PRO)
        self.click(By.XPATH, self.LEMON_ADD)
        self.click(By.XPATH, self.SALES_CATEGORY)
        self.click(By.XPATH, self.ULTRA_PRO)
        self.click(By.XPATH, self.ULTRA_SOUR_ADD)
        self.click(By.XPATH, self.CHECKOUT)
        self.fields(By.XPATH, self.PHONE_FIELD, "0502006336")
        self.checkbox(By.XPATH, self.CHECK_BOX)
        self.click(By.XPATH, self.CONNECT)
        self.fields(By.XPATH, self.FILL_ONE, self.code_generator())
        self.click(By.XPATH, self.AUTHENTICATION)
        self.click(By.XPATH, self.CHECKOUT)
        self.fields(By.XPATH, self.BUSINESS_NAME_FIELD, "Gashu")
        self.fields(By.XPATH, self.BN_NUMBER_FIELD, "515074946")
        self.fields(By.XPATH, self.EMAIL_FIELD, "abcd@gmail.com")
        self.fields(By.XPATH, self.CITY_FIELD, "באר שבע, Israel")
        self.fields(By.XPATH, self.STREET_FIELD, "באר שבע ")
        self.fields(By.XPATH, self.NUMBER_FIELD, "3")
        self.fields(By.XPATH, self.ENTRANCE_FIELD, "5")
        self.fields(By.XPATH, self.FLOOR_FIELD, "8")
        self.fields(By.XPATH, self.DELIVERY_CITY_FIELD, "תל אביב, Israel")
        self.fields(By.XPATH, self.DELIVERY_STREET_FIELD, "")
        self.fields(By.XPATH, self.DELIVERY_NUMBER_FIELD, "7")
        self.fields(By.XPATH, self.DELIVERY_ENTRANCE_FIELD, "9")
        self.fields(By.XPATH, self.DELIVERY_FLOOR_FIELD, "3")
        self.fields(By.XPATH, self.CONTACT_RECIVER_NAME, "team")
        self.fields(By.XPATH, self.FIRST_NAME_FIELD, "peace")
        self.fields(By.XPATH, self.LAST_NAME_FIELD, "love")
        self.fields(By.XPATH, self.TELEPHONE_FIELD, "0526802789")
        self.click(By.XPATH, self.COMPLETE_PURCHASE)
        if self.assertion(By.XPATH, self.STREET_ASERT) == 'נא למלא שדה זה':
            print("Passed")
        else:
            print("Test Failed")

    def invalid_invoice_DELIVERY_HOUSENO(self):
        self.setup_trado()
        self.click(By.XPATH, self.COCTAIL)
        self.click(By.XPATH, self.SAVE)
        self.click(By.XPATH, self.CANABIS_CATEGORY)
        self.click(By.XPATH, self.LEMON_OIL_PRO)
        self.click(By.XPATH, self.LEMON_ADD)
        self.click(By.XPATH, self.SALES_CATEGORY)
        self.click(By.XPATH, self.ULTRA_PRO)
        self.click(By.XPATH, self.ULTRA_SOUR_ADD)
        self.click(By.XPATH, self.CHECKOUT)
        self.fields(By.XPATH, self.PHONE_FIELD, "0502006336")
        self.checkbox(By.XPATH, self.CHECK_BOX)
        self.click(By.XPATH, self.CONNECT)
        self.fields(By.XPATH, self.FILL_ONE, self.code_generator())
        self.click(By.XPATH, self.AUTHENTICATION)
        self.click(By.XPATH, self.CHECKOUT)
        self.fields(By.XPATH, self.BUSINESS_NAME_FIELD, "Gashu")
        self.fields(By.XPATH, self.BN_NUMBER_FIELD, "515074946")
        self.fields(By.XPATH, self.EMAIL_FIELD, "abcd@gmail.com")
        self.fields(By.XPATH, self.CITY_FIELD, "באר שבע, Israel")
        self.fields(By.XPATH, self.STREET_FIELD, "באר שבע ")
        self.fields(By.XPATH, self.NUMBER_FIELD, "3")
        self.fields(By.XPATH, self.ENTRANCE_FIELD, "5")
        self.fields(By.XPATH, self.FLOOR_FIELD, "8")
        self.fields(By.XPATH, self.DELIVERY_CITY_FIELD, "תל אביב, Israel")
        self.fields(By.XPATH, self.DELIVERY_STREET_FIELD, "באר שבע")
        self.fields(By.XPATH, self.DELIVERY_NUMBER_FIELD, "")
        self.fields(By.XPATH, self.DELIVERY_ENTRANCE_FIELD, "9")
        self.fields(By.XPATH, self.DELIVERY_FLOOR_FIELD, "3")
        self.fields(By.XPATH, self.CONTACT_RECIVER_NAME, "team")
        self.fields(By.XPATH, self.FIRST_NAME_FIELD, "peace")
        self.fields(By.XPATH, self.LAST_NAME_FIELD, "love")
        self.fields(By.XPATH, self.TELEPHONE_FIELD, "0526802789")
        self.click(By.XPATH, self.COMPLETE_PURCHASE)
        if self.assertion(By.XPATH, self.HOUSE_NO_ASERT) == 'נא למלא שדה זה':
            print("Passed")
        else:
            print("Test Failed")

    def invalid_invoice_ENTRANCE_DELIVERY(self):
        self.setup_trado()
        self.click(By.XPATH, self.COCTAIL)
        self.click(By.XPATH, self.SAVE)
        self.click(By.XPATH, self.CANABIS_CATEGORY)
        self.click(By.XPATH, self.LEMON_OIL_PRO)
        self.click(By.XPATH, self.LEMON_ADD)
        self.click(By.XPATH, self.SALES_CATEGORY)
        self.click(By.XPATH, self.ULTRA_PRO)
        self.click(By.XPATH, self.ULTRA_SOUR_ADD)
        self.click(By.XPATH, self.CHECKOUT)
        self.fields(By.XPATH, self.PHONE_FIELD, "0502006336")
        self.checkbox(By.XPATH, self.CHECK_BOX)
        self.click(By.XPATH, self.CONNECT)
        self.fields(By.XPATH, self.FILL_ONE, self.code_generator())
        self.click(By.XPATH, self.AUTHENTICATION)
        self.click(By.XPATH, self.CHECKOUT)
        self.fields(By.XPATH, self.BUSINESS_NAME_FIELD, "Gashu")
        self.fields(By.XPATH, self.BN_NUMBER_FIELD, "515074946")
        self.fields(By.XPATH, self.EMAIL_FIELD, "abcd@gmail.com")
        self.fields(By.XPATH, self.CITY_FIELD, "באר שבע, Israel")
        self.fields(By.XPATH, self.STREET_FIELD, "באר שבע ")
        self.fields(By.XPATH, self.NUMBER_FIELD, "3")
        self.fields(By.XPATH, self.ENTRANCE_FIELD, "5")
        self.fields(By.XPATH, self.FLOOR_FIELD, "8")
        self.fields(By.XPATH, self.DELIVERY_CITY_FIELD, "תל אביב, Israel")
        self.fields(By.XPATH, self.DELIVERY_STREET_FIELD, "באר שבע")
        self.fields(By.XPATH, self.DELIVERY_NUMBER_FIELD, "7")
        self.fields(By.XPATH, self.DELIVERY_ENTRANCE_FIELD, "")
        self.fields(By.XPATH, self.DELIVERY_FLOOR_FIELD, "3")
        self.fields(By.XPATH, self.CONTACT_RECIVER_NAME, "team")
        self.fields(By.XPATH, self.FIRST_NAME_FIELD, "peace")
        self.fields(By.XPATH, self.LAST_NAME_FIELD, "love")
        self.fields(By.XPATH, self.TELEPHONE_FIELD, "0526802789")
        self.click(By.XPATH, self.COMPLETE_PURCHASE)
        if self.assertion(By.XPATH, self.ENTRANCE_ASERT) == 'נא למלא שדה זה':
            print("Passed")
        else:
            print("Test Failed")

    def invalid_delivery_FLOOR(self):
        self.setup_trado()
        self.click(By.XPATH, self.COCTAIL)
        self.click(By.XPATH, self.SAVE)
        self.click(By.XPATH, self.CANABIS_CATEGORY)
        self.click(By.XPATH, self.LEMON_OIL_PRO)
        self.click(By.XPATH, self.LEMON_ADD)
        self.click(By.XPATH, self.SALES_CATEGORY)
        self.click(By.XPATH, self.ULTRA_PRO)
        self.click(By.XPATH, self.ULTRA_SOUR_ADD)
        self.click(By.XPATH, self.CHECKOUT)
        self.fields(By.XPATH, self.PHONE_FIELD, "0502006336")
        self.checkbox(By.XPATH, self.CHECK_BOX)
        self.click(By.XPATH, self.CONNECT)
        self.fields(By.XPATH, self.FILL_ONE, self.code_generator())
        self.click(By.XPATH, self.AUTHENTICATION)
        self.click(By.XPATH, self.CHECKOUT)
        self.fields(By.XPATH, self.BUSINESS_NAME_FIELD, "Gashu")
        self.fields(By.XPATH, self.BN_NUMBER_FIELD, "515074946")
        self.fields(By.XPATH, self.EMAIL_FIELD, "abcd@gmail.com")
        self.fields(By.XPATH, self.CITY_FIELD, "באר שבע, Israel")
        self.fields(By.XPATH, self.STREET_FIELD, "באר שבע ")
        self.fields(By.XPATH, self.NUMBER_FIELD, "3")
        self.fields(By.XPATH, self.ENTRANCE_FIELD, "5")
        self.fields(By.XPATH, self.FLOOR_FIELD, "8")
        self.fields(By.XPATH, self.DELIVERY_CITY_FIELD, "תל אביב, Israel")
        self.fields(By.XPATH, self.DELIVERY_STREET_FIELD, "באר יקוב")
        self.fields(By.XPATH, self.DELIVERY_NUMBER_FIELD, "7")
        self.fields(By.XPATH, self.DELIVERY_ENTRANCE_FIELD, "9")
        self.fields(By.XPATH, self.DELIVERY_FLOOR_FIELD, "")
        self.fields(By.XPATH, self.CONTACT_RECIVER_NAME, "team")
        self.fields(By.XPATH, self.FIRST_NAME_FIELD, "peace")
        self.fields(By.XPATH, self.LAST_NAME_FIELD, "love")
        self.fields(By.XPATH, self.TELEPHONE_FIELD, "0526802789")
        self.click(By.XPATH, self.COMPLETE_PURCHASE)
        if self.assertion(By.XPATH, self.FLOOR_ASERT) == 'נא למלא שדה זה':
            print("Passed")
        else:
            print("Test Failed")

    def invalid_delivery_FIRSTNAME(self):
        self.setup_trado()
        self.click(By.XPATH, self.COCTAIL)
        self.click(By.XPATH, self.SAVE)
        self.click(By.XPATH, self.CANABIS_CATEGORY)
        self.click(By.XPATH, self.LEMON_OIL_PRO)
        self.click(By.XPATH, self.LEMON_ADD)
        self.click(By.XPATH, self.SALES_CATEGORY)
        self.click(By.XPATH, self.ULTRA_PRO)
        self.click(By.XPATH, self.ULTRA_SOUR_ADD)
        self.click(By.XPATH, self.CHECKOUT)
        self.fields(By.XPATH, self.PHONE_FIELD, "0502006336")
        self.checkbox(By.XPATH, self.CHECK_BOX)
        self.click(By.XPATH, self.CONNECT)
        self.fields(By.XPATH, self.FILL_ONE, self.code_generator())
        self.click(By.XPATH, self.AUTHENTICATION)
        self.click(By.XPATH, self.CHECKOUT)
        self.fields(By.XPATH, self.BUSINESS_NAME_FIELD, "Gashu")
        self.fields(By.XPATH, self.BN_NUMBER_FIELD, "515074946")
        self.fields(By.XPATH, self.EMAIL_FIELD, "abcd@gmail.com")
        self.fields(By.XPATH, self.CITY_FIELD, "באר שבע, Israel")
        self.fields(By.XPATH, self.STREET_FIELD, "באר שבע ")
        self.fields(By.XPATH, self.NUMBER_FIELD, "3")
        self.fields(By.XPATH, self.ENTRANCE_FIELD, "5")
        self.fields(By.XPATH, self.FLOOR_FIELD, "8")
        self.fields(By.XPATH, self.DELIVERY_CITY_FIELD, "תל אביב, Israel")
        self.fields(By.XPATH, self.DELIVERY_STREET_FIELD, "ירושלים")
        self.fields(By.XPATH, self.DELIVERY_NUMBER_FIELD, "7")
        self.fields(By.XPATH, self.DELIVERY_ENTRANCE_FIELD, "9")
        self.fields(By.XPATH, self.DELIVERY_FLOOR_FIELD, "3")
        self.fields(By.XPATH, self.CONTACT_RECIVER_NAME, "גשאו")
        self.fields(By.XPATH, self.FIRST_NAME_FIELD, "")
        self.fields(By.XPATH, self.LAST_NAME_FIELD, "love")
        self.fields(By.XPATH, self.TELEPHONE_FIELD, "0526802789")
        self.click(By.XPATH, self.COMPLETE_PURCHASE)
        if self.assertion(By.XPATH, self.FIRST_NAME_ASERT) == 'נא למלא שדה זה':
            print("Passed")
        else:
            print("Test Failed")

    def invalid_delivery_LASTNAME(self):
        self.setup_trado()
        self.click(By.XPATH, self.COCTAIL)
        self.click(By.XPATH, self.SAVE)
        self.click(By.XPATH, self.CANABIS_CATEGORY)
        self.click(By.XPATH, self.LEMON_OIL_PRO)
        self.click(By.XPATH, self.LEMON_ADD)
        self.click(By.XPATH, self.SALES_CATEGORY)
        self.click(By.XPATH, self.ULTRA_PRO)
        self.click(By.XPATH, self.ULTRA_SOUR_ADD)
        self.click(By.XPATH, self.CHECKOUT)
        self.fields(By.XPATH, self.PHONE_FIELD, "0502006336")
        self.checkbox(By.XPATH, self.CHECK_BOX)
        self.click(By.XPATH, self.CONNECT)
        self.fields(By.XPATH, self.FILL_ONE, self.code_generator())
        self.click(By.XPATH, self.AUTHENTICATION)
        self.click(By.XPATH, self.CHECKOUT)
        self.fields(By.XPATH, self.BUSINESS_NAME_FIELD, "Gashu")
        self.fields(By.XPATH, self.BN_NUMBER_FIELD, "515074946")
        self.fields(By.XPATH, self.EMAIL_FIELD, "abcd@gmail.com")
        self.fields(By.XPATH, self.CITY_FIELD, "באר שבע, Israel")
        self.fields(By.XPATH, self.STREET_FIELD, "באר שבע ")
        self.fields(By.XPATH, self.NUMBER_FIELD, "3")
        self.fields(By.XPATH, self.ENTRANCE_FIELD, "5")
        self.fields(By.XPATH, self.FLOOR_FIELD, "8")
        self.fields(By.XPATH, self.DELIVERY_CITY_FIELD, "תל אביב, Israel")
        self.fields(By.XPATH, self.DELIVERY_STREET_FIELD, "בית שמש")
        self.fields(By.XPATH, self.DELIVERY_NUMBER_FIELD, "7")
        self.fields(By.XPATH, self.DELIVERY_ENTRANCE_FIELD, "9")
        self.fields(By.XPATH, self.DELIVERY_FLOOR_FIELD, "3")
        self.fields(By.XPATH, self.CONTACT_RECIVER_NAME, "team")
        self.fields(By.XPATH, self.FIRST_NAME_FIELD, "peace")
        self.fields(By.XPATH, self.LAST_NAME_FIELD, "")
        self.fields(By.XPATH, self.TELEPHONE_FIELD, "0526802789")
        self.click(By.XPATH, self.COMPLETE_PURCHASE)
        if self.assertion(By.XPATH, self.LAST_NAME_ASERT) == 'נא למלא שדה זה':
            print("Passed")
        else:
            print("Test Failed")

    def invalid_CONTACT_DELIVERY(self):
        self.setup_trado()
        self.click(By.XPATH, self.COCTAIL)
        self.click(By.XPATH, self.SAVE)
        self.click(By.XPATH, self.CANABIS_CATEGORY)
        self.click(By.XPATH, self.LEMON_OIL_PRO)
        self.click(By.XPATH, self.LEMON_ADD)
        self.click(By.XPATH, self.SALES_CATEGORY)
        self.click(By.XPATH, self.ULTRA_PRO)
        self.click(By.XPATH, self.ULTRA_SOUR_ADD)
        self.click(By.XPATH, self.CHECKOUT)
        self.fields(By.XPATH, self.PHONE_FIELD, "0502006336")
        self.checkbox(By.XPATH, self.CHECK_BOX)
        self.click(By.XPATH, self.CONNECT)
        self.fields(By.XPATH, self.FILL_ONE, self.code_generator())
        self.click(By.XPATH, self.AUTHENTICATION)
        self.click(By.XPATH, self.CHECKOUT)
        self.fields(By.XPATH, self.BUSINESS_NAME_FIELD, "Gashu")
        self.fields(By.XPATH, self.BN_NUMBER_FIELD, "515074946")
        self.fields(By.XPATH, self.EMAIL_FIELD, "abcd@gmail.com")
        self.fields(By.XPATH, self.CITY_FIELD, "באר שבע, Israel")
        self.fields(By.XPATH, self.STREET_FIELD, "באר שבע ")
        self.fields(By.XPATH, self.NUMBER_FIELD, "3")
        self.fields(By.XPATH, self.ENTRANCE_FIELD, "5")
        self.fields(By.XPATH, self.FLOOR_FIELD, "8")
        self.fields(By.XPATH, self.DELIVERY_CITY_FIELD, "תל אביב, Israel")
        self.fields(By.XPATH, self.DELIVERY_STREET_FIELD, "5")
        self.fields(By.XPATH, self.DELIVERY_NUMBER_FIELD, "7")
        self.fields(By.XPATH, self.DELIVERY_ENTRANCE_FIELD, "9")
        self.fields(By.XPATH, self.DELIVERY_FLOOR_FIELD, "3")
        self.fields(By.XPATH, self.CONTACT_RECIVER_NAME, "")
        self.fields(By.XPATH, self.FIRST_NAME_FIELD, "peace")
        self.fields(By.XPATH, self.LAST_NAME_FIELD, "love")
        self.fields(By.XPATH, self.TELEPHONE_FIELD, "0526802789")
        self.click(By.XPATH, self.COMPLETE_PURCHASE)
        if self.assertion(By.XPATH, self.ASERT_CITY) == 'נא למלא שדה זה':
            print("Passed")
        else:
            print("Test Failed")

    def invalid__PHONENO(self):
        self.setup_trado()
        self.click(By.XPATH, self.COCTAIL)
        self.click(By.XPATH, self.SAVE)
        self.click(By.XPATH, self.CANABIS_CATEGORY)
        self.click(By.XPATH, self.LEMON_OIL_PRO)
        self.click(By.XPATH, self.LEMON_ADD)
        self.click(By.XPATH, self.SALES_CATEGORY)
        self.click(By.XPATH, self.ULTRA_PRO)
        self.click(By.XPATH, self.ULTRA_SOUR_ADD)
        self.click(By.XPATH, self.CHECKOUT)
        self.fields(By.XPATH, self.PHONE_FIELD, "0502006336")
        self.checkbox(By.XPATH, self.CHECK_BOX)
        self.click(By.XPATH, self.CONNECT)
        self.fields(By.XPATH, self.FILL_ONE, self.code_generator())
        self.click(By.XPATH, self.AUTHENTICATION)
        self.click(By.XPATH, self.CHECKOUT)
        self.fields(By.XPATH, self.BUSINESS_NAME_FIELD, "The Notorious")
        self.fields(By.XPATH, self.BN_NUMBER_FIELD, "515074946")
        self.fields(By.XPATH, self.EMAIL_FIELD, "abcd123@gmail.com")
        self.fields(By.XPATH, self.CITY_FIELD, "באר שבע, Israel")
        self.fields(By.XPATH, self.STREET_FIELD, "באר שבע ")
        self.fields(By.XPATH, self.NUMBER_FIELD, "3")
        self.fields(By.XPATH, self.ENTRANCE_FIELD, "5")
        self.fields(By.XPATH, self.FLOOR_FIELD, "8")
        self.fields(By.XPATH, self.DELIVERY_CITY_FIELD, "תל אביב, Israel")
        self.fields(By.XPATH, self.DELIVERY_STREET_FIELD, "רחובות")
        self.fields(By.XPATH, self.DELIVERY_NUMBER_FIELD, "7")
        self.fields(By.XPATH, self.DELIVERY_ENTRANCE_FIELD, "9")
        self.fields(By.XPATH, self.DELIVERY_FLOOR_FIELD, "3")
        self.fields(By.XPATH, self.CONTACT_RECIVER_NAME, "team")
        self.fields(By.XPATH, self.FIRST_NAME_ASERT, "peace")
        self.fields(By.XPATH, self.LAST_NAME_ASERT, "love")
        self.fields(By.XPATH, self.TELEPHONE_FIELD, "")
        self.click(By.XPATH, self.COMPLETE_PURCHASE)
        if self.assertion(By.XPATH, self.ASERT_CITY) == 'נא למלא שדה זה':
            print("Passed")
        else:
            print("Test Failed")

    def delete_product(self):
        self.setup_trado()
        self.click(By.XPATH, self.COCTAIL)
        self.click(By.XPATH, self.SAVE)
        self.click(By.XPATH, self.CANABIS_CATEGORY)
        self.click(By.XPATH, self.LEMON_OIL_PRO)
        self.click(By.XPATH, self.LEMON_ADD)
        self.click(By.XPATH, self.SALES_CATEGORY)
        self.click(By.XPATH, self.ULTRA_PRO)
        self.click(By.XPATH, self.ULTRA_SOUR_ADD)
        self.click(By.XPATH, self.HATIFIM)
        self.click(By.XPATH, self.LEMON_KUSH_PRO)
        self.click(By.XPATH, self.LEMON_KUSH_PRO_ADD)
        self.click(By.XPATH, self.EMPTY_CART)

    def minus_specific_product(self):
        self.setup_trado()
        self.click(By.XPATH, self.COCTAIL)
        self.click(By.XPATH, self.SAVE)
        self.click(By.XPATH, self.CANABIS_CATEGORY)
        self.click(By.XPATH, self.LEMON_OIL_PRO)
        self.click(By.XPATH, self.LEMON_ADD)
        self.click(By.XPATH, self.LEMON_ADD)
        self.click(By.XPATH, self.LEMON_MINUS)
        self.click(By.XPATH, self.SALES_CATEGORY)
        self.click(By.XPATH, self.ULTRA_PRO)
        self.click(By.XPATH, self.ULTRA_SOUR_ADD)
        self.click(By.XPATH, self.ULTRA_SOUR_ADD)
        self.click(By.XPATH, self.ULTRA_SOUR_MINUS)
        self.click(By.XPATH, self.HATIFIM)
        self.click(By.XPATH, self.LEMON_KUSH_PRO)
        self.click(By.XPATH, self.LEMON_KUSH_PRO_ADD)

    def delete_specific_product(self):
        self.setup_trado()
        self.click(By.XPATH, self.COCTAIL)
        self.click(By.XPATH, self.SAVE)
        self.click(By.XPATH, self.CANABIS_CATEGORY)
        self.click(By.XPATH, self.LEMON_OIL_PRO)
        self.click(By.XPATH, self.LEMON_ADD)
        self.click(By.XPATH, self.LEMON_KUSH_DELETE)
        self.click(By.XPATH, self.SALES_CATEGORY)
        self.click(By.XPATH, self.ULTRA_PRO)
        self.click(By.XPATH, self.ULTRA_SOUR_ADD)
        self.click(By.XPATH, self.ULTRA_DELETE)

    def total_price_negative(self):
        self.setup_trado()
        self.click(By.XPATH, self.COCTAIL)
        self.click(By.XPATH, self.SAVE)
        self.click(By.XPATH, self.CANABIS_CATEGORY)
        self.click(By.XPATH, self.LEMON_OIL_PRO)
        self.click(By.XPATH, self.LEMON_ADD)

        self.click(By.XPATH, self.SALES_CATEGORY)
        self.click(By.XPATH, self.ULTRA_PRO)
        self.click(By.XPATH, self.ULTRA_SOUR_ADD)
        assert self.assertion(By.XPATH, self.TOTAL_PRICE) == 'סה״כ:\n₪598'

    def total_price_assertion(self):
        self.setup_trado()
        self.click(By.XPATH, self.COCTAIL)
        self.click(By.XPATH, self.SAVE)
        self.click(By.XPATH, self.CANABIS_CATEGORY)
        self.click(By.XPATH, self.LEMON_OIL_PRO)
        self.click(By.XPATH, self.LEMON_ADD)

        self.click(By.XPATH, self.SALES_CATEGORY)
        self.click(By.XPATH, self.ULTRA_PRO)
        self.click(By.XPATH, self.ULTRA_SOUR_ADD)
        assert self.assertion(By.XPATH, self.TOTAL_PRICE) == 'סה״כ:\n₪598'

    def valid_trado_logo(self):
        self.setup_trado()
        self.click(By.XPATH, self.COCTAIL)
        self.click(By.XPATH, self.SAVE)
        self.click(By.XPATH, self.CANABIS_CATEGORY)
        self.click(By.XPATH, self.LEMON_OIL_PRO)
        self.click(By.XPATH, self.LEMON_ADD)
        self.click(By.XPATH, self.SALES_CATEGORY)
        self.click(By.XPATH, self.ULTRA_PRO)
        self.click(By.XPATH, self.ULTRA_SOUR_ADD)
        self.click(By.XPATH, self.CHECKOUT)
        self.fields(By.XPATH, self.PHONE_FIELD, "0502006336")
        self.checkbox(By.XPATH, self.CHECK_BOX)
        self.click(By.XPATH, self.CONNECT)
        self.fields(By.XPATH, self.FILL_ONE, self.code_generator())
        self.click(By.XPATH, self.AUTHENTICATION)
        self.click(By.XPATH, self.CHECKOUT)
        self.fields(By.XPATH, self.BUSINESS_NAME_FIELD, "Gashu")
        self.fields(By.XPATH, self.BN_NUMBER_FIELD, "515074946")
        self.fields(By.XPATH, self.EMAIL_FIELD, "abcd@gmail.com")
        self.fields(By.XPATH, self.CITY_FIELD, "באר שבע, Israel")
        self.fields(By.XPATH, self.STREET_FIELD, "באר שבע")
        self.fields(By.XPATH, self.NUMBER_FIELD, "5")
        self.fields(By.XPATH, self.ENTRANCE_FIELD, "6")
        self.fields(By.XPATH, self.FLOOR_FIELD, "9")

        self.fields(By.XPATH, self.DELIVERY_CITY_FIELD, "תל אביב, Israel")
        self.fields(By.XPATH, self.DELIVERY_STREET_FIELD, "5")
        self.fields(By.XPATH, self.DELIVERY_NUMBER_FIELD, "7")
        self.fields(By.XPATH, self.DELIVERY_ENTRANCE_FIELD, "4")
        self.fields(By.XPATH, self.DELIVERY_FLOOR_FIELD, "7")
        self.fields(By.XPATH, self.CONTACT_RECIVER_NAME, "team")
        self.fields(By.XPATH, self.FIRST_NAME_FIELD, "peace")
        self.fields(By.XPATH, self.LAST_NAME_FIELD, "love")
        self.fields(By.XPATH, self.TELEPHONE_FIELD, "0526802789")
        self.click(By.XPATH, self.COMPLETE_PURCHASE)
        try:
            assert 'Trado' in self.driver.title
            print('yes')
        except:
            print("Trado is invalid")

    def valid_back_to_page(self):
        self.setup_trado()
        self.click(By.XPATH, self.COCTAIL)
        self.click(By.XPATH, self.SAVE)
        self.click(By.XPATH, self.CANABIS_CATEGORY)
        self.click(By.XPATH, self.LEMON_OIL_PRO)
        self.click(By.XPATH, self.LEMON_ADD)
        self.click(By.XPATH, self.SALES_CATEGORY)
        self.click(By.XPATH, self.ULTRA_PRO)
        self.click(By.XPATH, self.ULTRA_SOUR_ADD)
        self.click(By.XPATH, self.CHECKOUT)
        self.fields(By.XPATH, self.PHONE_FIELD, "0502006336")
        self.checkbox(By.XPATH, self.CHECK_BOX)
        self.click(By.XPATH, self.CONNECT)
        self.fields(By.XPATH, self.FILL_ONE, self.code_generator())
        self.click(By.XPATH, self.AUTHENTICATION)
        self.click(By.XPATH, self.CHECKOUT)
        self.fields(By.XPATH, self.BUSINESS_NAME_FIELD, "Gashu")
        self.fields(By.XPATH, self.BN_NUMBER_FIELD, "515074946")
        self.fields(By.XPATH, self.EMAIL_FIELD, "abcd@gmail.com")
        self.fields(By.XPATH, self.CITY_FIELD, "באר שבע, Israel")
        self.fields(By.XPATH, self.STREET_FIELD, "באר שבע")
        self.fields(By.XPATH, self.NUMBER_FIELD, "5")
        self.fields(By.XPATH, self.ENTRANCE_FIELD, "6")
        self.fields(By.XPATH, self.FLOOR_FIELD, "9")

        self.fields(By.XPATH, self.DELIVERY_CITY_FIELD, "תל אביב, Israel")
        self.fields(By.XPATH, self.DELIVERY_STREET_FIELD, "5")
        self.fields(By.XPATH, self.DELIVERY_NUMBER_FIELD, "7")
        self.fields(By.XPATH, self.DELIVERY_ENTRANCE_FIELD, "4")
        self.fields(By.XPATH, self.DELIVERY_FLOOR_FIELD, "7")
        self.fields(By.XPATH, self.CONTACT_RECIVER_NAME, "team")
        self.fields(By.XPATH, self.FIRST_NAME_FIELD, "peace")
        self.fields(By.XPATH, self.LAST_NAME_FIELD, "love")
        self.fields(By.XPATH, self.TELEPHONE_FIELD, "0526802789")
        self.click(By.XPATH, self.COMPLETE_PURCHASE)
        time.sleep(2)
        self.click(By.XPATH, "")

    def valid_back_to_page_shopping(self):
        self.setup_trado()
        self.click(By.XPATH, self.COCTAIL)
        self.click(By.XPATH, self.SAVE)
        self.click(By.XPATH, self.CANABIS_CATEGORY)
        self.click(By.XPATH, self.LEMON_OIL_PRO)
        self.click(By.XPATH, self.LEMON_ADD)
        self.click(By.XPATH, self.SALES_CATEGORY)
        self.click(By.XPATH, self.ULTRA_PRO)
        self.click(By.XPATH, self.ULTRA_SOUR_ADD)
        self.click(By.XPATH, self.CHECKOUT)
        self.fields(By.XPATH, self.PHONE_FIELD, "0502006336")
        self.checkbox(By.XPATH, self.CHECK_BOX)
        self.click(By.XPATH, self.CONNECT)
        self.fields(By.XPATH, self.FILL_ONE, self.code_generator())
        self.click(By.XPATH, self.AUTHENTICATION)
        self.click(By.XPATH, self.CHECKOUT)
        self.fields(By.XPATH, self.BUSINESS_NAME_FIELD, "Gashu")
        self.fields(By.XPATH, self.BN_NUMBER_FIELD, "515074946")
        self.fields(By.XPATH, self.EMAIL_FIELD, "abcd@gmail.com")
        self.fields(By.XPATH, self.CITY_FIELD, "באר שבע, Israel")
        self.fields(By.XPATH, self.STREET_FIELD, "באר שבע")
        self.fields(By.XPATH, self.NUMBER_FIELD, "5")
        self.fields(By.XPATH, self.ENTRANCE_FIELD, "6")
        self.fields(By.XPATH, self.FLOOR_FIELD, "9")

        self.fields(By.XPATH, self.DELIVERY_CITY_FIELD, "תל אביב, Israel")
        self.fields(By.XPATH, self.DELIVERY_STREET_FIELD, "5")
        self.fields(By.XPATH, self.DELIVERY_NUMBER_FIELD, "7")
        self.fields(By.XPATH, self.DELIVERY_ENTRANCE_FIELD, "4")
        self.fields(By.XPATH, self.DELIVERY_FLOOR_FIELD, "7")
        self.fields(By.XPATH, self.CONTACT_RECIVER_NAME, "team")
        self.fields(By.XPATH, self.FIRST_NAME_FIELD, "peace")
        self.fields(By.XPATH, self.LAST_NAME_FIELD, "love")
        self.fields(By.XPATH, self.TELEPHONE_FIELD, "0526802789")
        self.click(By.XPATH, self.COMPLETE_PURCHASE)
        self.click(By.XPATH, "//body/div[@id='root']/div[1]/div[2]/div[2]/div[1]/div[2]/div[1]/div[3]/span[1]/i[1]")
